### ISSUE TITLE
App crash when entering query in URL input on Browser view

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#10556]
# Bug Report

## Problem

Status app crashes with `java.lanng.IllegalArgumentException: Invalid URL host: ...` error when searching for URL with whitespace at the beginning or simply a query of two words separated by whitespace 
Crash reproduced on Android but on iOS there is a just endless black page with loading indicator
 
#### Expected behavior
1) Trimmed URL value before execution
2) Searching for query with whitespace in the middle (e.g. `aaa bbb`) leads to `Webpage not available` and no crash

#### Actual behavior

<img width="336" alt="Screenshot 2020-05-04 at 12 40 42" src="https://user-images.githubusercontent.com/8749671/80953616-8d4f0180-8e04-11ea-8156-8aba16b9f91e.png">

### Reproduction

- Open Status and create new account
- Open `Browser` view
- Enter `[whitespace]status.im` or `aaa bbb` in the URL input and submit the search  

### Additional Information
- Status version: Release 1.3/develop 1.4
- Operating System: Android

#### Logs

```

--------- beginning of crash
05-04 12:45:18.151 14215 14215 E AndroidRuntime: FATAL EXCEPTION: main
05-04 12:45:18.151 14215 14215 E AndroidRuntime: Process: im.status.ethereum, PID: 14215
05-04 12:45:18.151 14215 14215 E AndroidRuntime: java.lang.IllegalArgumentException: Invalid URL host: "aaaaaaa%20bbbbbbbb"
05-04 12:45:18.151 14215 14215 E AndroidRuntime: 	at okhttp3.HttpUrl$Builder.parse(HttpUrl.java:1405)
05-04 12:45:18.151 14215 14215 E AndroidRuntime: 	at okhttp3.HttpUrl.get(HttpUrl.java:916)
05-04 12:45:18.151 14215 14215 E AndroidRuntime: 	at okhttp3.Request$Builder.url(Request.java:165)
05-04 12:45:18.151 14215 14215 E AndroidRuntime: 	at com.reactnativecommunity.webview.RNCWebViewManager.shouldInterceptRequest(RNCWebViewManager.java:335)
05-04 12:45:18.151 14215 14215 E AndroidRuntime: 	at com.reactnativecommunity.webview.RNCWebViewManager$RNCWebViewClient.shouldInterceptRequest(RNCWebViewManager.java:970)
05-04 12:45:18.151 14215 14215 E AndroidRuntime: 	at xt0.a(PG:15)
05-04 12:45:18.151 14215 14215 E AndroidRuntime: 	at org.chromium.android_webview.AwContentsBackgroundThreadClient.shouldInterceptRequestFromNative(PG:2)
05-04 12:45:18.153 14215 14452 W VideoCapabilities: Unsupported mime video/wvc1
05-04 12:45:18.156 14215 14452 W VideoCapabilities: Unsupported mime video/wvc1
05-04 12:45:18.184 14215 14452 W VideoCapabilities: Unsupported mime video/x-ms-wmv7
05-04 12:45:18.185 14215 14452 W VideoCapabilities: Unsupported mime video/x-ms-wmv8
05-04 12:45:18.198 14215 14452 I VideoCapabilities: Unsupported profile 4 for video/mp4v-es
05-04 12:45:18.202 14215 14256 D ReactNativeJS: DEBUG [status-im.utils.handlers:25] - Handling re-frame event:  :set
05-04 12:45:18.234 14215 14452 D libGLESv2: STS_GLApi : DTS, ODTC are not allowed for Package : im.status.ethereum
05-04 12:45:18.240 14215 14256 D ReactNativeJS: DEBUG [status-im.utils.handlers:25] - Handling re-frame event:  :screens/on-will-focus
05-04 12:45:18.246 14215 14256 D ReactNativeJS: DEBUG [status-im.utils.handlers:25] - Handling re-frame event:  :set
05-04 12:45:18.252 14215 14256 D ReactNativeJS: DEBUG [status-im.utils.handlers:25] - Handling re-frame event:  :screens/on-will-focus
05-04 12:45:18.258 14215 14256 D ReactNativeJS: DEBUG [status-im.utils.handlers:25] - Handling re-frame event:  :set
05-04 12:45:18.490  2614

```

**Comment by churik** [comment]
Crashes from https://github.com/status-im/status-react/issues/5242 are again reproducible
