### ISSUE TITLE
java.lang.AssertionError: No System TLS at attepmt to start app

### ISSUE THREAD

**Issue by churik** [status-im/status-react#10770]
# Bug Report

## Problem

Sometimes e2e are randomly failing when app is starting with "No System TLS" - so far was caught by e2e, not real devices

#### Expected behavior
no error

#### Actual behavior
 Unexpected Alert is shown: 'java.lang.AssertionError: No System TLS'
Examples of e2e:
- https://saucelabs.com/jobs/f1e1aad320d7450bafae12b227b38f09?auth=7cb0d44691bea5fb277a6aa8c2ee019a (~30 % of failures during June)

- https://saucelabs.com/jobs/8b84b6be8e8248eeb2600c4719360b31?auth=d1e7eb68e5b10e96ba49278f3306c4b8 (~16 % of failures during June)

#### Notes
Firstly this error appeared on nightly 04/05/2020

### Reproduction

- Open Status
- Create account
- Restart app

### Additional Information

- Status version: release 1.4
- Operating System: Android (not sure about IOS)

#### Logs

```
06-08 03:23:23.421  6617  6617 D AndroidRuntime: Shutting down VM
--------- beginning of crash
06-08 03:23:23.422  6617  6617 E AndroidRuntime: FATAL EXCEPTION: main
06-08 03:23:23.422  6617  6617 E AndroidRuntime: Process: im.status.ethereum.pr, PID: 6617
06-08 03:23:23.422  6617  6617 E AndroidRuntime: java.lang.AssertionError: No System TLS
06-08 03:23:23.422  6617  6617 E AndroidRuntime: 	at okhttp3.internal.Util.assertionError(Util.java:504)
06-08 03:23:23.422  6617  6617 E AndroidRuntime: 	at okhttp3.OkHttpClient.newSslSocketFactory(OkHttpClient.java:296)
06-08 03:23:23.422  6617  6617 E AndroidRuntime: 	at okhttp3.OkHttpClient.<init>(OkHttpClient.java:258)
06-08 03:23:23.422  6617  6617 E AndroidRuntime: 	at okhttp3.OkHttpClient$Builder.build(OkHttpClient.java:1040)
06-08 03:23:23.422  6617  6617 E AndroidRuntime: 	at com.reactnativecommunity.webview.RNCWebViewManager.<init>(RNCWebViewManager.java:182)
06-08 03:23:23.422  6617  6617 E AndroidRuntime: 	at com.reactnativecommunity.webview.RNCWebViewPackage.createViewManagers(RNCWebViewPackage.kt:13)
06-08 03:23:23.422  6617  6617 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager.getOrCreateViewManagers(ReactInstanceManager.java:830)
06-08 03:23:23.422  6617  6617 E AndroidRuntime: 	at com.facebook.react.CoreModulesPackage.createUIManager(CoreModulesPackage.java:189)
06-08 03:23:23.422  6617  6617 E AndroidRuntime: 	at com.facebook.react.CoreModulesPackage.getModule(CoreModulesPackage.java:157)
06-08 03:23:23.422  6617  6617 E AndroidRuntime: 	at com.facebook.react.TurboReactPackage$ModuleHolderProvider.get(TurboReactPackage.java:159)
06-08 03:23:23.422  6617  6617 E AndroidRuntime: 	at com.facebook.react.TurboReactPackage$ModuleHolderProvider.get(TurboReactPackage.java:147)
06-08 03:23:23.422  6617  6617 E AndroidRuntime: 	at com.facebook.react.bridge.ModuleHolder.create(ModuleHolder.java:191)
06-08 03:23:23.422  6617  6617 E AndroidRuntime: 	at com.facebook.react.bridge.ModuleHolder.getModule(ModuleHolder.java:156)
06-08 03:23:23.422  6617  6617 E AndroidRuntime: 	at com.facebook.react.bridge.NativeModuleRegistry.getModule(NativeModuleRegistry.java:149)
06-08 03:23:23.422  6617  6617 E AndroidRuntime: 	at com.facebook.react.bridge.CatalystInstanceImpl.getNativeModule(CatalystInstanceImpl.java:590)
06-08 03:23:23.422  6617  6617 E AndroidRuntime: 	at com.facebook.react.bridge.CatalystInstanceImpl.getNativeModule(CatalystInstanceImpl.java:567)
06-08 03:23:23.422  6617  6617 E AndroidRuntime: 	at com.facebook.react.uimanager.UIManagerHelper.getUIManager(UIManagerHelper.java:42)
06-08 03:23:23.422  6617  6617 E AndroidRuntime: 	at com.facebook.react.ReactRootView.setAllowImmediateUIOperationExecution(ReactRootView.java:479)
06-08 03:23:23.422  6617  6617 E AndroidRuntime: 	at com.facebook.react.ReactRootView.onMeasure(ReactRootView.java:130)
06-08 03:23:23.422  6617  6617 E AndroidRuntime: 	at android.view.View.measure(View.java:24530)
06-08 03:23:23.422  6617  6617 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6828)
06-08 03:23:23.422  6617  6617 E AndroidRuntime: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
06-08 03:23:23.422  6617  6617 E AndroidRuntime: 	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:143)
06-08 03:23:23.422  6617  6617 E AndroidRuntime: 	at android.view.View.measure(View.java:24530)
06-08 03:23:23.422  6617  6617 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6828)
06-08 03:23:23.422  6617  6617 E AndroidRuntime: 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
06-08 03:23:23.422  6617  6617 E AndroidRuntime: 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
06-08 03:23:23.422  6617  6617 E AndroidRuntime: 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
06-08 03:23:23.422  6617  6617 E AndroidRuntime: 	at android.view.View.measure(View.java:24530)
06-08 03:23:23.422  6617  6617 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6828)
06-08 03:23:23.422  6617  6617 E AndroidRuntime: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
06-08 03:23:23.422  6617  6617 E AndroidRuntime: 	at android.view.View.measure(View.java:24530)
06-08 03:23:23.422  6617  6617 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6828)
06-08 03:23:23.422  6617  6617 E AndroidRuntime: 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
06-08 03:23:23.422  6617  6617 E AndroidRuntime: 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
06-08 03:23:23.422  6617  6617 E AndroidRuntime: 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
06-08 03:23:23.422  6617  6617 E AndroidRuntime: 	at android.view.View.measure(View.java:24530)
06-08 03:23:23.422  6617  6617 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6828)
06-08 03:23:23.422  6617  6617 E AndroidRuntime: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
06-08 03:23:23.422  6617  6617 E AndroidRuntime: 	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:742)
06-08 03:23:23.422  6617  6617 E AndroidRuntime: 	at android.view.View.measure(View.java:24530)
06-08 03:23:23.422  6617  6617 E AndroidRuntime: 	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:3006)
06-08 03:23:23.422  6617  6617 E AndroidRuntime: 	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1833)
06-08 03:23:23.422  6617  6617 E AndroidRuntime: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2122)
06-08 03:23:23.422  6617  6617 E AndroidRuntime: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1721)
06-08 03:23:23.422  6617  6617 E AndroidRuntime: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7598)
06-08 03:23:23.422  6617  6617 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:966)
06-08 03:23:23.422  6617  6617 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:790)
06-08 03:23:23.422  6617  6617 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:725)
06-08 03:23:23.422  6617  6617 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:951)
06-08 03:23:23.422  6617  6617 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:883)
06-08 03:23:23.422  6617  6617 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:100)
06-08 03:23:23.422  6617  6617 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
06-08 03:23:23.422  6617  6617 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7356)
06-08 03:23:23.422  6617  6617 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
06-08 03:23:23.422  6617  6617 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
06-08 03:23:23.422  6617  6617 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
06-08 03:23:23.422  6617  6617 E AndroidRuntime: Caused by: java.security.KeyManagementException: java.security.KeyStoreException: BKS not found
06-08 03:23:23.422  6617  6617 E AndroidRuntime: 	at com.android.org.conscrypt.SSLParametersImpl.createDefaultX509KeyManager(SSLParametersImpl.java:539)
06-08 03:23:23.422  6617  6617 E AndroidRuntime: 	at com.android.org.conscrypt.SSLParametersImpl.getDefaultX509KeyManager(SSLParametersImpl.java:520)
06-08 03:23:23.422  6617  6617 E AndroidRuntime: 	at com.android.org.conscrypt.SSLParametersImpl.<init>(SSLParametersImpl.java:128)
06-08 03:23:23.422  6617  6617 E AndroidRuntime: 	at com.android.org.conscrypt.OpenSSLContextImpl.engineInit(OpenSSLContextImpl.java:111)
06-08 03:23:23.422  6617  6617 E AndroidRuntime: 	at javax.net.ssl.SSLContext.init(SSLContext.java:326)
06-08 03:23:23.422  6617  6617 E AndroidRuntime: 	at okhttp3.OkHttpClient.newSslSocketFactory(OkHttpClient.java:293)
06-08 03:23:23.422  6617  6617 E AndroidRuntime: 	... 55 more
06-08 03:23:23.422  6617  6617 E AndroidRuntime: Caused by: java.security.KeyStoreException: BKS not found
06-08 03:23:23.422  6617  6617 E AndroidRuntime: 	at java.security.KeyStore.getInstance(KeyStore.java:890)
06-08 03:23:23.422  6617  6617 E AndroidRuntime: 	at com.android.org.conscrypt.KeyManagerFactoryImpl.engineInit(KeyManagerFactoryImpl.java:63)
06-08 03:23:23.422  6617  6617 E AndroidRuntime: 	at javax.net.ssl.KeyManagerFactory.init(KeyManagerFactory.java:272)
06-08 03:23:23.422  6617  6617 E AndroidRuntime: 	at com.android.org.conscrypt.SSLParametersImpl.createDefaultX509KeyManager(SSLParametersImpl.java:528)
06-08 03:23:23.422  6617  6617 E AndroidRuntime: 	... 60 more
06-08 03:23:23.422  6617  6617 E AndroidRuntime: Caused by: java.security.NoSuchAlgorithmException: BKS KeyStore not available
06-08 03:23:23.422  6617  6617 E AndroidRuntime: 	at sun.security.jca.GetInstance.getInstance(GetInstance.java:159)
06-08 03:23:23.422  6617  6617 E AndroidRuntime: 	at java.security.Security.getImpl(Security.java:628)
06-08 03:23:23.422  6617  6617 E AndroidRuntime: 	at java.security.KeyStore.getInstance(KeyStore.java:887)
06-08 03:23:23.422  6617  6617 E AndroidRuntime: 	... 63 more
06-08 03:23:23.452  6617  6692 V NFC     : this device does not have NFC support
06-08 03:23:23.452  6617  6692 D SmartCard: not support in this device
06-08 03:23:23.452  6617  6692 D ReactNative: ReactInstanceManager.attachRootViewToInstance()
06-08 03:23:23.500  1778  3173 D gralloc_ranchu: gralloc_alloc: Creating ashmem region of size 1736704
06-08 03:23:23.513  1778  3173 D gralloc_ranchu: gralloc_alloc: Creating ashmem region of size 1736704
06-08 03:23:23.515  6617  6678 D EGL_emulation: eglMakeCurrent: 0xd14f5140: ver 2 0 (tinfo 0xbbda10b0)
06-08 03:23:23.516  1778  1778 D gralloc_ranchu: gralloc_alloc: Creating ashmem region of size 1736704
06-08 03:23:24.337  1777  2284 E GnssHAL_GnssInterface: gnssSvStatusCb: a: input svInfo.flags is 8
06-08 03:23:24.337  1777  2284 E GnssHAL_GnssInterface: gnssSvStatusCb: b: input svInfo.flags is 8
06-08 03:23:24.495  2010  2101 W ActivityManager: Unable to start service Intent { act=com.google.android.gms.drive.ApiService.RESET_AFTER_BOOT flg=0x4 cmp=com.google.android.gms/.drive.api.ApiService (has extras) } U=0: not found
06-08 03:23:24.496  2010  2118 W AlarmManager: Unrecognized alarm listener com.android.server.wifi.WifiConfigStore$2@5306dde
06-08 03:23:24.509  2010  2010 I am_uid_running: 10132
06-08 03:23:24.516  1762  1762 D Zygote  : Forked child process 6705
06-08 03:23:24.520  2010  2045 I am_proc_start: [0,6705,10132,com.google.android.apps.messaging,service,{com.google.android.apps.messaging/com.google.android.apps.messaging.shared.datamodel.action.execution.ActionJobService}]
06-08 03:23:24.520  2010  2045 I ActivityManager: Start proc 6705:com.google.android.apps.messaging/u0a132 for service {com.google.android.apps.messaging/com.google.android.apps.messaging.shared.datamodel.action.execution.ActionJobService}
06-08 03:23:24.522  6705  6705 W .apps.messagin: Unexpected CPU variant for X86 using defaults: x86_64
06-08 03:23:24.569  2010  2118 D WifiConfigStore: Writing to stores completed in 73 ms.
06-08 03:23:24.576  2010  5460 I am_proc_bound: [0,6705,com.google.android.apps.messaging]
06-08 03:23:24.592  2010  2043 E memtrack: Couldn't load memtrack module
06-08 03:23:24.592  2010  2043 W android.os.Debug: failed to get memory consumption info: -1
06-08 03:23:24.596  6705  6705 D ApplicationLoaders: Returning zygote-cached class loader: /system/framework/android.hidl.base-V1.0-java.jar
06-08 03:23:24.596  6705  6705 D ApplicationLoaders: Returning zygote-cached class loader: /system/framework/android.hidl.manager-V1.0-java.jar
06-08 03:23:24.596  6705  6705 D ApplicationLoaders: Returning zygote-cached class loader: /system/framework/android.hidl.base-V1.0-java.jar
06-08 03:23:24.600  6705  6705 I .apps.messagin: The ClassLoaderContext is a special shared library.
06-08 03:23:24.614  2010  2043 I am_pss  : [6165,10096,com.google.android.apps.wallpaper,9447424,5898240,0,82972672,0,20,3]
06-08 03:23:24.628  6705  6705 I .apps.messagin: The ClassLoaderContext is a special shared library.
06-08 03:23:24.738  6705  6705 I MultiDex: VM with version 2.1.0 has multidex support
06-08 03:23:24.738  6705  6705 I MultiDex: install
06-08 03:23:24.738  6705  6705 I MultiDex: VM has multidex support, MultiDex support library is disabled.
```

**Comment by hesterbruikman** [comment]
Issue appeared on 

- Phone model: Galaxy s10e 
- OS: Android 10
- Version: 1.4.0 (20200604071356)
- Action: Launch

App was unresponsive, including dialog. Had to kill the app. Everything was fine on restart. 

![Screenshot_20200610-104201_Status](https://user-images.githubusercontent.com/35233054/84248714-1ba45a80-ab0a-11ea-8b94-63926e232783.jpg)

**Comment by hesterbruikman** [comment]
@Serhy @churik I believe we can close this issue, correct?

**Comment by churik** [comment]
yes
