### ISSUE TITLE
"Invalid timbre logging level" after upgrade from 1.4 to 1.4.1 or relogin on 1.4.1

### ISSUE THREAD

**Issue by churik** [status-im/status-react#10870]
# Bug Report

## Problem

After upgrade and login got an error 
![IMAGE 2020-06-25 11:58:53](https://user-images.githubusercontent.com/4557972/85698759-3e726980-b6db-11ea-972d-db1e70bf1110.jpg)

#### Expected behavior
can upgrade normally 

#### Actual behavior
error after upgrade

### Reproduction

[comment]: # (Describe how we can replicate the bug step by step.)

- Install 1.4 from store
- Upgrade to build from https://ci.status.im/job/status-react/job/release/job/release%252F1.5.x/
- Login

### Additional Information

- Status version:  1.4.1 (builds https://ci.status.im/job/status-react/job/release/job/release%252F1.5.x/)
- Operating System: Android,iOS

#### Logs

```
06-25 11:38:53.952 16546 16636 D ReactNativeJS: DEBUG [status-im.utils.handlers:44] - Handling re-frame event:  :mailserver/check-connection-timeout
06-25 11:39:01.598 16546 16546 D ReactNative: ReactInstanceManager.detachViewFromInstance()
06-25 11:39:01.598 16546 16546 D StatusModule: ******************* ON HOST DESTROY *************************
06-25 11:39:01.601 16546 16636 D ReactNativeJS: DEBUG [status-im.utils.universal-links.core:186] - universal-links: finalizing
06-25 11:39:01.626 16546 16546 E ActivityThread: Activity im.status.ethereum.MainActivity has leaked IntentReceiver im.status.ethereum.keycard.SmartCard@5374d57 that was originally registered here. Are you missing a call to unregisterReceiver()?
06-25 11:39:01.626 16546 16546 E ActivityThread: android.app.IntentReceiverLeaked: Activity im.status.ethereum.MainActivity has leaked IntentReceiver im.status.ethereum.keycard.SmartCard@5374d57 that was originally registered here. Are you missing a call to unregisterReceiver()?
06-25 11:39:01.626 16546 16546 E ActivityThread: 	at android.app.LoadedApk$ReceiverDispatcher.<init>(LoadedApk.java:1596)
06-25 11:39:01.626 16546 16546 E ActivityThread: 	at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:1372)
06-25 11:39:01.626 16546 16546 E ActivityThread: 	at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1525)
06-25 11:39:01.626 16546 16546 E ActivityThread: 	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1498)
06-25 11:39:01.626 16546 16546 E ActivityThread: 	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1486)
06-25 11:39:01.626 16546 16546 E ActivityThread: 	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:637)
06-25 11:39:01.626 16546 16546 E ActivityThread: 	at im.status.ethereum.keycard.SmartCard.start(SmartCard.java:84)
06-25 11:39:01.626 16546 16546 E ActivityThread: 	at im.status.ethereum.keycard.RNStatusKeycardModule.onHostResume(RNStatusKeycardModule.java:47)
06-25 11:39:01.626 16546 16546 E ActivityThread: 	at com.facebook.react.bridge.ReactContext.onHostResume(ReactContext.java:221)
06-25 11:39:01.626 16546 16546 E ActivityThread: 	at com.facebook.react.ReactInstanceManager.moveToResumedLifecycleState(ReactInstanceManager.java:695)
06-25 11:39:01.626 16546 16546 E ActivityThread: 	at com.facebook.react.ReactInstanceManager.onHostResume(ReactInstanceManager.java:616)
06-25 11:39:01.626 16546 16546 E ActivityThread: 	at com.facebook.react.ReactInstanceManager.onHostResume(ReactInstanceManager.java:573)
06-25 11:39:01.626 16546 16546 E ActivityThread: 	at com.facebook.react.ReactDelegate.onHostResume(ReactDelegate.java:53)
06-25 11:39:01.626 16546 16546 E ActivityThread: 	at com.facebook.react.ReactActivityDelegate.onResume(ReactActivityDelegate.java:99)
06-25 11:39:01.626 16546 16546 E ActivityThread: 	at com.facebook.react.ReactActivity.onResume(ReactActivity.java:57)
06-25 11:39:01.626 16546 16546 E ActivityThread: 	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1454)
06-25 11:39:01.626 16546 16546 E ActivityThread: 	at android.app.Activity.performResume(Activity.java:8051)
06-25 11:39:01.626 16546 16546 E ActivityThread: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4236)
06-25 11:39:01.626 16546 16546 E ActivityThread: 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4278)
06-25 11:39:01.626 16546 16546 E ActivityThread: 	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
06-25 11:39:01.626 16546 16546 E ActivityThread: 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
06-25 11:39:01.626 16546 16546 E ActivityThread: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
06-25 11:39:01.626 16546 16546 E ActivityThread: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2040)
06-25 11:39:01.626 16546 16546 E ActivityThread: 	at android.os.Handler.dispatchMessage(Handler.java:107)
06-25 11:39:01.626 16546 16546 E ActivityThread: 	at android.os.Looper.loop(Looper.java:224)
06-25 11:39:01.626 16546 16546 E ActivityThread: 	at android.app.ActivityThread.main(ActivityThread.java:7520)
06-25 11:39:01.626 16546 16546 E ActivityThread: 	at java.lang.reflect.Method.invoke(Native Method)
06-25 11:39:01.626 16546 16546 E ActivityThread: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
06-25 11:39:01.626 16546 16546 E ActivityThread: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
06-25 11:39:01.656 16546 16580 W cr_ChildProcessConn: onServiceDisconnected (crash or killed by oom): pid=0 bindings:WM  state:2 counts:0,0,1,0,
06-25 11:39:03.954 16546 16636 D ReactNativeJS: DEBUG [status-im.utils.handlers:44] - Handling re-frame event:  :mailserver/check-connection-timeout
06-25 11:39:13.953 16546 16636 D ReactNativeJS: DEBUG [status-im.utils.handlers:44] - Handling re-frame event:  :mailserver/check-connection-timeout
```

**Comment by churik** [comment]
It is also reproducible after relogin into account in 1.4.1
Not reproducible on nightly 25/06/2020

**Comment by churik** [comment]
IMO can be related to https://github.com/PascalPrecht/status-react/commit/a7b15565cafab7ff70798a3725294070e3554521 
(but not sure) and to the fact, that it is INFO by default in nightly builds and disabled in release builds

**Comment by 0x-r4bbit** [comment]
@churik very likely that it's related to my commit. I'll take a look at it tomorrow morning first thing!

**Comment by flexsurfer** [comment]
fixed
