### ISSUE TITLE
Crash java.lang.NullPointerException on login on keycard multiaccount with enabled fingerprint

### ISSUE THREAD

**Issue by churik** [status-im/status-react#10976]
# Bug Report

## Problem
Login with enabled fingerprint is not possible with keycard multiaccount

#### Expected behavior
Login

#### Actual behavior
Error  java.lang.NullPointerException"

### Reproduction

[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Create multiaccount with keycard
- Enable fingerprint
- Login
- Reopen app
- Touch sensor on phone

### Additional Information

- Status version: nightly 21/07/2020
- Operating System: Android

#### Logs

[comment]: # (if on Android please replicate bug whilst running adb logcat)

```
--------- beginning of crash
07-21 11:37:41.609 15926 16008 E AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
07-21 11:37:41.609 15926 16008 E AndroidRuntime: Process: im.status.ethereum, PID: 15926
07-21 11:37:41.609 15926 16008 E AndroidRuntime: java.lang.NullPointerException
07-21 11:37:41.609 15926 16008 E AndroidRuntime: 	at java.io.File.<init>(File.java:323)
07-21 11:37:41.609 15926 16008 E AndroidRuntime: 	at im.status.ethereum.module.StatusModule.pathCombine(StatusModule.java:245)
07-21 11:37:41.609 15926 16008 E AndroidRuntime: 	at im.status.ethereum.module.StatusModule.initKeystore(StatusModule.java:446)
07-21 11:37:41.609 15926 16008 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-21 11:37:41.609 15926 16008 E AndroidRuntime: 	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
07-21 11:37:41.609 15926 16008 E AndroidRuntime: 	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
07-21 11:37:41.609 15926 16008 E AndroidRuntime: 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
07-21 11:37:41.609 15926 16008 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:883)
07-21 11:37:41.609 15926 16008 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:100)
07-21 11:37:41.609 15926 16008 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
07-21 11:37:41.609 15926 16008 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:224)
07-21 11:37:41.609 15926 16008 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
07-21 11:37:41.609 15926 16008 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:919)
07-21 11:37:41.622  1630  2547 D WindowManager: Input focus has changed to Window{60bce33 u0 im.status.ethereum/im.status.ethereum.MainActivity}
```
Full logcat:  [logcat1.log](https://github.com/status-im/status-react/files/4952600/logcat1.log)

**Comment by churik** [comment]
cc @guylouis  @hesterbruikman @rasom
