### ISSUE TITLE
Crash after getting app back from background after upgrade from 1.8 to 1.9 

### ISSUE THREAD

**Issue by churik** [status-im/status-react#11441]
# Bug Report

## Problem
After getting back from the background app is crashed.
Reopening app after a crash doesn't help to avoid issue.
After several manual relogins issue is not appeared anymore

#### Expected behavior
no crash

#### Actual behavior
app is crashed

### Reproduction

[comment]: # (Describe how we can replicate the bug step by step.)

- Install 1.8
- Enable biometric authentication
- Upgrade to 1.9
- Login with face-id
- Put app to background and back

### Additional Information
- Status version: upgraded from 1.8 -> 1.9 build 1
- Operating System: Android, iOS

#### Logs

[status_logs.zip](https://github.com/status-im/status-react/files/5553398/status_logs.zip)

**Comment by churik** [comment]
```
--------- beginning of crash
11-17 14:04:25.071 21745 21844 F libc    : Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 21844 (mqt_native_modu), pid 21745 (status.ethereum)
11-17 14:04:25.083   920  1536 D BufferQueueLayer: Launcher new frame Arrived
11-17 14:04:25.083  2903  2903 D NavigationBarTransitions: applyDarkIntensity 0.64377797
11-17 14:04:25.098  2903  2903 D NavigationBarTransitions: applyDarkIntensity 0.8394938
11-17 14:04:25.099   920   996 D BufferQueueLayer: Launcher new frame Arrived
11-17 14:04:25.115   920   998 D BufferQueueLayer: Launcher new frame Arrived
11-17 14:04:25.115  2903  2903 D NavigationBarTransitions: applyDarkIntensity 0.9378363
11-17 14:04:25.130   920   998 D BufferQueueLayer: Launcher new frame Arrived
11-17 14:04:25.132  2903  2903 D NavigationBarTransitions: applyDarkIntensity 0.9826073
11-17 14:04:25.132  2903  2903 D NavBarTintController: onSampleCollected 0.9764706
11-17 14:04:25.146   920   998 D BufferQueueLayer: Launcher new frame Arrived
11-17 14:04:25.148  2903  2903 D NavigationBarTransitions: applyDarkIntensity 0.9990056
11-17 14:04:25.164   920   998 D BufferQueueLayer: Launcher new frame Arrived
11-17 14:04:25.165  2903  2903 D NavigationBarTransitions: applyDarkIntensity 1.0
11-17 14:04:25.180   920   996 D BufferQueueLayer: Launcher new frame Arrived
11-17 14:04:25.198   920   996 D BufferQueueLayer: Launcher new frame Arrived
11-17 14:04:25.215   920   998 D BufferQueueLayer: Launcher new frame Arrived
11-17 14:04:25.227   785  1561 I SDM     : HWCDisplayBuiltIn::parseOutputBuffer: w 1080 h 2340 stride 1088 size 10186752 Bpp 4
11-17 14:04:25.228   785  1561 I SDM     : HWCDisplayBuiltIn::parseBrightness: set DBV 588.000000 brightness:1178
11-17 14:04:25.229   785  1561 D SDM     : HWCDisplayBuiltIn::parseBrightness: out partial brightness:1.500000, (r, g, b): { 11.000000, 16.000000, 49.000000 }
11-17 14:04:25.229   785  1561 I libsensor-C2SNotifier: NotifySensorThread will begin for SendClientRGB !
11-17 14:04:25.229   785  1561 I libsensor-C2SNotifier: SendMsgThread has begin for SendClientRGB !
11-17 14:04:25.229   785 22267 I libsensor-C2SNotifier: SendMsgThread threadLoop starting !
11-17 14:04:25.229   785 22267 I libsensor-C2SNotifier: Sensor: notify type: 5, value: -5
11-17 14:04:25.230   785 22267 I libsensor-C2SNotifier: SendMsgThread threadLoop correct and msg have been send !
11-17 14:04:25.231   920  1536 D BufferQueueLayer: Launcher new frame Arrived
11-17 14:04:25.247   920   998 D BufferQueueLayer: Launcher new frame Arrived
11-17 14:04:25.250  2903  2903 D NavBarTintController: onSampleCollected 0.9764706
11-17 14:04:25.264   920   996 D BufferQueueLayer: Launcher new frame Arrived
11-17 14:04:25.281   920   996 D BufferQueueLayer: Launcher new frame Arrived
11-17 14:04:25.297   920   998 D BufferQueueLayer: Launcher new frame Arrived
11-17 14:04:25.315   920  1536 D BufferQueueLayer: Launcher new frame Arrived
11-17 14:04:25.328 22266 22266 I crash_dump64: obtaining output fd from tombstoned, type: kDebuggerdTombstone
11-17 14:04:25.330   920  1536 D BufferQueueLayer: Launcher new frame Arrived
11-17 14:04:25.335  1279  1279 I /system/bin/tombstoned: received crash request for pid 21844
11-17 14:04:25.339 22266 22266 I crash_dump64: performing dump of process 21745 (target tid = 21844)
11-17 14:04:25.346   920  1536 D BufferQueueLayer: Launcher new frame Arrived
11-17 14:04:25.348  2903  2903 D NavBarTintController: onSampleCollected 0.9764706
11-17 14:04:25.357 22266 22266 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
11-17 14:04:25.357 22266 22266 F DEBUG   : Build fingerprint: 'Xiaomi/raphael_eea/raphael:10/QKQ1.190825.002/V12.0.3.0.QFKEUXM:user/release-keys'
11-17 14:04:25.357 22266 22266 F DEBUG   : Revision: '0'
11-17 14:04:25.357 22266 22266 F DEBUG   : ABI: 'arm64'
11-17 14:04:25.358 22266 22266 F DEBUG   : Timestamp: 2020-11-17 14:04:25+0100
11-17 14:04:25.358 22266 22266 F DEBUG   : pid: 21745, tid: 21844, name: mqt_native_modu  >>> im.status.ethereum <<<
11-17 14:04:25.358 22266 22266 F DEBUG   : uid: 10977
11-17 14:04:25.358 22266 22266 F DEBUG   : signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
11-17 14:04:25.358 22266 22266 F DEBUG   :     x0  0000000000000000  x1  0000000000005554  x2  0000000000000006  x3  0000000000000008
11-17 14:04:25.358 22266 22266 F DEBUG   :     x4  0000000000000001  x5  0000000000000000  x6  000000000000000a  x7  0000000000000002
11-17 14:04:25.358 22266 22266 F DEBUG   :     x8  0000000000000083  x9  0000000000000005  x10 0000000000000000  x11 0000007dde73b158
11-17 14:04:25.358 22266 22266 F DEBUG   :     x12 0000000000000000  x13 0000000000000000  x14 0000000000000000  x15 0000000000000001
11-17 14:04:25.358 22266 22266 F DEBUG   :     x16 0000007ddd0f1c5b  x17 0000007ddd0f1c58  x18 0000007de2a3e000  x19 00000000000054f1
11-17 14:04:25.358 22266 22266 F DEBUG   :     x20 0000007de2cf01f0  x21 0000004000088a80  x22 000000000000005a  x23 0000000000000014
11-17 14:04:25.359 22266 22266 F DEBUG   :     x24 000000000000002b  x25 0000007de2cf3020  x26 0000000000000000  x27 0000000000000010
11-17 14:04:25.359 22266 22266 F DEBUG   :     x28 00000040004c2f00  x29 0000007de2cf0ae0
11-17 14:04:25.359 22266 22266 F DEBUG   :     sp  00000040011cdbc0  lr  0000007ddd0d7f38  pc  0000007ddd0f29e0
11-17 14:04:25.359 22266 22266 F DEBUG   : 
11-17 14:04:25.359 22266 22266 F DEBUG   : backtrace:
11-17 14:04:25.359 22266 22266 F DEBUG   :       #00 pc 000000000082e9e0  /data/app/im.status.ethereum-Tg3qi77_cxlsXetYArMc3g==/lib/arm64/libgojni.so
```

Full logcat: 
[logcat-cr.log](https://github.com/status-im/status-react/files/5553603/logcat-cr.log)

**Comment by flexsurfer** [comment]
```
11-17 14:04:23.550 30932 30932 E Launcher: changeViewByFsGestureState,  view=ShortcutMenuLayer,  alpha=0.99875325,  scale=0.9997506
11-17 14:04:23.551 21745     0 E Go      : panic: runtime error: invalid memory address or nil pointer dereference
11-17 14:04:23.551 21745 22019 E GoLog   : panic: runtime error: invalid memory address or nil pointer dereference
11-17 14:04:23.551 21745     0 E Go      : [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x7dddc2e704]
11-17 14:04:23.551 21745     0 E Go      : 
11-17 14:04:23.551 21745     0 E Go      : goroutine 389 [running, locked to thread]:
11-17 14:04:23.551 21745     0 E Go      : github.com/status-im/status-go/services/local-notifications.(*Service).IsWatchingWallet(...)
11-17 14:04:23.551 21745     0 E Go      : 	/build/go/src/github.com/status-im/status-go/services/local-notifications/core.go:258
11-17 14:04:23.551 21745     0 E Go      : github.com/status-im/status-go/api.(*GethStatusBackend).AppStateChange(0x40000e2990, 0x40022403f0, 0xa)
11-17 14:04:23.551 21745     0 E Go      : 	/build/go/src/github.com/status-im/status-go/api/geth_backend.go:915 +0x39c
11-17 14:04:23.551 21745     0 E Go      : github.com/status-im/status-go/mobile.AppStateChange(...)
11-17 14:04:23.552 21745     0 E Go      : 	/build/go/src/github.com/status-im/status-go/mobile/status.go:511
11-17 14:04:23.552 21745     0 E Go      : main.proxystatusgo__AppStateChange(0x7e5af898e0, 0xa)
11-17 14:04:23.552 21745     0 E Go      : 	/build/gomobile-work/src/gobind/go_statusgomain.go:685 +0x4c
11-17 14:04:23.552 21745     0 E Go      : main._cgoexpwrap_05cf7656ecec_proxystatusgo__AppStateChange(0x7e5af898e0, 0xa)
11-17 14:04:23.552 21745     0 E Go      : 	_cgo_gotypes.go:1439 +0x28
```
