### ISSUE TITLE
java.lang.numberFormatException when receive TX in 1-1 chat. Can't proceed use Status after, - until Force Stop

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#11836]
# Bug Report

## Problem

`java.lang.numberFormatException for input string ""` error appears when received transaction in 1-1 chat.
After tap on 'Exit' - can't proceed to use Status. It's frozen. When re-opening Status was stuck on logo screen (apparently it's enabled Notifications settings which plays role here of app stuck on  Status logo view because we keep running Status when Notification ON)

#### Expected behavior

No error appears

#### Actual behavior

<img width="191" alt="Screenshot 2021-03-04 at 14 25 37" src="https://user-images.githubusercontent.com/8749671/109965163-40270f00-7cf7-11eb-9f35-8cf0c91d4cd7.png">

### Reproduction

- Open Status on Device1 and Device2
- Device1 sends to Device2 'Request transaction' message in 1-1 chat
- Device2 signs with PIN and sends transaction 
- Device2 goes offline (Airplane mode)
- After Device1 receives transaction, - Device2 returns back online
- Device2 receives 'Confirmed' status in 1-1 chat transaction but error also appears (see **Actual result** above) 

### Additional Information

- Status version: `Release 1.12`/ develop
- Operating System: Android

#### Logs

Full logcat log (from emulator): 
[logcat.log](https://github.com/status-im/status-react/files/6083738/logcat.20.log)

```

--------- beginning of crash
03-03 07:14:40.588  5754  5850 E AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
03-03 07:14:40.588  5754  5850 E AndroidRuntime: Process: im.status.ethereum, PID: 5754
03-03 07:14:40.588  5754  5850 E AndroidRuntime: java.lang.NumberFormatException: For input string: ""
03-03 07:14:40.588  5754  5850 E AndroidRuntime: 	at java.lang.Integer.parseInt(Integer.java:627)
03-03 07:14:40.588  5754  5850 E AndroidRuntime: 	at java.lang.Integer.parseInt(Integer.java:650)
03-03 07:14:40.588  5754  5850 E AndroidRuntime: 	at im.status.ethereum.pushnotifications.NewMessageSignalHandler.upsertChat(NewMessageSignalHandler.java:268)
03-03 07:14:40.588  5754  5850 E AndroidRuntime: 	at im.status.ethereum.pushnotifications.NewMessageSignalHandler.handleNewMessage(NewMessageSignalHandler.java:241)
03-03 07:14:40.588  5754  5850 E AndroidRuntime: 	at im.status.ethereum.pushnotifications.PushNotification.presentLocalNotification(PushNotification.java:116)
03-03 07:14:40.588  5754  5850 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-03 07:14:40.588  5754  5850 E AndroidRuntime: 	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
03-03 07:14:40.588  5754  5850 E AndroidRuntime: 	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
03-03 07:14:40.588  5754  5850 E AndroidRuntime: 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
03-03 07:14:40.588  5754  5850 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:883)
03-03 07:14:40.588  5754  5850 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:100)
03-03 07:14:40.588  5754  5850 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
03-03 07:14:40.588  5754  5850 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
03-03 07:14:40.588  5754  5850 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
03-03 07:14:40.588  5754  5850 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:919)
03-03 07:14:40.612  5754  6759 D StatusModule: Signal event
03-03 07:14:40.615  1749  1825 D gralloc_ranchu: gralloc_alloc: Creating ashmem region of size 1736704
03-03 07:14:40.619  1749  1825 I chatty  : uid=1000(system) HwBinder:1749_3 identical 1 line
03-03 07:14:40.622  1749  1825 D gralloc_ranchu: gralloc_alloc: Creating ashmem region of size 1736704
03-03 07:14:40.629  5754  5833 D EGL_emulation: eglMakeCurrent: 0xc00b74a0: ver 2 0 (tinfo 0xc00dc3a0)
```

**Comment by churik** [comment]
added to 1.12 as IMO it is really dreadful issue
