### ISSUE TITLE
Research creating own F-Droid repository

### ISSUE THREAD

**Issue by jakubgs** [status-im/status-react#12400]
Being dependent on F-Droid own submission and build process makes it hard to sync releases. It is possible to maintain your own F-Droid repository which would make use more independent in terms of submitting new versions:

https://f-droid.org/en/docs/Setup_an_F-Droid_App_Repo/

List of other known repositories:
https://forum.f-droid.org/t/known-repositories/721
https://f-droid.org/wiki/page/Known_Repositories

**Comment by jakubgs** [comment]
Based on this repository: https://www.cgeo.org/development#f-droid-repository
I thought we could use the domain `fdroid.status.im` and have different branches under sub-paths, like they do:

>#### Repositories
>URL:
>
>* https://fdroid.cgeo.org for mainline
>* https://fdroid.cgeo.org/nightly for nightly builds
>* https://fdroid.cgeo.org/legacy for legacy builds
>
>Our repository fingerprint is:
>
>370BB4D550C391D5DCCB6C81FD82FDA4892964764E085A09B7E075E9BAD5ED98

So we could do something like:

* https://fdroid.status.im/ - Releases
* https://fdroid.status.im/nightly - Nightlies

And while that would make for a neat URL, the documentation states that:

>While __you can serve the repository at an arbitrary URL__, it is customary to make it available at an URL ending with `/fdroid/repo/`. A good reason to actually do this is that the __F-Droid client sets up an intent filter and registers itself for such URLs__. As a result, a user that has the F-Droid app installed and opens such a well-formed URL will have their device open F-Droid and guide them directly to adding the repository to it.

**Comment by jakubgs** [comment]
Although I did test this with some other repos, like https://microg.org/fdroid/repo/ and it doesn't seem to work. F-Droid doesn't open.

**Comment by jakubgs** [comment]
I looked in the [`fdroidclient`](https://gitlab.com/fdroid/fdroidclient/-/issues) issues and I couldn't find anything about intent filter.

I created my own issue to see if this is a known issue: https://gitlab.com/fdroid/fdroidclient/-/issues/2251

**Comment by jakubgs** [comment]
When I try to run `fdroid update` on NixOS I get this:
```
 > fdroid update --verbose             
DEBUG: Reading 'config.py'
DEBUG: Processing StatusIm-Mobile-v1.15.0-5e46db.apk
DEBUG: Using androguard from "/etc/profiles/per-user/sochan/lib/python3.8/site-packages/androguard/__init__.py"
Traceback (most recent call last):
  File "/nix/store/bkpkssfx6bpwdynsifygq86mda3z0rnw-fdroidserver-1.1.9/lib/python3.8/site-packages/fdroidserver/update.py", line 1216, in scan_apk_androguard
    from androguard.core.bytecodes.apk import APK
  File "/etc/profiles/per-user/sochan/lib/python3.8/site-packages/androguard/core/bytecodes/apk.py", line 9, in <module>
    from androguard.core.bytecodes.axml import ARSCParser, AXMLPrinter, ARSCResTableConfig, AXMLParser, format_value, START_TAG, END_TAG, TEXT, END_DOCUMENT
  File "/etc/profiles/per-user/sochan/lib/python3.8/site-packages/androguard/core/bytecodes/axml/__init__.py", line 17, in <module>
    from lxml import etree
ImportError: /nix/store/q53f5birhik4dxg3q3r2g5f324n7r5mc-glibc-2.31-74/lib/libc.so.6: version `GLIBC_2.32' not found (required by /nix/store/gk42f59363p82rg2wv2mfy71jn5w4q4c-glibc-2.32-48/lib/librt.so.1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nix/store/bkpkssfx6bpwdynsifygq86mda3z0rnw-fdroidserver-1.1.9/bin/.fdroid-wrapped", line 171, in <module>
    main()
  File "/nix/store/bkpkssfx6bpwdynsifygq86mda3z0rnw-fdroidserver-1.1.9/bin/.fdroid-wrapped", line 147, in main
    mod.main()
  File "/nix/store/bkpkssfx6bpwdynsifygq86mda3z0rnw-fdroidserver-1.1.9/lib/python3.8/site-packages/fdroidserver/update.py", line 1968, in main
    apks, cachechanged = process_apks(apkcache, repodirs[0], knownapks, options.use_date_from_apk)
  File "/nix/store/bkpkssfx6bpwdynsifygq86mda3z0rnw-fdroidserver-1.1.9/lib/python3.8/site-packages/fdroidserver/update.py", line 1495, in process_apks
    (skip, apk, cachethis) = process_apk(apkcache, apkfilename, repodir, knownapks,
  File "/nix/store/bkpkssfx6bpwdynsifygq86mda3z0rnw-fdroidserver-1.1.9/lib/python3.8/site-packages/fdroidserver/update.py", line 1369, in process_apk
    apk = scan_apk(apkfile)
  File "/nix/store/bkpkssfx6bpwdynsifygq86mda3z0rnw-fdroidserver-1.1.9/lib/python3.8/site-packages/fdroidserver/update.py", line 1055, in scan_apk
    scan_apk_androguard(apk, apk_file)
  File "/nix/store/bkpkssfx6bpwdynsifygq86mda3z0rnw-fdroidserver-1.1.9/lib/python3.8/site-packages/fdroidserver/update.py", line 1234, in scan_apk_androguard
    raise FDroidException("androguard library is not installed and aapt not present")
fdroidserver.exception.FDroidException: androguard library is not installed and aapt not present
```

**Comment by jakubgs** [comment]
Thanks to tests by @qoqobolo it turns out that F-Droid repo deep linking(intent filter) works in other applications than browsers, for example in chat applications like Discord. I confirmed this myself and it does indeed work.

For this reason it would indeed make most sense to put the repo under https://status.im/frdroid/repo.

**Comment by jakubgs** [comment]
I tried making a custom shell with Android SDK in it to do this:
```nix
{ pkgs ? import <nixpkgs> { config.android_sdk.accept_license = true; } }:

let
  androidEnv = pkgs.androidenv.composeAndroidPackages {
    toolsVersion = "26.1.1";
    platformToolsVersion = "31.0.2";
    buildToolsVersions = [ "30.0.3" ];
    platformVersions = [ "29" ];
    cmakeVersions = [ "3.18.1" ];
    ndkVersion = "22.1.7171670";
    includeNDK = true;
    includeExtras = [
      "extras;android;m2repository"
      "extras;google;m2repository"
    ];
  };
in pkgs.mkShell {
  name = "status-fdroidata";

  buildInputs = with pkgs; [ python38 python38Packages.androguard ];

  ANDROID_HOME = "${androidEnv.androidsdk}";
}
```
But I'm getting the same `glibc` error:
```
ImportError: /nix/store/q53f5birhik4dxg3q3r2g5f324n7r5mc-glibc-2.31-74/lib/libc.so.6: version `GLIBC_2.32' not found (required by /nix/store/gk42f59363p82rg2wv2mfy71jn5w4q4c-glibc-2.32-48/lib/librt.so.1)
```
I think I will try a container of a VM to compare with a non-Nix system.

**Comment by jakubgs** [comment]
Okay, with this shell setup I managed to get it working:
```nix
{ pkgs ? import <nixpkgs> { config.android_sdk.accept_license = true; } }:

let
  androidEnv = pkgs.androidenv.composeAndroidPackages {
    toolsVersion = "26.1.1";
    platformToolsVersion = "31.0.2";
    buildToolsVersions = [ "30.0.3" ];
    platformVersions = [ "29" ];
    cmakeVersions = [ "3.18.1" ];
    ndkVersion = "22.1.7171670";
  };
  myPython38 = pkgs.python38.withPackages (
    python-packages: with (pkgs.python38Packages); [ androguard ]
  );
in pkgs.mkShell {
  name = "status-fdroidata";

  buildInputs = with pkgs; [ fdroidserver myPython38 ];

  ANDROID_HOME = "${androidEnv.androidsdk}";
}
```
```
[nix-shell:~/work/status-fdroiddata]$ fdroid update -c
INFO: Generated skeleton metadata for im.status.ethereum
INFO: Creating signed index with this key (SHA256):
INFO: D4 AD DB D7 01 61 6D 0E 6B F7 46 64 E2 83 E6 DD 98 35 13 F7 C0 9C 2A 75 B3 B8 27 77 17 6E 6B 97
INFO: Finished
```

**Comment by jakubgs** [comment]
This generates and `repo/index.xml` which contains the app metadata:
```
 > cat repo/index.xml | xmllint --format -
```
```xml
<?xml version="1.0" encoding="utf-8"?>
<fdroid>
  <repo icon="fdroid-icon.png" name="Status.im F-Droid Repo" pubkey="3082...6981" timestamp="1629381541" url="https://status.im/fdroid/repo" version="21">
    <description>This is a repository of Status application releases for Android.

Status is a Cryptocurrency wallet, Private messenger, and Ethereum DApp Browser all in one </description>
  </repo>
  <application id="im.status.ethereum">
    <id>im.status.ethereum</id>
    <added>2021-08-19</added>
    <lastupdated>2021-08-19</lastupdated>
    <name>Status</name>
    <summary/>
    <icon>im.status.ethereum.2021071411.png</icon>
    <desc>&lt;p&gt;No description available&lt;/p&gt;</desc>
    <license>Unknown</license>
    <categories>status-fdroiddata</categories>
    <category>status-fdroiddata</category>
    <web/>
    <source/>
    <tracker/>
    <marketversion/>
    <marketvercode>2147483647</marketvercode>
    <package>
      <version>1.15.0</version>
      <versioncode>2021071411</versioncode>
      <apkname>StatusIm-Mobile-v1.15.0-5e46db.apk</apkname>
      <hash type="sha256">3c1f363e366d8b8178aad804f87a792ef5ce3200c6985ef04930daf51fcfe508</hash>
      <size>90386188</size>
      <sdkver>23</sdkver>
      <targetSdkVersion>29</targetSdkVersion>
      <added>2021-08-19</added>
      <sig>dd412f369ff54ab1d9fa79c19865ba6d</sig>
      <permissions>ACCESS_FINE_LOCATION,ACCESS_NETWORK_STATE,ACCESS_WIFI_STATE,CAMERA,FOREGROUND_SERVICE,INTERNET,NFC,READ_EXTERNAL_STORAGE,RECEIVE_BOOT_COMPLETED,RECORD_AUDIO,USE_FINGERPRINT,VIBRATE,WAKE_LOCK,WRITE_EXTERNAL_STORAGE,com.android.vending.BILLING,com.google.android.c2dm.permission.RECEIVE,com.google.android.finsky.permission.BIND_GET_INSTALL_REFERRER_SERVICE</permissions>
      <nativecode>arm64-v8a,armeabi-v7a,x86,x86_64</nativecode>
      <features>android.hardware.camera,android.hardware.camera.autofocus</features>
    </package>
  </application>
</fdroid>
```

**Comment by jakubgs** [comment]
I am seeing some warnings when adding the APKs, but they don't seem to matter:
```
[nix-shell:~/work/status-fdroiddata]$ fdroid update -c
WARNING: Requested API level 29 is larger than maximum we have, returning API level 28 instead.
WARNING: Using Java's jarsigner, not recommended for verifying APKs! Use apksigner
WARNING: Requested API level 29 is larger than maximum we have, returning API level 28 instead.
WARNING: Requested API level 29 is larger than maximum we have, returning API level 28 instead.
WARNING: Requested API level 29 is larger than maximum we have, returning API level 28 instead.
```
The APKs get imported without issues:
```
 > cat repo/index.xml | xmllint --format - | grep apkname
      <apkname>StatusIm-Mobile-v1.15.0-5e46db.apk</apkname>
      <apkname>StatusIm-Mobile-v1.14.0-d1a3a2.apk</apkname>
      <apkname>StatusIm-Mobile-v1.13.0-896b583.apk</apkname>
      <apkname>StatusIm-Mobile-v1.12.2-4e8bb68.apk</apkname>
      <apkname>StatusIm-Mobile-v1.12.1-4e8bb68.apk</apkname>
      <apkname>StatusIm-Mobile-v1.11.1-d41532a.apk</apkname>
      <apkname>StatusIm-Mobile-v1.10.1-09f95dc.apk</apkname>
      <apkname>StatusIm-Mobile-v1.10.0-d8be02.apk</apkname>
      <apkname>StatusIm-Mobile-v1.9.0-60511dc.apk</apkname>
      <apkname>StatusIm-Mobile-v1.8.0-579e079.apk</apkname>
      <apkname>StatusIm-Mobile-v1.7.2-5edbd0f.apk</apkname>
      <apkname>StatusIm-Mobile-v1.7.1-2d4638.apk</apkname>
      <apkname>StatusIm-Mobile-v1.7.0-e40664.apk</apkname>
      <apkname>StatusIm-Mobile-v1.6.1-877acff.apk</apkname>
      <apkname>StatusIm-Mobile-v1.6.0-21cac9.apk</apkname>
      <apkname>StatusIm-Mobile-v1.5.0-a1f59c2.apk</apkname>
      <apkname>StatusIm-Mobile-v1.4.1-2c882e3.apk</apkname>
      <apkname>StatusIm-Mobile-v1.4.0-12fce4.apk</apkname>
      <apkname>StatusIm-Mobile-v1.3.1-ff6cb2.apk</apkname>
      <apkname>StatusIm-Mobile-v1.3.0-00d63ed.apk</apkname>
      <apkname>StatusIm-Mobile-v1.2.1-464ad4d.apk</apkname>
      <apkname>StatusIm-Mobile-v1.2.0-b76fa53.apk</apkname>
      <apkname>StatusIm-Mobile-v1.1.0-7b64a99.apk</apkname>
      <apkname>StatusIm-Mobile-v1.0.2-2c47804.apk</apkname>
      <apkname>StatusIm-Mobile-v1.0.1-aa28d2.apk</apkname>
      <apkname>StatusIm-Mobile-v1.0.0-30952e1.apk</apkname>
```

**Comment by jakubgs** [comment]
If you use `--pretty` you get formatted XML. And if you add `--rename-apks` they all get renamed like this:
```
[nix-shell:~/work/status-fdroiddata]$ ls -lh repo/
total 1.9G
-rw-r--r-- 1 sochan sochan   18 Aug 19 17:33 categories.txt
drwxr-xr-x 2 sochan sochan   55 Aug 19 17:33 icons
drwxr-xr-x 2 sochan sochan   28 Aug 19 17:33 icons-120
drwxr-xr-x 2 sochan sochan   28 Aug 19 17:33 icons-160
drwxr-xr-x 2 sochan sochan   28 Aug 19 17:33 icons-240
drwxr-xr-x 2 sochan sochan   28 Aug 19 17:33 icons-320
drwxr-xr-x 2 sochan sochan   28 Aug 19 17:33 icons-480
drwxr-xr-x 2 sochan sochan   28 Aug 19 17:33 icons-640
-rw-r--r-- 1 sochan sochan  67M Aug 19 17:25 im.status.ethereum_2020020414.apk
-rw-r--r-- 1 sochan sochan  67M Aug 19 17:25 im.status.ethereum_2020021213.apk
-rw-r--r-- 1 sochan sochan  67M Aug 19 17:25 im.status.ethereum_2020022507.apk
-rw-r--r-- 1 sochan sochan  67M Aug 19 17:25 im.status.ethereum_2020031610.apk
-rw-r--r-- 1 sochan sochan  67M Aug 19 17:25 im.status.ethereum_2020040117.apk
-rw-r--r-- 1 sochan sochan  67M Aug 19 17:25 im.status.ethereum_2020040212.apk
-rw-r--r-- 1 sochan sochan  68M Aug 19 17:25 im.status.ethereum_2020042307.apk
-rw-r--r-- 1 sochan sochan  68M Aug 19 17:25 im.status.ethereum_2020050209.apk
-rw-r--r-- 1 sochan sochan  75M Aug 19 17:25 im.status.ethereum_2020060905.apk
-rw-r--r-- 1 sochan sochan  75M Aug 19 17:25 im.status.ethereum_2020070112.apk
-rw-r--r-- 1 sochan sochan  76M Aug 19 17:25 im.status.ethereum_2020081013.apk
-rw-r--r-- 1 sochan sochan  76M Aug 19 17:25 im.status.ethereum_2020082611.apk
-rw-r--r-- 1 sochan sochan  76M Aug 19 17:25 im.status.ethereum_2020090810.apk
-rw-r--r-- 1 sochan sochan  76M Aug 19 17:25 im.status.ethereum_2020092512.apk
-rw-r--r-- 1 sochan sochan  76M Aug 19 17:25 im.status.ethereum_2020100112.apk
-rw-r--r-- 1 sochan sochan  77M Aug 19 17:25 im.status.ethereum_2020100610.apk
-rw-r--r-- 1 sochan sochan  77M Aug 19 17:25 im.status.ethereum_2020101914.apk
-rw-r--r-- 1 sochan sochan  77M Aug 19 17:25 im.status.ethereum_2020112009.apk
-rw-r--r-- 1 sochan sochan  79M Aug 19 17:25 im.status.ethereum_2021011115.apk
-rw-r--r-- 1 sochan sochan  79M Aug 19 17:25 im.status.ethereum_2021011810.apk
-rw-r--r-- 1 sochan sochan  80M Aug 19 17:25 im.status.ethereum_2021021517.apk
-rw-r--r-- 1 sochan sochan  80M Aug 19 17:25 im.status.ethereum_2021031517.apk
-rw-r--r-- 1 sochan sochan  80M Aug 19 17:25 im.status.ethereum_2021032607.apk
-rw-r--r-- 1 sochan sochan  81M Aug 19 17:25 im.status.ethereum_2021042608.apk
-rw-r--r-- 1 sochan sochan  81M Aug 19 17:25 im.status.ethereum_2021060711.apk
-rw-r--r-- 1 sochan sochan  87M Aug 19 17:25 im.status.ethereum_2021071411.apk
-rw-r--r-- 1 sochan sochan 6.9K Aug 19 17:33 index.jar
-rw-r--r-- 1 sochan sochan 5.8K Aug 19 17:33 index-v1.jar
-rw-r--r-- 1 sochan sochan  59K Aug 19 17:33 index-v1.json
-rw-r--r-- 1 sochan sochan  27K Aug 19 17:33 index.xml
```

**Comment by jakubgs** [comment]
```
[nix-shell:~/work/status-fdroiddata]$ fdroid update -h
usage: fdroid update [-h] [-v] [-q] [--create-key] [-c] [--delete-unknown] [-b] [-I] [-w] [--pretty] [--clean] [--nosign] [--use-date-from-apk] [--rename-apks]
                     [--allow-disabled-algorithms] [-W {error,warn,ignore}]

optional arguments:
  -h, --help            show this help message and exit
  -v, --verbose         Spew out even more information than normal
  -q, --quiet           Restrict output to warnings and errors
  --create-key          Add a repo signing key to an unsigned repo
  -c, --create-metadata
                        Add skeleton metadata files for APKs that are missing them
  --delete-unknown      Delete APKs and/or OBBs without metadata from the repo
  -b, --buildreport     Report on build data status
  -I, --icons           Resize all the icons exceeding the max pixel size and exit
  -w, --wiki            Update the wiki
  --pretty              Produce human-readable XML/JSON for index files
  --clean               Clean update - don't uses caches, reprocess all APKs
  --nosign              When configured for signed indexes, create only unsigned indexes at this stage
  --use-date-from-apk   Use date from APK instead of current time for newly added APKs
  --rename-apks         Rename APK files that do not match package.name_123.apk
  --allow-disabled-algorithms
                        Include APKs that are signed with disabled algorithms like MD5
  -W {error,warn,ignore}
                        force metadata errors (default) to be warnings, or to be ignored.
```

**Comment by cammellos** [comment]
I will move this to a discussion, since this looks like the best place, until is actionable/we are ready to work on it
