### ISSUE TITLE
App crashes on processing new messages in 1-1 chat

### ISSUE THREAD

**Issue by churik** [status-im/status-react#12872]
# Bug Report

## Problem 
When user opens a new message in the activity center, the app crashes. And after re-login keeps crashing after couple of seconds.
**Blocks around 40% e2e**
Appeared on nightly 02.12.21, it is not presented on nightly 01.12.21
#### Expected behavior
app doesn't crash

#### Actual behavior
app crash 

### Reproduction

From e2e:
1) User A: sens User B a message
2) User B: tap on Activity center

### Additional Information

- Status version: nightly 02.12.21 
- Operating System: Android, IOS
Example of log: [test_send_non_english_message_to_newly_added_contact_on_different_networks_geth1 (3).log](https://github.com/status-im/status-react/files/7641117/test_send_non_english_message_to_newly_added_contact_on_different_networks_geth1.3.log)

**Comment by churik** [comment]
```
t=2021-12-02T07:22:01+0000 lvl=info msg="Messenger failed to process sent messages" error="Can't get raw message with id 0x56ba52983a973deac8532f1a47a1d2e89464d22af74569ac87548826f2fbacfc: sql: no rows in result set"
t=2021-12-02T07:22:02+0000 lvl=info msg="Messenger failed to process sent messages" error="Can't get raw message with id 0xbc7571af2872c93025f3b85830ee5b7d8eccbe5048c24f0e15870de098eedae1: sql: no rows in result set"
```

**Comment by churik** [comment]
More logs: 
[geth.log](https://github.com/status-im/status-react/files/7641363/geth.log)

**Comment by flexsurfer** [comment]
```
12-02 12:49:19.283 27511 27616 W ReactNativeJS: (Saw setTimeout with duration 252255ms)
12-02 12:49:20.023 27511     0 E Go      : panic: runtime error: invalid memory address or nil pointer dereference
12-02 12:49:20.023 27511     0 E Go      : [signal SIGSEGV: segmentation violation code=0x1 addr=0xc pc=0xaba47563]
12-02 12:49:20.023 27511     0 E Go      : 
12-02 12:49:20.024 27511     0 E Go      : goroutine 2193 [running]:
12-02 12:49:20.025 27511     0 E Go      : github.com/status-im/status-go/protocol/encryption.(*Protocol).HandleMessage(0x7a078588, 0x79d37218, 0x7c615ff0, 0x7bbd9d80, 0x7c21cae0, 0x20, 0x20, 0x7bbfa6f0, 0x7bd35638, 0x0)
12-02 12:49:20.025 27511     0 E Go      :      github.com/status-im/status-go/protocol/encryption/protocol.go:480 +0x6f3
12-02 12:49:20.026 27511     0 E Go      : github.com/status-im/status-go/protocol/v1.(*StatusMessage).HandleEncryption(0x7bbebb90, 0x79d37218, 0x7c615ff0, 0x7a078588, 0x7bbfa700, 0x79df33b0, 0x8)
12-02 12:49:20.026 27511     0 E Go      :      github.com/status-im/status-go/protocol/v1/status_message.go:129 +0xf5
12-02 12:49:20.027 27511     0 E Go      : github.com/status-im/status-go/protocol/common.(*MessageSender).handleEncryptionLayer(0x79f4a5c0, 0xac173d9c, 0x79d2602c, 0x7bbebb90, 0x7bbfa6c0, 0x7a42c9e8)
12-02 12:49:20.027 27511     0 E Go      :      github.com/status-im/status-go/protocol/common/message_sender.go:579 +0x152
12-02 12:49:20.028 27511     0 E Go      : github.com/status-im/status-go/protocol/common.(*MessageSender).HandleMessages(0x79f4a5c0, 0x79d3aa20, 0x1, 0x1, 0x7bbfa5d0, 0x20, 0x40, 0x0, 0x0, 0x0, ...)
12-02 12:49:20.029 27511     0 E Go      :      github.com/status-im/status-go/protocol/common/message_sender.go:528 +0x269
12-02 12:49:20.029 27511     0 E Go      : github.com/status-im/status-go/protocol.(*Messenger).handleRetrievedMessages(0x7a0a0840, 0x7c649960, 0x0, 0x0, 0xabc1ff25)
12-02 12:49:20.029 27511     0 E Go      :      github.com/status-im/status-go/protocol/messenger.go:2745 +0x4a2
12-02 12:49:20.030 27511     0 E Go      : github.com/status-im/status-go/protocol.(*Messenger).RetrieveAll(0x7a0a0840, 0x7bd37f84, 0x0, 0x0)
12-02 12:49:20.030 27511     0 E Go      :      github.com/status-im/status-go/protocol/messenger.go:2577 +0x55
12-02 12:49:20.031 27511     0 E Go      : github.com/status-im/status-go/services/ext.(*Service).retrieveMessagesLoop(0x79e626e0, 0x3b9aca00, 0x0, 0x7be412c0)
12-02 12:49:20.032 27511     0 E Go      :      github.com/status-im/status-go/services/ext/service.go:193 +0xf4
12-02 12:49:20.032 27511     0 E Go      : created by github.com/status-im/status-go/services/ext.(*Service).StartMessenger
12-02 12:49:20.032 27511     0 E Go      :      github.com/status-im/status-go/services/ext/service.go:166 +0xb7
12-02 12:49:21.156 27845 27845 E chromium: [1202/124921.155836:ERROR:elf_dynamic_array_reader.h(61)] tag not found

```

**Comment by flexsurfer** [comment]
https://github.com/status-im/status-go/pull/2412

**Comment by vitvly** [comment]
Possible fix in https://github.com/status-im/status-go/pull/2453, checking
