### ISSUE TITLE
java.lang.NullPointerExeption after opening an image in chat on virtual device in e2e test (e2e blocker)

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#15958]
Bug is reproducible only in e2e which causes bunch of tests to fail.
As for now we are not able to reproduce the bug manually on physical devices. 

Here is a video of failing test https://app.eu-central-1.saucelabs.com/tests/d75df12328874734a281134d97688381?auth=5dffcd5c97efe773772fad637e907418#220

Here is logcat from e2e run
[logcat (4).log](https://github.com/status-im/status-mobile/files/11514874/logcat.4.log)

Please, let us know if attached logcat is helpful in debugging the issue. If not - we will update e2e in order to avoid action which results in error. 

### Additional Information

- Status version: nightly 
- Operating System: Android

[comment]: # (Please, add logs/notes if necessary)

**Comment by siddarthkay** [comment]
The relevant stack trace is : 

```log
05-19 02:23:29.831  3883  3883 W GrowthKit: Failed to initialize SyncGcoreGcmTaskService
05-19 02:23:29.831  3883  3883 W GrowthKit: java.lang.NullPointerException: Unable to get 
GrowthKit Component from host app.
05-19 02:23:29.831  3883  3883 W GrowthKit: 	at com.google.android.libraries.internal.
growth.growthkit.inject.GrowthKit.get(GrowthKit.java:43)
05-19 02:23:29.831  3883  3883 W GrowthKit: 	at com.google.android.libraries.internal.
growth.growthkit.internal.jobs.impl.GrowthKitJobService.
onCreate(GrowthKitJobService.java:66)
05-19 02:23:29.831  3883  3883 W GrowthKit: 	at android.app.ActivityThread.handleCreateService
(ActivityThread.java:3953)
05-19 02:23:29.831  3883  3883 W GrowthKit: 	at android.app.ActivityThread.access$1500
(ActivityThread.java:219)
05-19 02:23:29.831  3883  3883 W GrowthKit: 	at android.app.ActivityThread$H.handleMessage
(ActivityThread.java:1875)
05-19 02:23:29.831  3883  3883 W GrowthKit: 	at android.os.Handler.dispatchMessage
(Handler.java:107)
05-19 02:23:29.831  3883  3883 W GrowthKit: 	at android.os.Looper.loop(Looper.java:214)
05-19 02:23:29.831  3883  3883 W GrowthKit: 	at android.app.ActivityThread.main
(ActivityThread.java:7356)
05-19 02:23:29.831  3883  3883 W GrowthKit: 	at java.lang.reflect.Method.invoke(Native Method)
05-19 02:23:29.831  3883  3883 W GrowthKit: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller
.run(RuntimeInit.java:492)
05-19 02:23:29.831  3883  3883 W GrowthKit: 	at com.android.internal.os.ZygoteInit.
main(ZygoteInit.java:930)

```

**Comment by cammellos** [comment]
is this still an issue @pavloburykh @VolodLytvynenko @churik ?

**Comment by pavloburykh** [comment]
> is this still an issue @pavloburykh @VolodLytvynenko @churik ?

I haven't faced it lately.

**Comment by cammellos** [comment]
closing for now then, feel free to reopen, thank you
