### ISSUE TITLE
App Crash During Key Generation

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#16983]
### Steps:
1. Start onboarding
2. Perform the key generation

### Actual result:

https://github.com/status-im/status-mobile/assets/52490791/4e6e57fc-0da6-4886-8d83-11dc1ba34b11

### Expected result:
The key generation process should complete successfully

### Logs:

[Status.log](https://github.com/status-im/status-mobile/files/12319468/Status.log)
[geth.log](https://github.com/status-im/status-mobile/files/12319469/geth.log)
[android_logcat.txt](https://github.com/status-im/status-mobile/files/12319516/android_logcat.txt)

**Comment by cammellos** [comment]
@VolodLytvynenko do you have the raw logcat? it's the one that would be most helpful in this case.
Thanks

**Comment by VolodLytvynenko** [comment]
> @VolodLytvynenko do you have the raw logcat? it's the one that would be most helpful in this case. Thanks

Yes. On the way of fetching logcat. Just a moment

**Comment by VolodLytvynenko** [comment]
> @VolodLytvynenko do you have the raw logcat? it's the one that would be most helpful in this case. Thanks

@cammellos Done [android_logcat.txt](https://github.com/status-im/status-mobile/files/12319514/android_logcat.txt)

**Comment by cammellos** [comment]
@VolodLytvynenko thank you!

@qfrank 
```
10:52:25.905  I  INFO [status-im.ethereum.subscriptions:71] - [wallet-subs] new-wallet-event event-type recent-history-fetching blockNumber nil accounts ["0x6887a998b2f050f5bc2a8bbc93261cbeff561639"]
10:52:26.065  E  panic: runtime error: invalid memory address or nil pointer dereference
10:52:26.066  E  [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x6e6ca0ee90]
10:52:26.066  E  
10:52:26.066  E  goroutine 590 [running]:
10:52:26.066  E  github.com/status-im/status-go/protocol/communities.(*Community).updateCommunityDescriptionByEvents(0x40004b36e0?)
10:52:26.066  E          github.com/status-im/status-go/protocol/communities/community_event.go:222 +0x20
10:52:26.066  E  github.com/status-im/status-go/protocol/communities.(*Manager).GetByID(0x4003bfc4e0?, {0x4003be8440?, 0x44?, 0x6e6c96169c?})
10:52:26.066  E          github.com/status-im/status-go/protocol/communities/manager.go:2975 +0x48
10:52:26.066  E  github.com/status-im/status-go/protocol/communities.(*Manager).GetStoredDescriptionForCommunities(0x6e6d1c3be0?, {0x4003bfc4e0, 0x3, 0x1?})
10:52:26.066  E          github.com/status-im/status-go/protocol/communities/manager.go:503 +0x18c
10:52:26.066  E  github.com/status-im/status-go/protocol.(*Messenger).CuratedCommunities(0x40002d1b80)
10:52:26.066  E          github.com/status-im/status-go/protocol/messenger_communities.go:518 +0x194
10:52:26.066  E  github.com/status-im/status-go/protocol.(*Messenger).startCuratedCommunitiesUpdateLoop.func1()
10:52:26.066  E          github.com/status-im/status-go/protocol/messenger_communities.go:446 +0x38
10:52:26.066  E  created by github.com/status-im/status-go/protocol.(*Messenger).startCuratedCommunitiesUpdateLoop
10:52:26.066  E          github.com/status-im/status-go/protocol/messenger_communities.go:442 +0x90
10:52:26.074  I  port0

```
