### ISSUE TITLE
App may crash on logout

### ISSUE THREAD

**Issue by churik** [status-im/status-react#17115]
# Bug Report

## Problem 
Caught by e2e.
Reproduced rather rarely, but on both IOS/Android from time to time (however not sure that the error itself is the same) 

#### Expected behavior

no crash 

#### Actual behavior

Video in tests: https://app.eu-central-1.saucelabs.com/tests/948ebce8aad2400e9dfcbfdbdd5f9e39?auth=153cd20383ba9739023bc91e5903fab2#207
From 07:43:

https://github.com/status-im/status-mobile/assets/4557972/11cd02d5-a033-4e87-9f2c-bf4de0a7ff9c

### Reproduction

1. Open profile
2. Logout

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS
- Logs: [logcat (17).log](https://github.com/status-im/status-mobile/files/12440492/logcat.17.log)

[comment]: # (Please, add logs/notes if necessary)

**Comment by cammellos** [comment]
```
08-23 12:16:12.464  6676  6774 I appium  : AppiumResponse: {"sessionId":"95d87928-17d7-4f5a-b24d-c15e03fe480f","value":{"error":"no such element","message":"An element could not be located on the page using the given search parameters","stacktrace":"io.appium.uiautomator2.common.exceptions.ElementNotFoundException: An element could not be located on the pag…
08-23 12:16:12.610  8216     0 E Go      : panic: send on closed channel
08-23 12:16:12.610  8216     0 E Go      : 
08-23 12:16:12.610  8216     0 E Go      : goroutine 6449 [running]:
08-23 12:16:12.610  8216     0 E Go      : github.com/status-im/status-go/vendor/github.com/waku-org/go-waku/waku/v2/discv5.(*DiscoveryV5).peerLoop.func2(0x87b9a070, {{0x844d5dd0, 0x27}, {0x877e1450, 0x2, 0x2}})
08-23 12:16:12.610  8216     0 E Go      : 	github.com/status-im/status-go/vendor/github.com/waku-org/go-waku/waku/v2/discv5/discover.go:418 +0xde
08-23 12:16:12.610  8216     0 E Go      : github.com/status-im/status-go/vendor/github.com/waku-org/go-waku/waku/v2/discv5.(*DiscoveryV5).Iterate(0x8449c680, {0xb74a9540, 0x8447f920}, {0xb74a6a88, 0x877e10c0}, 0x84059eec)
08-23 12:16:12.610  8216     0 E Go      : 	github.com/status-im/status-go/vendor/github.com/waku-org/go-waku/waku/v2/discv5/discover.go:358 +0x55f
08-23 12:16:12.610  8216     0 E Go      : github.com/status-im/status-go/vendor/github.com/waku-org/go-waku/waku/v2/discv5.(*DiscoveryV5).peerLoop(0x8449c680, {0xb74a9540, 0x8447f920})
08-23 12:16:12.610  8216     0 E Go      : 	github.com/status-im/status-go/vendor/github.com/waku-org/go-waku/waku/v2/discv5/discover.go:411 +0x371
08-23 12:16:12.610  8216     0 E Go      : github.com/status-im/status-go/vendor/github.com/waku-org/go-waku/waku/v2/discv5.(*DiscoveryV5).runDiscoveryV5Loop(0x8449c680, {0xb74a9540, 0x8447f920})
08-23 12:16:12.610  8216     0 E Go      : 	github.com/status-im/status-go/vendor/github.com/waku-org/go-waku/waku/v2/discv5/discover.go:434 +0x53
08-23 12:16:12.611  8216     0 E Go      : github.com/status-im/status-go/vendor/github.com/waku-org/go-waku/waku/v2/discv5.(*DiscoveryV5).Start.func1()
08-23 12:16:12.611  8216     0 E Go      : 	github.com/status-im/status-go/vendor/github.com/waku-org/go-waku/waku/v2/discv5/discover.go:212 +0x89
08-23 12:16:12.611  8216     0 E Go      : created by github.com/status-im/status-go/vendor/github.com/waku-org/go-waku/waku/v2/discv5.(*DiscoveryV5).Start
08-23 12:16:12.611  8216     0 E Go      : 	github.com/status-im/status-go/vendor/github.com/waku-org/go-waku/waku/v2/discv5/discover.go:210 +0x1c9
08-23 12:16:12.972  6676  6774 I appium  : channel read: POST /wd/hub/session/95d87928-17d7-4f5a-b24d-c15e03fe480f/element
08-23 12:16:12.972  6676  6774 I appium  : FindElement command
0
```
cc @richard-ramos
