### ISSUE TITLE
App can be crashed after account creation 

### ISSUE THREAD

**Issue by churik** [status-im/status-react#17114]
# Bug Report

## Problem 
The app can be crashed from time to time after account creation, this can be caught by e2e

NOTE: reproduced not that often as https://github.com/status-im/status-mobile/issues/16560 so supposedly another issue

#### Expected behavior
no crash

#### Actual behavior
Session: https://app.eu-central-1.saucelabs.com/tests/3c7924f0fb5b43bcb186349019909e3b?auth=1437d1dc137f19439be711ef24141c13#24

https://github.com/status-im/status-mobile/assets/4557972/8f6ff159-70d8-408d-863e-f8bc1936a50c

### Reproduction

1. Create profile

### Additional Information

- Status version: nightly 
- Operating System: Android
- Logcat:  [logcat (16).log](https://github.com/status-im/status-mobile/files/12440352/logcat.16.log)

[comment]: # (Please, add logs/notes if necessary)

**Comment by cammellos** [comment]
similar
```
08-25 12:45:06.614  5571  5948 D ReactNativeJS: DEBUG [utils.re-frame:21] - Handling re-frame event:  :signals/signal-received
08-25 12:45:06.619  5571     0 E Go      : panic: send on closed channel
08-25 12:45:06.619  5571     0 E Go      : 
08-25 12:45:06.619  5571     0 E Go      : goroutine 2262 [running]:
08-25 12:45:06.619  5571     0 E Go      : github.com/status-im/status-go/vendor/github.com/waku-org/go-waku/waku/v2/discv5.(*DiscoveryV5).peerLoop.func2(0x90262fc0, {{0x8dbe0000, 0x27}, {0x8dff0640, 0x2, 0x2}})
08-25 12:45:06.619  5571     0 E Go      : 	github.com/status-im/status-go/vendor/github.com/waku-org/go-waku/waku/v2/discv5/discover.go:418 +0xde
08-25 12:45:06.619  5571     0 E Go      : github.com/status-im/status-go/vendor/github.com/waku-org/go-waku/waku/v2/discv5.(*DiscoveryV5).Iterate(0x8d141780, {0xc00b1540, 0x8e1500c0}, {0xc00aea88, 0x8dff0270}, 0x8db3beec)
08-25 12:45:06.619  5571     0 E Go      : 	github.com/status-im/status-go/vendor/github.com/waku-org/go-waku/waku/v2/discv5/discover.go:358 +0x55f
08-25 12:45:06.619  5571     0 E Go      : github.com/status-im/status-go/vendor/github.com/waku-org/go-waku/waku/v2/discv5.(*DiscoveryV5).peerLoop(0x8d141780, {0xc00b1540, 0x8e1500c0})
08-25 12:45:06.619  5571     0 E Go      : 	github.com/status-im/status-go/vendor/github.com/waku-org/go-waku/waku/v2/discv5/discover.go:411 +0x371
08-25 12:45:06.619  5571     0 E Go      : github.com/status-im/status-go/vendor/github.com/waku-org/go-waku/waku/v2/discv5.(*DiscoveryV5).runDiscoveryV5Loop(0x8d141780, {0xc00b1540, 0x8e1500c0})
08-25 12:45:06.619  5571     0 E Go      : 	github.com/status-im/status-go/vendor/github.com/waku-org/go-waku/waku/v2/discv5/discover.go:434 +0x53
08-25 12:45:06.619  5571     0 E Go      : github.com/status-im/status-go/vendor/github.com/waku-org/go-waku/waku/v2/discv5.(*DiscoveryV5).Start.func1()
08-25 12:45:06.619  5571     0 E Go      : 	github.com/status-im/status-go/vendor/github.com/waku-org/go-waku/waku/v2/discv5/discover.go:212 +0x89
08-25 12:45:06.619  5571     0 E Go      : created by github.com/status-im/status-go/vendor/github.com/waku-org/go-waku/waku/v2/discv5.(*DiscoveryV5).Start
08-25 12:45:06.619  5571     0 E Go      : 	github.com/status-im/status-go/vendor/github.com/waku-org/go-waku/waku/v2/discv5/discover.go:210 +0x1c9

```

**Comment by cammellos** [comment]
Same bug as https://github.com/status-im/status-mobile/issues/17115 (different repro steps possibly, but stacktrace identical)
