### ISSUE TITLE
Tests fail after upgrading react-native to 0.72

### ISSUE THREAD

**Issue by siddarthkay** [status-im/status-react#17403]
# Problem

`make test` fails with : 
```
✨  Done in 21.98s.
INFO [09-24|22:43:00.229] Status backend initialized               backend=geth version= commit= IpfsGatewayURL=
SHADOW import error /Users/siddarthkumar/code/experiments/status-mobile/target/test/cljs-runtime/quo.animated.js
/Users/siddarthkumar/code/experiments/status-mobile/target/test/test.js:67
    throw e;
    ^

Error: Oops, Unexpected object value (undefined)
    at /Users/siddarthkumar/code/experiments/status-mobile/target/test/cljs-runtime/quo.animated.js:175:102
    at /Users/siddarthkumar/code/experiments/status-mobile/target/test/cljs-runtime/quo.animated.js:181:4
    at global.SHADOW_IMPORT (/Users/siddarthkumar/code/experiments/status-mobile/target/test/test.js:64:44)
    at /Users/siddarthkumar/code/experiments/status-mobile/target/test/test.js:1622:1
    at Object.<anonymous> (/Users/siddarthkumar/code/experiments/status-mobile/target/test/test.js:2868:3)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Function.hookedLoader [as _load] (/Users/siddarthkumar/code/experiments/status-mobile/test-resources/override.js:16:10) {
  'cljs$core$IPrintWithWriter$': {},
  'cljs$core$IPrintWithWriter$_pr_writer$arity$3': [Function (anonymous)]
}

Node.js v18.16.0
make: *** [test] Error 1
```

first observed here : https://github.com/status-im/status-mobile/pull/17241#issuecomment-1714981272

## Notes: 
- Issue could be related to metro being updated along side of react-native.
- Issue is not related to node version.
- Issue is not related to clojurescript version.
- Issue could be related to `shadow-cljs.edn` file

links that seem related : 
- https://github.com/thheller/shadow-cljs/issues/1084
- https://github.com/google/closure-compiler/wiki/JS-Modules#dynamic-import-expressions
- https://github.com/google/closure-compiler/pull/3204

blocks [react native and other](https://github.com/status-im/status-mobile/pull/17241)

**Comment by siddarthkay** [comment]
I generally stay away from compiled code but looking at `status-mobile/target/test/cljs-runtime/quo.animated.js:175:102`

I see 
`quo.animated.extrapolate = new cljs.core.PersistentArrayMap(null, 1, [new cljs.core.Keyword(null,"clamp","clamp",1803814940),(function (){var target_obj_20183 = shadow.js.shim.module$react_native_reanimated.Extrapolate;
var _STAR_runtime_state_STAR__orig_val__20185 = oops.state._STAR_runtime_state_STAR_;
var _STAR_runtime_state_STAR__temp_val__20186 = oops.state.prepare_state.call(null,target_obj_20183,(new Error()),function(){arguments[0].apply(console,Array.prototype.slice.call(arguments,1))});
(oops.state._STAR_runtime_state_STAR_ = _STAR_runtime_state_STAR__temp_val__20186);
`
This could be related to the aggressive nuking of re-animated v1 code  here : https://github.com/status-im/status-mobile/pull/16721/commits/9a90592a727ccc766de5509ab4aaa3f6bcb2d829#diff-099675f8cad1cec308b38dbcf3669126954c37da034fe2f8ae4df841c54fa94a

**Comment by siddarthkay** [comment]
The compiled code was failing because of `(def extrapolate {:clamp (oget Extrapolate "CLAMP")})`
fixed here https://github.com/status-im/status-mobile/pull/17241/commits/4c7a0ca3fc232bfcce5506922cd3e9df641957ad
