### ISSUE TITLE
Sync is broken (crash after sync, some data is not restored, screenshots are blocked after sync)

### ISSUE THREAD

**Issue by churik** [status-im/status-react#18021]
# Bug Report

## Problem 
Tested on builds with upgarded status-go (PR https://github.com/status-im/status-mobile/pull/17906 and PR  https://github.com/status-im/status-mobile/pull/17979, state on commit https://github.com/status-im/status-go/commit/472e4bdb7761e9e05204dd0f74b1a5f138e8138c)  + current desktop develop (0.171.20)

Currently after sync there are several issues:
1) Case1: sometimes username is not restored
![IMAGE 2023-11-29 11:34:07](https://github.com/status-im/status-mobile/assets/4557972/0fcd602e-75d9-49aa-8fa5-738db54f5846)
![IMAGE 2023-11-29 11:34:26](https://github.com/status-im/status-mobile/assets/4557972/b1b7a5b1-6075-4d5e-9009-ca69058137f4)

2) In both cases: Advanced > Block screenshots is enabled after sync
<img width="222" alt="Monosnap 2023-11-29 11-39-59" src="https://github.com/status-im/status-mobile/assets/4557972/41bbc7de-b298-4686-ab57-ad803b174deb">

3) In both cases: Android crashed after sync
4) Case  2: contacts are not restored, got a list of empty chats + bunch of pending contact requests + bunch of cummunities are not synced

https://github.com/status-im/status-mobile/assets/4557972/77ca130d-18c1-4015-b5b8-ba538c5a171d

#### Expected behavior

1-4 are not reproducible

### Reproduction

1. Desktop: open Syncing > Setup syncing
2. Mobile: Sign in>Scan qr

### Additional Information

- Status version: status-go develop  https://github.com/status-im/status-go/commit/472e4bdb7761e9e05204dd0f74b1a5f138e8138c + Status-desktop nightly 28/11
- Operating System: Android,

### LOGS

Case 1: [Status-debug-logs (80).zip](https://github.com/status-im/status-mobile/files/13499711/Status-debug-logs.80.zip)

Case 2: [Status-debug-logs.zip](https://github.com/status-im/status-mobile/files/13499708/Status-debug-logs.zip)

**Comment by cammellos** [comment]
@churik do you have the raw logcat for one of the session that crashes please?

**Comment by churik** [comment]
@cammellos [logcat_crash.log](https://github.com/status-im/status-mobile/files/13500548/logcat_crash.log)

**Comment by cammellos** [comment]
```
2023-11-29 13:32:37.206 24838-0/? E/Go: goroutine 17 [running, locked to thread]:
2023-11-29 13:32:37.206 24838-0/? E/Go: github.com/status-im/status-go/protocol/communities.(*Community).IsControlNode(0x6e814d5ee0?)
2023-11-29 13:32:37.206 24838-0/? E/Go: 	github.com/status-im/status-go/protocol/communities/community.go:1131 +0x18
2023-11-29 13:32:37.206 24838-0/? E/Go: 
github.com/status-im/status-go/protocol/communities.(*Community).HasPermissionToSendCommunityEvents(0x0)
2023-11-29 13:32:37.206 24838-0/? E/Go: 	github.com/status-im/status-go/protocol/communities/community.go:1183 +0x24
2023-11-29 13:32:37.206 24838-0/? E/Go: 
github.com/status-im/status-go/protocol/communities.(*Manager).HandleCommunityTokensMetadataByPrivilegedMembers(0x40033f6300?, 
0x4002b6a5a0?)
2023-11-29 13:32:37.206 24838-0/? E/Go: 	github.com/status-im/status-go/protocol/communities/manager.go:4738 +0x28
2023-11-29 13:32:37.206 24838-0/? E/Go: 
github.com/status-im/status-go/protocol.(*Messenger).handleCommunityTokensMetadataByPrivilegedMembers(...)
2023-11-29 13:32:37.206 24838-0/? E/Go: 	github.com/status-im/status-go/protocol/messenger_communities.go:3291
2023-11-29 13:32:37.206 24838-24953/? E/GoLog: panic: runtime error: invalid memory address or nil pointer dereference
2023-11-29 13:32:37.206 24838-0/? E/Go: 
github.com/status-im/status-go/protocol.(*Messenger).handleSyncInstallationCommunity(0x400339c000, 0x4001d0ecf8, 0x4002c12340, 
0x6e8186c130?)
2023-11-29 13:32:37.206 24838-0/? E/Go: 	github.com/status-im/status-go/protocol/messenger_communities.go:3230 +0xe28
2023-11-29 13:32:37.206 24838-24953/? E/GoLog: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x6e80c99348]
2023-11-29 13:32:37.206 24838-0/? E/Go: github.com/status-im/status-go/protocol.(*Messenger).HandleSyncRawMessages(0x400339c000, 
{0x400094ec00, 0x64, 0x24?})
2023-11-29 13:32:37.206 24838-0/? E/Go: 	github.com/status-im/status-go/protocol/messenger_sync_raw_messages.go:119 +0x9e0

```
I think I can fix this

**Comment by pavloburykh** [comment]
closing this one as issues 3-4 are fixed. 

Created separate issues for [1](https://github.com/status-im/status-mobile/issues/18040) and [2](https://github.com/status-im/status-mobile/issues/18041)
