### ISSUE TITLE
App crashes after recover of any user

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#18092]
This bug is not in our develop yet. So it should be reproduced in the builds looking at current go develop. 

You can reproduce the bug in PR builds that include new go version, for example https://github.com/status-im/status-mobile/pull/17941 or https://github.com/status-im/status-mobile/pull/18069

**Steps:**

1. Recover any user
2. See if app is not crashing after recovery

**Actual result:** app crashes

[Status-debug-logs (88).zip](https://github.com/status-im/status-mobile/files/13583223/Status-debug-logs.88.zip)

https://github.com/status-im/status-mobile/assets/97245802/1b295bea-0ef4-4966-9745-d5f19f3aea1a

**Expected result:** app does not crash

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by cammellos** [comment]
```
INFO [11-29|10:12:55.686|github.com/status-im/status-go/protocol/messenger_mailserver_cycle.go:270]                                          connecting error                         eerr="tcp check timeout: I/O timeout"
INFO [11-29|10:12:55.686|github.com/status-im/status-go/protocol/messenger_mailserver_cycle.go:270]                                          connecting error                         eerr="tcp check timeout: I/O timeout"
INFO [11-29|10:12:55.686|github.com/status-im/status-go/protocol/messenger_mailserver_cycle.go:270]                                          connecting error                         eerr="tcp check timeout: I/O timeout"
INFO [11-29|10:12:55.687|github.com/status-im/status-go/protocol/messenger_mailserver_cycle.go:270]                                          connecting error                         eerr="tcp check timeout: I/O timeout"
INFO [11-29|10:12:55.687|github.com/status-im/status-go/protocol/messenger_mailserver_cycle.go:270]                                          connecting error                         eerr="tcp check timeout: I/O timeout"
INFO [11-29|10:12:55.687|github.com/status-im/status-go/protocol/messenger_mailserver_cycle.go:270]                                          connecting error                         eerr="tcp check timeout: I/O timeout"

```
Don't think it's causing the crash, but worth maybe having a look, @richard-ramos

**Comment by pavloburykh** [comment]
@cammellos here is a logcat 
[crashlog_061223.log.zip](https://github.com/status-im/status-mobile/files/13583353/crashlog_061223.log.zip)

**Comment by cammellos** [comment]
```
12-06 14:36:15.474 19241     0 E Go      : [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x7998307748]
12-06 14:36:15.474 19241     0 E Go      : 
12-06 14:36:15.474 19241     0 E Go      : goroutine 28293 [running]:
12-06 14:36:15.474 19241     0 E Go      : github.com/status-im/status-go/services/wallet/transfer.(*loadBlocksAndTransfersCommand).fetchHistoryBlocks(0x40062c2480, {0x4003be1e78?, 0x4?}, 0x4?, {0x8a, 0x13, 0x12, 0x24, 0x6b, 0x98, ...}, ...)
12-06 14:36:15.474 19241     0 E Go      : 	github.com/status-im/status-go/services/wallet/transfer/commands_sequential.go:803 +0x2d8
12-06 14:36:15.475 19241     0 E Go      : github.com/status-im/status-go/services/wallet/transfer.(*loadBlocksAndTransfersCommand).Run(0x40062c2480, {0x7998e3d818, 0x4006205340})
12-06 14:36:15.475 19241     0 E Go      : 	github.com/status-im/status-go/services/wallet/transfer/commands_sequential.go:745 +0x3c4
12-06 14:36:15.475 19241     0 E Go      : github.com/status-im/status-go/services/wallet/async.InfiniteCommand.Run({0x4006847601?, 0x4006726d00?}, {0x7998e3d818, 0x4006205340})
12-06 14:36:15.475 19241     0 E Go      : 	github.com/status-im/status-go/services/wallet/async/async.go:72 +0x40
12-06 14:36:15.475 19241     0 E Go      : github.com/status-im/status-go/services/wallet/async.(*Group).Add.func1()
12-06 14:36:15.475 19241     0 E Go      : 	github.com/status-im/status-go/services/wallet/async/async.go:101 +0x34
12-06 14:36:15.475 19241     0 E Go      : created by github.com/status-im/status-go/services/wallet/async.(*Group).Add
12-06 14:36:15.475 19241     0 E Go      : 	github.com/status-im/status-go/services/wallet/async/async.go:100 +0x8c
12-06 14:36:15.475 19241 20645 E GoLog   : panic: runtime error: invalid memory address or nil pointer dereference
12-06 14:36:15.475 19241 20645 E GoLog   : [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x7998307748]

```

**Comment by cammellos** [comment]
@pavloburykh can you ask people to rebase against status-go develop? the code has changed since then

**Comment by pavloburykh** [comment]
> @pavloburykh can you ask people to rebase against status-go develop? the code has changed since then

@cammellos unfortunately rebasing didn't help. I have checked latest builds here https://github.com/status-im/status-mobile/pull/18069 and still facing the crash. 

Attaching fresh logcat if needed.

[crashlog_111333.log.zip](https://github.com/status-im/status-mobile/files/13587298/crashlog_111333.log.zip)

**Comment by cammellos** [comment]
```
12-06 16:26:11.140 21775     0 E Go      : goroutine 1973 [running]:
12-06 16:26:11.140 21775     0 E Go      : github.com/status-im/status-go/services/wallet/transfer.(*loadBlocksAndTransfersCommand).fetchHistoryBlocks(0x4003f54c60, {0x4002671e78?, 0x4?}, 0x4?, {0x4, 0x88, 0x34, 0x26, 0x6d, 0x47, ...}, ...)
12-06 16:26:11.140 21775     0 E Go      : 	github.com/status-im/status-go/services/wallet/transfer/commands_sequential.go:821 +0x2d8
12-06 16:26:11.140 21775     0 E Go      : github.com/status-im/status-go/services/wallet/transfer.(*loadBlocksAndTransfersCommand).Run(0x4003f54c60, {0x7cf5213af8, 0x4003ec3b00})
12-06 16:26:11.140 21775     0 E Go      : 	github.com/status-im/status-go/services/wallet/transfer/commands_sequential.go:763 +0x3c4
12-06 16:26:11.140 21775     0 E Go      : github.com/status-im/status-go/services/wallet/async.InfiniteCommand.Run({0x0?, 0x4003f398f0?}, {0x7cf5213af8, 0x4003ec3b00})
12-06 16:26:11.140 21775     0 E Go      : 	github.com/status-im/status-go/services/wallet/async/async.go:72 +0x40
12-06 16:26:11.140 21775     0 E Go      : github.com/status-im/status-go/services/wallet/async.(*Group).Add.func1()
12-06 16:26:11.141 21775     0 E Go      : 	github.com/status-im/status-go/services/wallet/async/async.go:101 +0x34
12-06 16:26:11.141 21775     0 E Go      : created by github.com/status-im/status-go/services/wallet/async.(*Group).Add
12-06 16:26:11.141 21775     0 E Go      : 	github.com/status-im/status-go/services/wallet/async/async.go:100 +0x8c
```

**Comment by cammellos** [comment]
@IvanBelyakoff could you have a look at the issue above please?

**Comment by siddarthkay** [comment]
`fetchHistoryBlocks ` https://github.com/status-im/status-go/commit/82185b54b5e23b096086cd491d380bbc7b2c74ef#diff-32cceb00b8d06fb3f28df6024d1e28c526c6215bb329976d5fed6a4c5fffcf4cR1102 code was touched in https://github.com/status-im/status-go/pull/4386

**Comment by cammellos** [comment]
@IvanBelyakoff will take a look at this tomorrow morning. Thank you!

**Comment by IvanBelyakoff** [comment]
Guys, sorry for the issue. Here is a quick fix https://github.com/status-im/status-go/pull/4433
For me no crash on recovery on desktop.
@pavloburykh @cammellos

**Comment by pavloburykh** [comment]
> Guys, sorry for the issue. Here is a quick fix [status-im/status-go#4433](https://github.com/status-im/status-go/pull/4433) For me no crash on recovery on desktop. @pavloburykh @cammellos

@IvanBelyakoff thank you for the fix! Unfortunately still reproducing issue when recovering user with tokens. I have left the details here https://github.com/status-im/status-mobile/pull/18110#issuecomment-1844983431

**Comment by IvanBelyakoff** [comment]
I updated the PR, please check it once again. There was another crash in a different place

**Comment by cammellos** [comment]
@pavloburykh removing release blocker label, as this is not on 1.26 branch

**Comment by pavloburykh** [comment]
Fixed by https://github.com/status-im/status-mobile/pull/18110
