### ISSUE TITLE
Take a look at flaky component test

### ISSUE THREAD

**Issue by siddarthkay** [status-im/status-react#18157]
Component tests are flaky due to us patching the jest config at react-native here : https://github.com/status-im/status-mobile/blob/develop/nix/deps/nodejs-patched/default.nix#L60-L64

We have to do this because react-native 0.72.x uses jest 29.x and our codebase has jest 26 ( jest 26 is no longer supported btw)

as pointed here upgrading jest was a pain last time I had tried : https://github.com/status-im/status-mobile/issues/17409#issuecomment-1742650078

But to solve the flakiness that seems to be the only way forward.
We'll have to get builds working with latest version of jest and remove this patch.

**Comment by smohamedjavid** [comment]
One of my PRs #18100 - Failed on the `username` component. 

[Console log](https://ci.status.im/job/status-mobile/job/prs/job/tests/job/PR-18100/8/consoleText)

But, re-running the tests seems to working well. 

```log
[2023-12-11T19:13:57.018Z] Summary of all failing tests
[2023-12-11T19:13:57.018Z] FAIL ./quo.components.text_combinations.username.component_spec.js
[2023-12-11T19:13:57.018Z]   ● Text combinations - Username › Render different :name-type values › nickname › All status are rendered › Verified status
[2023-12-11T19:13:57.018Z] 
[2023-12-11T19:13:57.018Z]     `render` method has not been called
[2023-12-11T19:13:57.018Z] 
[2023-12-11T19:13:57.018Z]       at Function.Object.<anonymous>.test_helpers.component.wait_for.cljs$core$IFn$_invoke$arity$2 (test_helpers/component.cljs:52:4)
[2023-12-11T19:13:57.018Z]       at test_helpers$component$wait_for (test_helpers.component.js:111:46)
[2023-12-11T19:13:57.018Z]       at Function.Object.<anonymous>.test_helpers.component.wait_for.cljs$core$IFn$_invoke$arity$1 (test_helpers.component.js:118:42)
[2023-12-11T19:13:57.018Z]       at test-helpers.component/wait-for (test_helpers.component.js:108:46)
[2023-12-11T19:13:57.018Z]       at Object.<anonymous> (quo/components/inputs/address_input/component_spec.cljs:147:10)
```



The issue is not related to any component. I guess this is more on the react native testing library.

**Comment by siddarthkay** [comment]
you're right @smohamedjavid 
also common theme in test failures seem to be related to the wait-for helper method here : 
https://github.com/status-im/status-mobile/blob/develop/src/test_helpers/component.cljs#L71-L74

**Comment by ajayesivan** [comment]
Re-enable component tests disabled [here](https://github.com/status-im/status-mobile/pull/18243) once this issue is resolved.

**Comment by ilmotta** [comment]
@siddarthkay, I can try to upgrade Jest to match RN's requirement. It's the only way forward to me. The changelog from Jest 26 to 29 is extensive and just search for the word `breaking` and I get dozens of hits. Have we written somewhere the most critical breaking changes from Jest 26 to 29 that could affect us?

Hopefully Jest doesn't bump to version 100 when I finish 😆 

Edit: Or are you already working on upgrading Jest to 29?
