### ISSUE TITLE
Random crashes occur during manual logout

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#18202]
Unfortunately there are no clear steps of how to reproduce the crash. Last time I have reproduced it following below steps in the [PR](https://github.com/status-im/status-mobile/pull/18140#issuecomment-1857859652). Maybe something will be clear based on attached logs.  cc @vitvly 

**Steps:** 

1. Recover User A on Device 1 and Device 2. Set different passwords and Enable biometrics for both devices during recovery (not sure if it is important step)
2. Sync Devices
3. Change profile picture on Device 1, add some community on Device 2 (also not sure if this step is important)
4. Perform manual logout on devices
5. See if app has not crashed on logout

**Actual result:** sometimes (both IOS and Android) crash on manual logout. 

[logcat_151223.log.zip](https://github.com/status-im/status-mobile/files/13685497/logcat_151223.log.zip)

[Status-debug-logs (90).zip](https://github.com/status-im/status-mobile/files/13685499/Status-debug-logs.90.zip)

https://github.com/status-im/status-mobile/assets/97245802/fef2f67f-90fa-42df-98c4-b92ba5890ffb

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

**Comment by pavloburykh** [comment]
Panic found by @qfrank in the above logs. 


```
12-15 14:53:58.687 14067     0 E Go      : panic: runtime error: invalid memory address or nil pointer dereference
12-15 14:53:58.687 14067     0 E Go      : [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x77715d63c0]
12-15 14:53:58.687 14067     0 E Go      : 
12-15 14:53:58.687 14067     0 E Go      : goroutine 455 [running]:
12-15 14:53:58.687 14067     0 E Go      : github.com/status-im/status-go/wakuv2.(*Waku).broadcast(0x40001c0f00)
12-15 14:53:58.687 14067     0 E Go      : 	github.com/status-im/status-go/wakuv2/waku.go:1060 +0x40
12-15 14:53:58.687 14067     0 E Go      : created by github.com/status-im/status-go/wakuv2.(*Waku).Start
12-15 14:53:58.687 14067     0 E Go      : 	github.com/status-im/status-go/wakuv2/waku.go:1270 +0x7c4
```
