### ISSUE TITLE
Messages stuck in sending for a long time in communities which have lot of token gated channels

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#19042]
Reproducible on release builds both on Mobile and Desktop

Example of community with permissions for token gated channels set on Sepolia (0.001 ETH to View and Post) https://status.app/c/G0cAAGTy2qJxtFl_0TfQ34AeLCjbEnoEUkhWnReqKLv_9_W5FThdDdEd__tqXgMDj_O09lvpcDVI#zQ3shfxkA7AsQ633jsEE2dH5AGFGfnigtj26JHUdX1FdBRmm4

Example of community with permissions for token gated channels set on Mainnet (0.001 ETH to View and Post) https://status.app/c/G7oAAORtQxyCU4KaUi8IyqJxit5tneYINuDALdNEJ99sUBsmchZY0nagyx_Y16aeF2SRKg_WlW_K0CxgpDT6rPtktOIA#zQ3shrEJ1GuDRnSnCBuJpGW88ovc2UiQQsQ8PGatYKGJy4KTY

**Steps:** 

1. Create a community that has a lot of token gated channels (or use community from the example)
2. Join this community (in case you are not admin)
3. Start sending messages in any channel
4. Pay attention how much time it takes for message to be sent

**Actual result:** stuck in sending for a long time. Also, logging the account of such community member takes a long time. 

Below I attach logs and videos from mobile and desktop. 

[logs (20).zip](https://github.com/status-im/status-mobile/files/14438746/logs.20.zip)
[geth_Desktop.log](https://github.com/status-im/status-mobile/files/14439000/geth_Desktop.log)

https://github.com/status-im/status-mobile/assets/97245802/bc444377-e221-4549-b3c6-8a3983bb2a03

https://github.com/status-im/status-mobile/assets/97245802/1b8bcc7e-4e95-454f-8240-4e4f7180b42e

### Additional Information

- Status version: release 
- Operating System: Android, iOS, MacOS
- builds: mobile/Desktop

**Comment by cammellos** [comment]
```
2024-02-28T18:26:40.236Z DEBUG [utils.re-frame:23] - Handling re-frame event:  :mention/on-error

2024-02-28T18:26:40.238Z ERROR [legacy.status-im.chat.models.mentions:78] - [mentions] on-error {:context
 {:method "wakuext_chatMentionOnChangeText",
  :params
  ["0x03ac329a8ffe9d3021f1dfcce354958337659238a869510d440db5f4f35e104fe30cd99d53-0097-4c91-a5a2-9b2f4a4a2381"
   "0"]}, 
 :error {:code -32603, :message "method handler crashed"}}

2024-02-28T18:26:40.258Z DEBUG [utils.re-frame:23] - Handling re-frame event:  :app-state-change

2024-02-28T18:26:40.260Z INFO [legacy.status-im.wallet.core:734] - restart-wallet-service force-restart? nil
 syncing-allowed? true
 binance-chain? false

```

```
ERROR[02-28|17:46:30.816|github.com/status-im/status-go/protocol/common/message_sender.go:968]                             failed to handle an encrypted message    site=handleEncryptionLayer error="failed to unmarshal ProtocolMessage: string field contains invalid UTF-8"
ERROR[02-28|17:46:31.216|github.com/status-im/status-go/vendor/github.com/ethereum/go-ethereum/rpc/service.go:200]         RPC method wakuext_chatMentionOnChangeText crashed: runtime error: invalid memory address or nil pointer dereference
goroutine 9826 [running]:
github.com/status-im/status-go/vendor/github.com/ethereum/go-ethereum/rpc.(*callback).call.func1()
	/private/tmp/nix-build-status-go-develop-f29f91e-ios.drv-0/go/src/github.com/status-im/status-go/vendor/github.com/ethereum/go-ethereum/rpc/service.go:199 +0x74
panic({0x105822ec0, 0x1070d3b00})
	/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-go-1.19.9/share/go/src/runtime/panic.go:884 +0x204
github.com/status-im/status-go/protocol.(*MentionManager).calculateSuggestionsWithMentionableUsers(0x130d6b650, {0x14538e850, 0x68}, {0x14866a860, 0x6}, 0x3?)
	/private/tmp/nix-build-status-go-develop-f29f91e-ios.drv-0/go/src/github.com/status-im/status-go/protocol/messenger_mention.go:339 +0x150
github.com/status-im/status-go/protocol.(*MentionManager).calculateSuggestions(0x130d6b650, {0x14538e850, 0x68}, {0x14866a860, 0x6})
	/private/tmp/nix-build-status-go-develop-f29f91e-ios.drv-0/go/src/github.com/status-im/status-go/protocol/messenger_mention.go:330 +0x348
github.com/status-im/status-go/protocol.(*MentionManager).OnChangeText(0x130d6b650, {0x14538e850, 0x68}, {0x14866a860, 0x6})
	/private/tmp/nix-build-status-go-develop-f29f91e-ios.drv-0/go/src/github.com/status-im/status-go/protocol/messenger_mention.go:318 +0x418
github.com/status-im/status-go/services/ext.(*PublicAPI).ChatMentionOnChangeText(0x5?, {0x14538e850?, 0x1312ac240?}, {0x14866a860?, 0x1307234b8?})
	/private/tmp/nix-build-status-go-develop-f29f91e-ios.drv-0/go/src/github.com/status-im/status-go/services/ext/api.go:1628 +0x30
reflect.Value.call({0x143854180?, 0x14384a738?, 0x107c94108?}, {0x104cd4a6a, 0x4}, {0x1485e9080, 0x3, 0x1039b996c?})
	/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-go-1.19.9/share/go/src/reflect/value.go:584 +0x68c
reflect.Value.Call({0x143854180?, 0x14384a738?, 0x14866a830?}, {0x1485e9080?, 0x2?, 0x16?})
	/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-go-1.19.9/share/go/src/reflect/value.go:368 +0x90
github.com/status-im/status-go/vendor/github.com/ethereum/go-ethereum/rpc.(*callback).call(0x1438532c0, {0x105bca358?, 0x12dd78e40}, {0x148ed0920, 0x1f}, {0x131b4cdb0, 0x2, 0x1039b3150?})
	/private/tmp/nix-build-status-go-develop-f29f91e-ios.drv-0/go/src/github.com/status-im/status-go/vendor/github.com/ethereum/go-ethereum/rpc/service.go:205 +0x38c
github.com/status-im/status-go/vendor/github.com/ethereum/go-ethereum/rpc.(*handler).runMethod(0x143a2a500?, {0x105bca358?, 0x12dd78e40?}, 0x1302b8b60, 0x2?, {0x131b4cdb0?, 0x10100014a6e49b0?, 0x0?})
	/private/tmp/nix-build-status-go-develop-f29f91e-ios.drv-0/go/src/github.com/status-im/status-go/vendor/github.com/ethereum/go-ethereum/rpc/handler.go:391 +0x40
github.com/status-im/status-go/vendor/github.com/ethereum/go-ethereum/rpc.(*handler).handleCall(0x130494a20, 0x131b4cd50, 0x1302b8b60)
	/private/tmp/nix-build-status-go-develop-f29f91e-ios.drv-0/go/src/github.com/status-im/status-go/vendor/github.com/ethereum/go-ethereum/rpc/handler.go:336 +0x1dc
github.com/status-im/status-go/vendor/github.com/ethereum/go-ethereum/rpc.(*handler).handleCallMsg(0x130494a20, 0x131b4cd50?, 0x1302b8b60)
	/private/tmp/nix-build-status-go-develop-f29f91e-ios.drv-0/go/src/github.com/status-im/status-go/vendor/github.com/ethereum/go-ethereum/rpc/handler.go:297 +0x1d4
github.com/status-im/status-go/vendor/github.com/ethereum/go-ethereum/rpc.(*handler).handleMsg.func1(0x131b4cd50)
	/private/tmp/nix-build-status-go-develop-f29f91e-ios.drv-0/go/src/github.com/status-im/status-go/vendor/github.com/ethereum/go-ethereum/rpc/handler.go:138 +0x34
github.com/status-im/status-go/vendor/github.com/ethereum/go-ethereum/rpc.(*handler).startCallProc.func1()
	/private/tmp/nix-build-status-go-develop-f29f91e-ios.drv-0/go/src/github.com/status-im/status-go/vendor/github.com/ethereum/go-ethereum/rpc/handler.go:225 +0xc0
created by github.com/status-im/status-go/vendor/github.com/ethereum/go-ethereum/rpc.(*handler).startCallProc
	/private/tmp/nix-build-status-go-develop-f29f91e-ios.drv-0/go/src/github.com/status-im/status-go/vendor/github.com/ethereum/go-ethereum/rpc/handler.go:221 +0x8c
 
WARN [02-28|17:46:31.216|github.com/status-im/status-go/vendor/github.com/ethereum/go-ethereum/rpc/handler.go:305]         Served wakuext_chatMentionOnChangeText   reqid=122 duration=41.157041ms err="method handler crashed"
ERROR[02-28|17:46:31.589|github.com/status-im/status-go/protocol/pushnotificationclient/client.go:900]                     could not retrieve message               error="record not found"
W
```

Not sure that's related, but this is the log for the crash

**Comment by cammellos** [comment]
```
DEBUG[02-28|21:07:25.452|github.com/status-im/status-go/wakuv2/waku.go:1673]                                         not querying bootnodes                   seeded=true peer-count=6
DEBUG[02-28|21:07:25.486|github.com/status-im/status-go/protocol/messenger.go:1601]                                  failed to resend expired message         error="Only public chats and community chats messages are resent"
DEBUG[02-28|21:07:25.554|github.com/status-im/status-go/protocol/messenger_mailserver_cycle.go:727]                  wakuV2 storenode status verification 
DEBUG[02-28|21:07:25.605|github.com/status-im/mvds/node/node.go:185]                                                 Epoch processing                         namespace=mvds node=04864569 epoch=1,716,869
DEBUG[02-28|21:07:25.906|github.com/status-im/mvds/node/node.go:185]                                                 Epoch processing                         namespace=mvds node=04864569 epoch=1,716,870
DEBUG[02-28|21:07:25.950|github.com/waku-org/go-waku/waku/v2/peermanager/peer_manager.go:191]                        number of peers connected                inPeers=0 outPeers=6
DEBUG[02-28|21:07:25.950|github.com/waku-org/go-waku/waku/v2/peermanager/peer_manager.go:252]                        number of relay peers connected          in=0 out=6
DEBUG[02-28|21:07:25.952|github.com/status-im/status-go/wakuv2/waku.go:1673]                                         not querying bootnodes                   seeded=true peer-count=6
DEBUG[02-28|21:07:25.977|github.com/status-im/status-go/protocol/messenger.go:2531]                                  inside sendChatMessage                   id=0x64b231d5d1390a445e5e41d4de274791042de2ed5e7a3c7a402370ac2723cc12 text=dasd from=0x04864569bda288a7df2e47e19932878dd27c5ab43e36f54cbc2e06902cdae6c77fa014e4dfd96bc48eec30ba43a05ab7b4b2d78cc31cc72bc56ac807ab4b0443d6 displayName="Main mobile edit loooong" ChatId=0x03ac329a8ffe9d3021f1dfcce354958337659238a869510d440db5f4f35e104fe3e4c5d32b-0f49-4751-94b1-6a7695fbd051 Clock=1709147235621 Timestamp=1709147235621
DEBUG[02-28|21:07:25.978|rpc/handler.go:307]                                                                         Served wakuext_sendChatMessage           reqid=923 duration=13.034487667s
```
it takes 13s to send a message, seems likely it's a problem with indexes?

**Comment by anastasiyaig** [comment]
@jrainville can you please help to investigate? or someone in your team?

**Comment by cammellos** [comment]
I can have a quick look this morning

**Comment by cammellos** [comment]
Potential fix:
https://github.com/status-im/status-desktop/pull/13781

https://github.com/status-im/status-desktop/pull/13781

**Comment by anastasiyaig** [comment]
can reproduce as well, i added 10 permissions for 10 channels (1 permission per channel) and the sending become really slow. I also think 10 is more than enough , i guess the issue started appearing on 6th channel


https://github.com/status-im/status-mobile/assets/82375995/fc55148b-50b7-42d1-b297-dc3aa306f5d2

```
DEBUG[03-04|17:24:58.200|github.com/status-im/status-go/wakuv2/common/filter.go:122]                                 filters uninstall                        id=629843f495fe7d52a28c03f263feeb7ad75e435ac129213750aa3ba7f0a42a88
DEBUG[03-04|17:24:58.200|github.com/status-im/status-go/protocol/messenger.go:1937]                                  running shutdown task                    n=5
DEBUG[03-04|17:24:58.200|github.com/status-im/status-go/protocol/messenger.go:1937]                                  running shutdown task                    n=6
INFO [03-04|17:24:58.200|github.com/status-im/mvds/node/node.go:205]                                                 Stopping node                            namespace=mvds
DEBUG[03-04|17:24:58.200|github.com/status-im/status-go/protocol/messenger.go:1937]                                  running shutdown task                    n=7
DEBUG[03-04|17:24:58.200|github.com/status-im/status-go/protocol/messenger.go:1937]                                  running shutdown task                    n=8
DEBUG[03-04|17:24:58.200|github.com/status-im/status-go/wakuv2/waku.go:1708]                                         bootnode seeding stopped 
INFO [03-04|17:24:58.200|github.com/waku-org/go-waku/waku/v2/protocol/relay/waku_relay.go:505]                       unsubscribing from pubsubTopic           topic=/waku/2/rs/16/32
INFO [03-04|17:24:58.200|go.uber.org/zap/sugar.go:132]                                                               pubsub processloop shutting down 
DEBUG[03-04|17:24:58.200|github.com/waku-org/go-waku/waku/v2/node/wakunode2.go:934]                                  context done, auto-relay has enough peers 
ERROR[03-04|17:24:58.201|github.com/waku-org/go-waku/waku/v2/protocol/relay/waku_relay.go:514]                       failed to close the pubsubTopic          topic=/waku/2/rs/16/32
INFO [03-04|17:24:58.200|github.com/waku-org/go-waku/waku/v2/node/keepalive.go:61]                                   stopping ping protocol 
INFO [03-04|17:24:58.201|github.com/waku-org/go-waku/waku/v2/protocol/relay/waku_relay.go:505]                       unsubscribing from pubsubTopic           topic=/waku/2/rs/16/64
ERROR[03-04|17:24:58.201|github.com/waku-org/go-waku/waku/v2/protocol/relay/waku_relay.go:514]                       failed to close the pubsubTopic          topic=/waku/2/rs/16/64
DEBUG[03-04|17:24:58.201|go.uber.org/zap/sugar.go:204]                                                               updating snapshot                        seq=14 addrs="[/ip4/127.0.0.1/tcp/55082 /ip4/178.207.203.235/tcp/0 /ip4/192.168.1.25/tcp/55082]"
DEBUG[03-04|17:24:58.201|go.uber.org/zap/sugar.go:204]                                                               updating snapshot                        seq=15 addrs="[/ip4/127.0.0.1/tcp/55082 /ip4/178.207.203.235/tcp/0 /ip4/192.168.1.25/tcp/55082]"
DEBUG[03-04|17:24:58.201|go.uber.org/zap/sugar.go:204]                                                               updating snapshot                        seq=16 addrs="[/ip4/127.0.0.1/tcp/55082 /ip4/178.207.203.235/tcp/0 /ip4/192.168.1.25/tcp/55082]"
DEBUG[03-04|17:24:58.201|github.com/waku-org/go-discover/discover/v5_udp.go:631]                                     UDP read error                           err="read udp [::]:49953: use of closed network connection"
INFO [03-04|17:24:58.201|github.com/waku-org/go-waku/waku/v2/discv5/discover.go:249]                                 stopped Discovery V5 
DEBUG[03-04|17:24:58.201|go.uber.org/zap/sugar.go:204]                                                               updating snapshot                        seq=17 addrs="[/ip4/127.0.0.1/tcp/55082 /ip4/178.207.203.235/tcp/0 /ip4/192.168.1.25/tcp/55082]"
DEBUG[03-04|17:24:58.201|go.uber.org/zap/sugar.go:127]                                                               stopping relay finder 
DEBUG[03-04|17:24:58.201|go.uber.org/zap/sugar.go:127]                                                               stream reset 
DEBUG[03-04|17:24:58.201|go.uber.org/zap/sugar.go:163]                                                               error reading rpc from 16Uiu2HAm2M7xs7cLPc3jamawkEqbr7cUJX11uvY7LxQ6WFUdUKUT: stream reset 
DEBUG[03-04|17:24:58.202|go.uber.org/zap/sugar.go:163]                                                               Dialback through peer 16Uiu2HAmAUdrQ3uwzuE4Gy4D56hX6uLKEeerJAnhKEHZ3DxF1EfT completed: err: stream reset 
DEBUG[03-04|17:24:58.202|go.uber.org/zap/sugar.go:163]                                                               error reading rpc from 16Uiu2HAmAUdrQ3uwzuE4Gy4D56hX6uLKEeerJAnhKEHZ3DxF1EfT: stream reset 
DEBUG[03-04|17:24:58.202|go.uber.org/zap/sugar.go:163]                                                               error reading rpc from 16Uiu2HAm9aDJPkhGxc2SFcEACTFdZ91Q5TJjp76qZEhq9iF59x7R: stream reset 
DEBUG[03-04|17:24:58.202|go.uber.org/zap/sugar.go:163]                                                               error reading rpc from 16Uiu2HAm9CQhsuwPR54q27kNj9iaQVfyRzTGKrhFmr94oD8ujU6P: stream reset 
INFO [03-04|17:24:58.202|github.com/status-im/status-go/services/wallet/service.go:238]                              wallet will be stopped 
INFO [03-04|17:24:58.202|github.com/status-im/status-go/services/wallet/service.go:247]                              wallet stopped 
DEBUG[03-04|17:24:58.206|github.com/status-im/status-go/server/ports.go:49]                                          fired 
DEBUG[03-04|17:24:58.206|github.com/status-im/status-go/server/ports.go:58]                                          fired 
DEBUG[03-04|17:24:58.206|github.com/status-im/status-go/server/ports.go:30]                                          fired                                    port=57221
DEBUG[03-04|17:24:58.206|github.com/status-im/status-go/server/ports.go:40]                                          p.afterPortChanged != nil 
ERROR[03-04|17:24:58.279|github.com/status-im/mvds/node/node.go:346]                                                 error while mapping sync state           namespace=mvds error="sql: database is closed"
ERROR[03-04|17:24:58.279|github.com/status-im/mvds/node/node.go:189]                                                 Error sending messages.                  namespace=mvds error="sql: database is closed"
ERROR[03-04|17:24:58.279|github.com/status-im/mvds/node/node.go:195]                                                 Failed to persisten epoch                namespace=mvds error="sql: database is closed"
INFO [03-04|17:24:58.279|github.com/status-im/mvds/node/node.go:182]                                                 Epoch processing stopped                 namespace=mvds
```

**Comment by anastasiyaig** [comment]
@jrainville tagging you for context

**Comment by jrainville** [comment]
We have the same issue in Desktop. It is tracked here. I'll try later to investigate https://github.com/status-im/status-desktop/issues/13813

**Comment by cammellos** [comment]
Did a bit of investigation, this is most likely due to decrypting the community description, the more encrypted channels it has, the more time we decrypt it. 
There does not seem to be a single operation that takes long, but each one of them can take up to 200ms, and it compounds. 
I am further pinpointing though exactly what takes time (it could be pulling from the database etc).
In any case, the solution is probably to cache/memoize/store the community description that has been already decrypted. 
I'll post the findings just to make sure it's not just an index missing for example when decrypting.

**Comment by cammellos** [comment]
there's no single operation that is taking a long time, pulling hash ratchet keys from the db seems to be the worst culprit (100ms/200ms for the query, which is slow), but that's also because you can see that go will yield at that point, likely because of the IO operation, so that's where context switching happens. 
I'll cover that with an index, but we tried that already and doens't help overall, so I think it's time to memoize/cache the decrypted community description.

**Comment by cammellos** [comment]
Update:
I have implemented a very crude caching, and that solves the issue (that's in memory caching, and it doesn't take into account invalidation, as new encryption keys might be retrieved and that should invalidate the cache).
Tomorrow I will work on making the caching persistent  (it greatly slows down login, so we want it to be persistent), and cache invalidation.

**Comment by cammellos** [comment]
Update:
On mobile it works fine, on desktop, it's still really slow when making changes to community. 
The issue is retrieving the key from the database, the query is fairly complex and runs in 500ms * number of encrypted channels.
I am working on simplifying the query (splitting in two well covered by indexes).

**Comment by cammellos** [comment]
https://github.com/status-im/status-go/pull/4891/files 
should alleviate the problem.
Creating a channel on an community with many channel is still slow on my machine, but it went from >20s, to 1, 2 seconds.

**Comment by cammellos** [comment]
https://github.com/status-im/status-mobile/pull/19153 should fix the issue

**Comment by pavloburykh** [comment]
fixed by https://github.com/status-im/status-mobile/pull/19153
