### ISSUE TITLE
App crashes after sync

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#19655]
### Steps:
1. `User A` generates a sync QR code
2. `User B` scans the QR of `User A`

### Actual result:
App is crashed

### Expected result:
Accounts are synced without crash

### OS: 
IOS, Android

### Devices:
- Pixel 7a, Android 13
- iPhone 11 Pro Max, IOS 17

### Logs
[logs (1).txt](https://github.com/status-im/status-mobile/files/14992728/logs.1.txt)

**Comment by cammellos** [comment]
@pavloburykh @VolodLytvynenko do you have geth.log for the crashing device?

**Comment by flexsurfer** [comment]
```
0:48:54.472  E  Unable to update properties for view tag 367
                 com.facebook.react.uimanager.IllegalViewOperationException: ViewManager for tag 367 could not be found.
                 
                         at com.facebook.react.uimanager.NativeViewHierarchyManager.resolveViewManager(NativeViewHierarchyManager.java:111)
                         at com.facebook.react.uimanager.NativeViewHierarchyManager.updateProperties(NativeViewHierarchyManager.java:138)
                         at com.facebook.react.uimanager.UIImplementation.synchronouslyUpdateViewOnUIThread(UIImplementation.java:292)
                         at com.swmansion.reanimated.NodesManager.updateProps(NodesManager.java:372)
                         at com.swmansion.reanimated.nativeProxy.NativeProxyCommon.updateProps(NativeProxyCommon.java:135)
                         at com.swmansion.reanimated.AndroidUIScheduler.triggerUI(Native Method)
                         at com.swmansion.reanimated.AndroidUIScheduler$1.run(AndroidUIScheduler.java:24)
                         at com.swmansion.reanimated.AndroidUIScheduler$2.runGuarded(AndroidUIScheduler.java:43)
                         at com.facebook.react.bridge.GuardedRunnable.run(GuardedRunnable.java:29)
                         at android.os.Handler.handleCallback(Handler.java:959)
                         at android.os.Handler.dispatchMessage(Handler.java:100)
                         at android.os.Looper.loopOnce(Looper.java:232)
                         at android.os.Looper.loop(Looper.java:317)
                         at android.app.ActivityThread.main(ActivityThread.java:8501)
                         at java.lang.reflect.Method.invoke(Native Method)
                         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
```

**Comment by flexsurfer** [comment]
```
10:48:58.900  D  A3:MSG: usf_sensor.cc, 2141: USF: Sampling configuration 13050 not found.
10:48:58.900  D  A3:MSG: usf_sensor_client.cc, 145: USF: Received kErrNotFound when disabling one shot sensor.
10:48:58.918  D  [1159]< UPDATE_DEVICE_STATE 
10:48:58.980  D  2024-04-16T07:48:58.974Z DEBUG [native-module.core:411] - [native-module] get-device-model-info
10:48:59.012  D  2024-04-16T07:48:59.009Z DEBUG [native-module.core:72] - [native-module] prepare-dir-and-update-config
10:48:59.014  D  prepareDirAndUpdateConfig
10:48:59.015  D  Starting Geth node in folder: /data/user/0/im.status.ethereum.pr/no_backup/ethereum/testnet
10:48:59.025  E  updateConfig failed: No value for DataDir
10:48:59.033  I  System.exit called, status: 1
10:48:59.035  I  VM exiting with result code 1, cleanup skipped.
10:48:59.169  I  Process im.status.ethereum.pr (pid 30540) has died: fg  TOP 
10:48:59.169  D  Camera 0: start to disconnect
10:48:59.169  D  Camera 0: serializationLock acquired
10:48:59.169  D  Camera 0: Shutting down
```

**Comment by pavloburykh** [comment]
> @pavloburykh @VolodLytvynenko do you have geth.log for the crashing device?

sure @cammellos. Here it is [Status-debug-logs - 2024-04-23T130921.969.zip](https://github.com/status-im/status-mobile/files/15075148/Status-debug-logs.-.2024-04-23T130921.969.zip)
