### ISSUE TITLE
Wallet: QR scanner in SEND flow is not scanning QRs

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#1975]
### Description

*Type*: Bug

*Summary*: Can't scan QRs within wallet QR scanner in Send transaction flow

#### Expected behavior
I can scan QRs and use this functionality to add recipient

#### Actual behavior
Nothing happens when trying to scan QR. Double tap into the camera area leads the following error that crashes the app:

```
java.lang.NullPointerException: Attempt to invoke virtual method 'android.hardware.Camera$Parameters android.hardware.Camera.getParameters()' on a null object reference
	at com.lwansbrough.RCTCamera.RCTCameraViewFinder.onTouchEvent(RCTCameraViewFinder.java:349)
	at android.view.View.dispatchTouchEvent(View.java:10013)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2301)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2301)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2301)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2301)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2301)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2301)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2301)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2301)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:447)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1871)
	at android.app.Activity.dispatchTouchEvent(Activity.java:3213)
	at com.testfairy.p.q.dispatchTouchEvent(SourceFile:188)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:409)
	at android.view.View.dispatchPointerEvent(View.java:10233)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4856)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4717)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4249)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4302)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4268)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4395)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4276)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4452)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4249)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4302)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4268)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4276)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4249)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6676)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6650)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6611)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6803)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:192)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:356)
	at android.os.Looper.loop(Looper.java:138)
	at android.app.ActivityThread.main(ActivityThread.java:6577)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
```

![image](https://user-images.githubusercontent.com/28752642/31077122-078e5422-a786-11e7-90bf-05f97fdc59d3.png)

### Reproduction

- Open Status
- Go to Wallet
- Send
- Choose recipient
- Scan QR

### Additional Information

* Status version:  0.9.10-149-gb954c807+ (1706)
* Operating System: Android
* TF: from 0:40 https://app.testfairy.com/projects/4803622-status/builds/6669067/sessions/6/?accessToken=Xx1-MZ7q2xRbfpAKudB4U42QHr4

**Comment by asemiankevich** [comment]
For the crash we have separate issue logged already https://github.com/status-im/status-react/issues/1774
The QR scanner is now working as expected in latest develop `0.9.10-162-gcede0957+`. Closing this issue
