### ISSUE TITLE
Sometimes app crashes/stucks on Keys saved step during onboarding

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#20261]
This issue is caught by e2e from time to time. So far I was unable to reproduce manually. @churik has faced similar issue on IOS some time ago.

Link to the e2e steps video https://app.eu-central-1.saucelabs.com/tests/b0e4792562ca403a89a7b6296953cea1?auth=6cd3d5f3fa68bc9308cb71249fb1bdc0#23

[logcat (9).log](https://github.com/status-im/status-mobile/files/15495702/logcat.9.log)

I see panic in logcat

```
05-29 14:18:51.300  5387     0 E Go      : panic: runtime error: invalid memory address or nil pointer dereference
05-29 14:18:51.300  5387     0 E Go      : [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x73683a616540]
```

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

**Comment by siddarthkay** [comment]
**_WAKU.GO_**
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x73683a616540]

goroutine 1276 [running]:
github.com/status-im/status-go/vendor/github.com/ethereum/go-ethereum/p2p/enode.(*Node).Seq(0x7368b1b30680?)
github.com/status-im/status-go/vendor/github.com/ethereum/go-ethereum/p2p/enode/node.go:89
github.com/status-im/status-go/vendor/github.com/waku-org/go-waku/waku/v2/peermanager.(*PeerManager).
AddDiscoveredPeer(0xc000e0e790, {0x4, {{0xc0004dd260, 0x27}, 
{0xc0006b5a00, 0x3, 0x4}}, 0x0, {0xc000f376b0, 0x1, ...}}, ...)
github.com/status-im/status-go/vendor/github.com/waku-org/go-waku/waku/v2/peermanager/peer_manager.go:432 +0x170
github.com/status-im/status-go/vendor/github.com/waku-org/go-waku/waku/v2/node.(*WakuNode).AddDiscoveredPeer(...)
github.com/status-im/status-go/vendor/github.com/waku-org/go-waku/waku/v2/node/wakunode2.go:710
github.com/status-im/status-go/wakuv2.(*Waku).connect(0xc0008fa5a0, {{0xc0004dd260, 0x27}, 
{0xc0006b5a00, 0x3, 0x4}}, 0x4)
github.com/status-im/status-go/wakuv2/waku.go:452 +0x1a6
created by github.com/status-im/status-go/wakuv2.(*Waku).discoverAndConnectPeers.func1
github.com/status-im/status-go/wakuv2/waku.go:415 +0x154
```

**Comment by pavloburykh** [comment]
might be fixed by https://github.com/status-im/status-mobile/pull/20255
