### ISSUE TITLE
Android app crashes if send ether [feature/upgrade-status-go-geth17]

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#2069]
### Description

*Type*: Bug

*Summary*: App crashes if send ether in 1-1 chat. After sign Transaction app goes on background and upon switching to it user sees Sign in to Status Screen.

It happens only with Android app. For iOS send transaction message is shown in 1-1 chat

#### Expected behavior
ether is sent
#### Actual behavior
app crashes

### Reproduction
. TF session: https://app.testfairy.com/projects/4803622-status/builds/6796755/sessions/6/?accessToken=3INV/hhJsn9AGIANtiyzMJYJAj4
- Open Status
- Open 1-1 chat with Jarrad
- Send 0.04 ether

### Additional Information
* Status version: feature/upgrade-status-go-geth17  0.9.10-186-g806c75c2
* Operating System: 
Real device Samsung Galaxy S6, Android 6.0.1

End of the log:
``` 00:36 D/ReactNativeJS: DEBUG [status-im.protocol.listeners:16] - :parse-content-error CORRUPT: ccm: tag doesn't match
00:36 D/ReactNativeJS: DEBUG [status-im.utils.handlers:22] - Handling re-frame event:  :incoming-message
00:36 D/ReactNativeJS: DEBUG [status-im.protocol.web3.delivery:62] - :add-pending-message! {:from "0x04304e90820c73686227b14241b501b23eea78d235235f93c3a49d5e1bf36286126e16360308e8bfc7a5394b811ddf3ef273f263d5b4bc5049aebc1bd2be986e79", :to "0x04398d9ee89e55e15722e17676e1d510dd7792bae7c6125c8c283c460f1f9ca42b3738ffacd8d5849b6f171798bbdd70093c8f8ff59de71df720e43f1291da1f1c", :message-id "1507634544772-db9106c6-1340-57ef-966e-8e149c1281c0", :topics ["0xaabb11ee"], :type :contact-request, :ack? true, :payload {:type :contact-request, :ack? true, :ack-of-message "1507634313680-6a19f3ed-d4fa-590f-9ecb-b1f053971661", :group-id nil}}
00:36 D/ReactNativeJS: DEBUG [status-im.utils.handlers:22] - Handling re-frame event:  :contact-request-received
00:36 D/ReactNativeJS: DEBUG [status-im.utils.handlers:22] - Handling re-frame event:  :update-contact!
00:36 D/ReactNativeJS: DEBUG [status-im.utils.handlers:22] - Handling re-frame event:  :update-chat!
00:36 D/ReactNativeJS: DEBUG [status-im.utils.handlers:22] - Handling re-frame event:  :watch-contact
00:36 D/ReactNativeJS: DEBUG [status-im.protocol.web3.filtering:34] - :add-filter {:sig "0x04398d9ee89e55e15722e17676e1d510dd7792bae7c6125c8c283c460f1f9ca42b3738ffacd8d5849b6f171798bbdd70093c8f8ff59de71df720e43f1291da1f1c", :topics ["0xaabb11ee"], :key "b3c40e35a8d49e611fdaf6cf77eafe99b402aada1c0efd48b49de4c8917b5f8b", :type :sym}
00:36 D/ReactNativeJS: DEBUG [status-im.protocol.web3.transport:15] - :post-message {:sig "0x04304e90820c73686227b14241b501b23eea78d235235f93c3a49d5e1bf36286126e16360308e8bfc7a5394b811ddf3ef273f263d5b4bc5049aebc1bd2be986e79", :topic "0xaabb11ee", :payload "0x7b3a6d6573736167652d69642022313530373633343534343737322d64623931303663362d313334302d353765662d393636652d386531343963313238316330222c203a74797065203a636f6e746163742d726571756573742c203a61636b3f20747275652c203a61636b2d6f662d6d6573736167652022313530373633343331333638302d36613139663365642d643466612d353930662d396563622d623166303533393731363631222c203a67726f75702d6964206e696c2c203a636f6e74656e74206e696c7d0a", :pubKey "0x04398d9ee89e55e15722e17676e1d510dd7792bae7c6125c8c283c460f1f9ca42b3738ffacd8d5849b6f171798bbdd70093c8f8ff59de71df720e43f1291da1f1c", :ttl 120}
00:36 D/ReactNativeJS: DEBUG [status-im.protocol.web3.delivery:141] - :attempt-was-made 1507634544772-db9106c6-1340-57ef-966e-8e149c1281c0
00:36 D/ReactNativeJS: DEBUG [status-im.utils.handlers:22] - Handling re-frame event:  :set-in
00:36 D/ReactNativeJS: DEBUG [status-im.protocol.listeners:26] - :parse-payload
00:36 I/System.out: pool-47-thread-1 calls detatch()
00:37 D/ReactNativeJS: DEBUG [status-im.protocol.listeners:16] - :parse-content-error CORRUPT: ccm: tag doesn't match
00:37 D/ReactNativeJS: DEBUG [status-im.protocol.listeners:26] - :parse-payload
00:37 D/ViewRootImpl: ViewPostImeInputStage processPointer 0
00:38 D/ViewRootImpl: ViewPostImeInputStage processPointer 1
00:38 D/ReactNativeJS: DEBUG [status-im.protocol.listeners:16] - :parse-content-error CORRUPT: ccm: tag doesn't match


```

**Comment by rasom** [comment]
```
10-10 16:04:57.259 15268 15812 I System.out: pool-54-thread-1 calls detatch()
10-10 16:04:57.459 15268 15509 E Go      : panic: runtime error: invalid memory address or nil pointer dereference
10-10 16:04:57.459 15268 15509 E Go      : [signal SIGSEGV: segmentation violation code=0x1 addr=0x4 pc=0x9c3e2260]
10-10 16:04:57.459 15268 15509 E Go      : goroutine 358 [running]:
10-10 16:04:57.459 15268 15509 E Go      : panic(0x9d2ceca8, 0x8b802010)
10-10 16:04:57.459 15268 15509 E Go      : 	/usr/local/go/src/runtime/panic.go:500 +0x37c
10-10 16:04:57.459 15268 15509 E Go      : sync/atomic.addUint64(0x8d0beb44, 0x1, 0x0, 0x1, 0x0)
10-10 16:04:57.459 15268 15509 E Go      : 	/usr/local/go/src/sync/atomic/64bit_arm.go:31 +0x68
10-10 16:04:57.459 15268 15509 E Go      : github.com/status-im/status-go/geth/jail/internal/loop.(*Loop).Add(0x8d0beb40, 0x9d6cfcd0, 0x8f204b40)
10-10 16:04:57.459 15268 15509 E Go      : 	/ext-go/3/src/github.com/status-im/status-go/geth/jail/internal/loop/loop.go:75 +0x70
10-10 16:04:57.459 15268 15509 E Go      : github.com/status-im/status-go/geth/jail.(*Cell).CallAsync(0x8dc4a700, 0x5, 0x9d369050, 0x8f0ad7a0, 0x8c96f730, 0x2, 0x2)
10-10 16:04:57.459 15268 15509 E Go      : 	/ext-go/3/src/github.com/status-im/status-go/geth/jail/cell.go:71 +0x74
10-10 16:04:57.459 15268 15509 E Go      : github.com/status-im/status-go/geth/jail.makeAsyncSendHandler.func1.1(0x8bae3230, 0x8dbbe180, 0x0, 0x0, 0x5, 0x9d369050, 0x8dd51350, 0x8e967900, 0x2, 0x2, ...)
10-10 16:04:57.459 15268 15509 E Go      : 	/ext-go/3/src/github.com/status-im/status-go/geth/jail/handlers.go:81 +0x2e8
10-10 16:04:57.459 15268 15509 E Go      : created by github.com/status-im/status-go/geth/jail.makeAsyncSendHandler.func1
10-10 16:04:57.459 15268 15509 E Go      : 	/ext-go/3/src/github.com/status-im/status-go/geth/jail/handlers.go:82 +0x54
10-10 16:04:57.459  4321  4321 E audit   : type=1701 msg=audit(1507644297.459:621): auid=4294967295 uid=10328 gid=10328 ses=4294967295 subj=u:r:untrusted_app:s0:c512,c768 pid=15509 comm=4173796E635461736B202331 reason="memory violation" sig=6
10-10 16:04:57.579  1575  4372 I Sensors : AccelerometerSensor(0) setDelay : 200000000(ns)
```

**Comment by yenda** [comment]
First transaction with /send command crashes
Second one with `send` from wallet works

```
10-11 13:37:15.654  4216  4260 D ReactNativeJS: DEBUG [status-im.ui.screens.events:324] - :event-str {"type":"transaction.queued","event":{"id":"a4288c26-474d-4eab-971e-69da4737c869","args":{"from":"0x1b43868a6bce7779be4c75fe6d4d80ddb10a7fd0","to":"0x323a7fd769a0f106d6b41232b10c44064bb4be88","gas":null,"gasPrice":"0x14f46b0400","value":"0x16345785d8a0000","data":"0x","nonce":null},"message_id":""}}
10-11 13:37:15.655  4216  4260 D ReactNativeJS: DEBUG [status-im.utils.instabug:7] - Signal event: {"type":"transaction.queued","event":{"id":"a4288c26-474d-4eab-971e-69da4737c869","args":{"from":"0x1b43868a6bce7779be4c75fe6d4d80ddb10a7fd0","to":"0x323a7fd769a0f106d6b41232b10c44064bb4be88","gas":null,"gasPrice":"0x14f46b0400","value":"0x16345785d8a0000","data":"0x","nonce":null},"message_id":""}}


10-11 13:39:39.172  6964  7009 D ReactNativeJS: DEBUG [status-im.ui.screens.events:324] - :event-str {"type":"transaction.queued","event":{"id":"e8969b94-e34d-4c1a-a017-4a920fd78ece","args":{"from":"0x1b43868a6bce7779be4c75fe6d4d80ddb10a7fd0","to":"0x323a7fd769a0f106d6b41232b10c44064bb4be88","gas":null,"gasPrice":null,"value":"0x16345785d8a0000","data":"0x","nonce":null},"message_id":""}}
10-11 13:39:39.172  6964  7009 D ReactNativeJS: DEBUG [status-im.utils.instabug:7] - Signal event: {"type":"transaction.queued","event":{"id":"e8969b94-e34d-4c1a-a017-4a920fd78ece","args":{"from":"0x1b43868a6bce7779be4c75fe6d4d80ddb10a7fd0","to":"0x323a7fd769a0f106d6b41232b10c44064bb4be88","gas":null,"gasPrice":null,"value":"0x16345785d8a0000","data":"0x","nonce":null},"message_id":""}}
```

Seems like the problem is that /send command gives gasPrice `0x14f46b0400` when the other gives null ?

**Comment by annadanchenko** [comment]
verified ok on new build (iOs and Android) ver 0.9.11d189
