### ISSUE TITLE
Crash on login after switching network [feature/upgrade-status-go-geth17]

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#2122]
*Type*: Bug

*Summary*: Network is switched  from 
* `Ropsten upstream RPC` to `Rinkeby upstream RPC`. 
* or `Ropsten upstream RPC` to `Rinkeby`
* or `Ropsten upstream RPC` to `Ropsten`
After this user is logged out. When try to sign in then app crashes. 

Note that on develop build same steps are OK and user can log in after switching the network

### Reproduction
https://app.testfairy.com/projects/4803590-status/builds/6822087/sessions/14/?accessToken=tUJqybGvPLxp0EYc9Sby0CcPc1c
- Open Status
- Create account (by providing password)
- Open Profile, scroll to the botom
- Tap Network settings
- Tap on Ropsten
- Tap on Connect button. As a result, Sign in screen is shown
- Tap on username and provide a password
- tap Sign in -> crash.

### Additional Information
* Status version:
* Operating System: 
Real device iPhone 6s, iOs 10.3.1

**Comment by rasom** [comment]
```
10-12 12:26:10.502 11969 12009 D StatusModule: parseJail
10-12 12:26:10.509 11969     0 E Go      : panic: assignment to entry in nil map
10-12 12:26:10.509 11969     0 E Go      :
10-12 12:26:10.509 11969     0 E Go      : goroutine 228 [running, locked to thread]:
10-12 12:26:10.509 11969     0 E Go      : panic(0xd184b2e0, 0xb3203b60)
10-12 12:26:10.509 11969     0 E Go      :     /usr/local/go/src/runtime/panic.go:500 +0x384
10-12 12:26:10.509 11969     0 E Go      : github.com/status-im/status-go/geth/jail.(*Jail).NewCell(0xb0b268d0, 0xb3b79a97, 0x7, 0x0, 0x0, 0x0, 0x0)
10-12 12:26:10.509 11969     0 E Go      :     /ext-go/3/src/github.com/status-im/status-go/geth/jail/jail.go:64 +0x110
10-12 12:26:10.509 11969     0 E Go      : github.com/status-im/status-go/geth/jail.(*Jail).Parse(0xb0b268d0, 0xb3b79a97, 0x7, 0xb1ca8000, 0x11b9e, 0x0, 0x0)
10-12 12:26:10.510 11969     0 E Go      :     /ext-go/3/src/github.com/status-im/status-go/geth/jail/jail.go:103 +0xde
10-12 12:26:10.510 11969     0 E Go      : github.com/status-im/status-go/geth/api.(*StatusAPI).JailParse(0xb0b202e0, 0xb3b79a97, 0x7, 0xb1ca8000, 0x11b9e, 0x0, 0x0)
10-12 12:26:10.510 11969     0 E Go      :     /ext-go/3/src/github.com/status-im/status-go/geth/api/api.go:185 +0x5a
10-12 12:26:10.510 11969     0 E Go      : main.Parse(0x964cddb8, 0x95ca6700, 0xb3eb1f30)
10-12 12:26:10.510 11969     0 E Go      :     /ext-go/3/src/github.com/status-im/status-go/cmd/statusd/library.go:344 +0x76
10-12 12:26:10.510 11969     0 E Go      : main._cgoexpwrap_0c831d694dcc_Parse(0x964cddb8, 0x95ca6700, 0x0)
10-12 12:26:10.510 11969     0 E Go      :     github.com/status-im/status-go/cmd/statusd/_obj/_cgo_gotypes.go:416 +0x5b
```

**Comment by annadanchenko** [comment]
verified ok on develop  0.9.11d237
