### ISSUE TITLE
App crashes when granting camera with access

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#2840]
### Description

*Type*: Bug

*Summary*: App crashes when giving the camera access to scan QR code. @flexsurfer has noticed that on his `Xiaomi Redmi Note 3`. It was done when app was launched for the 1st time after install. After that it is not reproducible.

#### Expected behavior
no crashes

#### Actual behavior
`java.lang.RuntimeException: getParameters failed (empty parameters)
	at android.hardware.Camera.native_getParameters(Native Method)
	at android.hardware.Camera.getParameters(Camera.java:1984)
	at com.lwansbrough.RCTCamera.RCTCamera.adjustPreviewLayout(RCTCamera.java:396)
	at com.lwansbrough.RCTCamera.RCTCamera.setActualDeviceOrientation(RCTCamera.java:194)
	at com.lwansbrough.RCTCamera.RCTCameraView.setActualDeviceOrientation(RCTCameraView.java:130)
	at com.lwansbrough.RCTCamera.RCTCameraView.access$100(RCTCameraView.java:16)
	at com.lwansbrough.RCTCamera.RCTCameraView$1.onOrientationChanged(RCTCameraView.java:35)
	at android.view.OrientationEventListener$SensorEventListenerImpl.onSensorChanged(OrientationEventListener.java:143)
	at android.hardware.SystemSensorManager$SensorEventQueue.dispatchSensorEvent(SystemSensorManager.java:494)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:323)
	at android.os.Looper.loop(Looper.java:138)
	at android.app.ActivityThread.main(ActivityThread.java:5527)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)`

### Reproduction
- Open Status
- Give camera access to scan code

### Additional Information
* Status version: `0.9.10-481-g279ebc31+ (2038)`
* Operating System: Android, real device Xiaomi Redmi Note 3 with custom MIU 8.5.7.0

#### Logs
TF https://app.testfairy.com/projects/4803622-status/builds/7371377/sessions/72/?accessToken=IZccKNjSehx6Fw-mO9l917pNAWk

**Comment by churik** [comment]
new details - 
1) instead of QR code white screen is shown:
00:55 - 01:15: https://app.testfairy.com/projects/4803622-status/builds/7416814/sessions/55/?accessToken=Fk5c5J9iWFKGy0W1NQywpqDh9EY
2) after relaunch app camera is not working.

Scanning QR and camera start working after reset the phone.
@flexsurfer did I miss something?
