### ISSUE TITLE
java.lang.NullPointerException: Attempt to read from field 'android.animation.Animator android.animation.AnimatorSet$Node.mAnimation' when I tap on 'Requesting 0 ETH' message in group chat

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#2867]
*Type*: Bug

*Summary*: `java.lang.NullPointerException: Attempt to read from field 'android.animation.Animator android.animation.AnimatorSet$Node.mAnimation'` exception appeared after I tap on "Requesting 0 ETH" from another contact in group chat on Android 7.0 (Samsung J7 real device). 
/request message with 0 ETH was sent from iPhone X.

I can not reproduce it now, but there is a TF session with the exception details that may give a hint in what case exception followed by app crash may appear.

#### Expected behavior
"Send transaction" view appears when I tap on "Requesting 0 ETH" in group chat
#### Actual behavior
`java.lang.NullPointerException: Attempt to read from field 'android.animation.Animator android.animation.AnimatorSet$Node.mAnimation'` exception appeared when I tap on 'Requesting 0 ETH' in group chat. Application terminated and closed. 

### Reproduction
TF video with logs: https://status-im.testfairy.com/projects/4803622-status/builds/7421878/sessions/4?source=latest-sessions - from 11:00

1) Open Status on iPhone and Android devices
2) Create group chat from iPhone user with the Android user
3) iPhone user send "/request 0" message to Android user
4) Android user tap on 'Requesting 0 ETH' message

### Additional Information
* Status version: 0.910-503-g3e940b5b+ develop build
* Operating System: Android 7.0 (Samsung J7 real device)

#### Logs

```
android.content.res.Resources$NotFoundException: Drawable android:drawable/seekbar_thumb_material_anim with resource ID #0x108073c
Caused by: java.lang.NullPointerException: Attempt to read from field 'android.animation.Animator android.animation.AnimatorSet$Node.mAnimation' on a null object reference
	at android.animation.AnimatorSet.clone(AnimatorSet.java:725)
	at android.animation.AnimatorSet.clone(AnimatorSet.java:682)
	at android.animation.Animator$AnimatorConstantState.newInstance(Animator.java:589)
	at android.animation.Animator$AnimatorConstantState.newInstance(Animator.java:588)
	at android.content.res.ConstantState.newInstance(ConstantState.java:53)
	at android.content.res.ConstantState.newInstance(ConstantState.java:61)
	at android.content.res.ConfigurationBoundResourceCache.getInstance(ConfigurationBoundResourceCache.java:40)
	at android.animation.AnimatorInflater.loadAnimator(AnimatorInflater.java:114)
	at android.graphics.drawable.AnimatedVectorDrawable$AnimatedVectorDrawableState$PendingAnimator.newInstance(AnimatedVectorDrawable.java:641)
	at android.graphics.drawable.AnimatedVectorDrawable$AnimatedVectorDrawableState.inflatePendingAnimators(AnimatedVectorDrawable.java:619)
	at android.graphics.drawable.AnimatedVectorDrawable.applyTheme(AnimatedVectorDrawable.java:451)
	at android.graphics.drawable.DrawableContainer$DrawableContainerState.applyTheme(DrawableContainer.java:949)
	at android.graphics.drawable.DrawableContainer.applyTheme(DrawableContainer.java:611)
	at android.graphics.drawable.StateListDrawable.applyTheme(StateListDrawable.java:371)
	at android.graphics.drawable.AnimatedStateListDrawable.applyTheme(AnimatedStateListDrawable.java:392)
	at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:630)
	at android.content.res.Resources.loadDrawable(Resources.java:1729)
	at android.content.res.TypedArray.getDrawable(TypedArray.java:945)
	at android.widget.AbsSeekBar.(AbsSeekBar.java:214)
	at android.widget.SeekBar.(SeekBar.java:85)
	at android.widget.SeekBar.(SeekBar.java:81)
	at com.facebook.react.views.slider.ReactSlider.(ReactSlider.java:56)
	at com.facebook.react.views.slider.ReactSliderManager$ReactSliderShadowNode.measure(ReactSliderManager.java:64)
	at com.facebook.yoga.YogaNode.measure(YogaNode.java:634)
	at com.facebook.yoga.YogaNode.jni_YGNodeCalculateLayout(Native Method)
	at com.facebook.yoga.YogaNode.calculateLayout(YogaNode.java:184)
	at com.facebook.react.uimanager.ReactShadowNodeImpl.calculateLayout(ReactShadowNodeImpl.java:415)
	at com.facebook.react.uimanager.UIImplementation.calculateRootLayout(UIImplementation.java:928)
	at com.facebook.react.uimanager.UIImplementation.updateViewHierarchy(UIImplementation.java:684)
	at com.facebook.react.uimanager.UIImplementation.dispatchViewUpdates(UIImplementation.java:644)
	at com.facebook.react.uimanager.UIManagerModule.onBatchComplete(UIManagerModule.java:657)
	at com.facebook.react.bridge.NativeModuleRegistry.onBatchComplete(NativeModuleRegistry.java:136)
	at com.facebook.react.bridge.CatalystInstanceImpl$BridgeCallback.onBatchComplete(CatalystInstanceImpl.java:149)
	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
	at android.os.Looper.loop(Looper.java:154)
	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194)
	at java.lang.Thread.run(Thread.java:762)
```

**Comment by Serhy** [comment]
Could not reproduce it.
Closing this issue.
