### ISSUE TITLE
java.lang.RuntimeException: Could not invoke Status.sendWeb3Request app crash after log in with deleted 1-1 chat (100+ messages) (Android)

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#3189]
***Type***: Bug

***Summary***: App crashes after 1 minute log in into account where deleted 1-1 chat (with 150 messages) and group chat (with 50 messages) were present before re-login.
Happens on Android.
I could not reproduce it on iPhoneX with the same dataset. 

#### Expected behavior
No crash after log in to account and stay on Home screen for 1-2 minutes if there were deleted chats (with 100+ messages) prior login.
#### Actual behavior
No crash after log in to account and stay on Home screen for 1-2 minutes if there were deleted chats (with 100+ messages) prior login.

### Precondition
1-1 chat with ~100+ messages exist

### Reproduction

- Open Status
- Delete 1-1 chat with 100+ messages
- Close the app
- Open Status 
- Stay on Home screen for 1-2 minutes

### Additional Information
* Status version:  0.9.10-621-g8f1bc58b+ (0.9.11d621) 
* Operating System: Android 7.0 (Samsung J7 real device)

TF sessions with the crash:
https://app.testfairy.com/projects/4803622-status/builds/7599983/sessions/27/?accessToken=Z5GGGnOzl6DOsteVyfQ6qXaF1xk (from 04:30)
https://app.testfairy.com/projects/4803622-status/builds/7599983/sessions/28/?accessToken=DdF2SzoC9FtDBn5qSNphrNVxtOw (from 01:00)
https://app.testfairy.com/projects/4803622-status/builds/7599983/sessions/29/?accessToken=wQOC72bsXeppLrHC9eVo-yathFk (from 00:20)

See there each time CPU performance spikes out before app crashed. 

#### Logs

```
java.lang.RuntimeException: Could not invoke Status.sendWeb3Request
	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:385)
	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:162)
	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
	at android.os.Looper.loop(Looper.java:154)
	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194)
	at java.lang.Thread.run(Thread.java:762)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:374)
	... 8 more
Caused by: java.lang.OutOfMemoryError: pthread_create (1040KB stack) failed: Try again
	at java.lang.Thread.nativeCreate(Native Method)
	at java.lang.Thread.start(Thread.java:731)
	at im.status.ethereum.module.StatusModule.sendWeb3Request(StatusModule.java:676)
	... 10 more
```

**Comment by Serhy** [comment]
Rechecked above scenario with the chat with 300+ messages on latest develop (282th) and it's all fine! Can't reproduce anymore. Closing this issue.
