### ISSUE TITLE
App crushes while taking a photo for profile

### ISSUE THREAD

**Issue by JekaMas** [status-im/status-react#3274]
[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

#### Description
[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)

When I try to change profile photo making new one by camera the application crushes with error.

#### Steps to reproduce

- Open Status
- Open a profile
- Tap on 'edit'
- Tap on a photo
- Select 'take a picture'
- Get an error

[comment]: # (Android or iOS.)
Operating System: Android 6.0.1 MMB29M

#### Logs

[comment]: # (if on Android please replicate bug whilst running adb logcat)
Error message
```
com.facebook.react.bridge.UnexpectedNativeTypeException: TypeError: expected dynamic type 'double', but had type 'null'
    at com.facebook.react.bridge.ReadableNativeMap.getInt(Native Method)
    at com.lwansbrough.RCTCamera.RCTCameraModule.processImage(RCTCameraModule.java:585)
    at com.lwansbrough.RCTCamera.RCTCameraModule.access$200(RCTCameraModule.java:38)
    at com.lwansbrough.RCTCamera.RCTCameraModule$3$1.run(RCTCameraModule.java:539)
    at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
    at java.lang.Thread.run(Thread.java:818)
```
![screenshot_2018-02-09-13-44-41-902_im status ethereum](https://user-images.githubusercontent.com/3192700/36025669-e4626d14-0da4-11e8-99e6-5959854ebcb6.png)

**Comment by annadanchenko** [comment]
duplicate #3232
