### ISSUE TITLE
App crashes while creating new account in custom network

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-react#4354]
Create account A
create custom network
switch to the custom network
logout
Create account B
Crash

Expected behaviour
New account should be created in default - mainnet network

`0   StatusIm                            0x0000000104b8e9c8 0x104084000 + 11577800
1   StatusIm                            0x0000000104b93394 0x104084000 + 11596692
2   StatusIm                            0x0000000104ba6170 0x104084000 + 11673968
3   libsystem_pthread.dylib             0x00000001814f9220 0x1814f7000 + 8736
4   libsystem_pthread.dylib             0x00000001814f9110 0x1814f7000 + 8464
5   libsystem_pthread.dylib             0x00000001814f7b10 0x1814f7000 + 2832`

 TF: https://app.testfairy.com/projects/4803590-status/builds/8336923/sessions/18/?accessToken=-bSMc-wB8K1ePQMZYDGAnwiIkrQ

**Comment by asemiankevich** [comment]
is this https://github.com/status-im/status-react/issues/3981 @flexsurfer ?

**Comment by flexsurfer** [comment]
@asemiankevich no, a different one, here it crashes because we're trying to use custom network, but it available only for account who created it

**Comment by lukaszfryc** [comment]
Can you log in to the account when you open the app again?

**Comment by flexsurfer** [comment]
no, it crashes if i try to sign in

**Comment by lukaszfryc** [comment]
I've just experienced a crash when logging in to a custom network. Steps I did: 
1. I created custom network on mainnet
2. I switched to the network and was logged out
3. The app crashed while I was trying to log in again

I can't replicate it now.

Notes:
- Galaxy S8, Android 7.1
- e9fcba0, nightly 13
- Crash log
```
07-13 04:26:17.702  3752 27309 E InputMethodManagerService: Perflock object null
07-13 04:26:17.716 13800 13800 E SKBD    : aeo getInstance start
07-13 04:26:17.716 13800 13800 E SKBD    : aeo sendSIPInformation state: 6   isAbstractKeyboardView :  true
07-13 04:26:17.722 13800  3444 E SKBD    : aeo sending null keyboardInfo as SIP is closed
07-13 04:26:17.985 30181     0 E Go      : panic: runtime error: invalid memory address or nil pointer dereference
07-13 04:26:17.985 30181     0 E Go      : [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xc49c5b70]
07-13 04:26:17.985 30181     0 E Go      :
07-13 04:26:17.985 30181     0 E Go      : goroutine 51 [running, locked to thread]:
07-13 04:26:17.987 30181     0 E Go      : github.com/status-im/status-go/rpc.(*Client).handler(0x0, 0x901da000, 0x1b, 0x0, 0x0)
07-13 04:26:17.987 30181     0 E Go      : 	/ext-go/1/src/github.com/status-im/status-go/rpc/client.go:147 +0x24
07-13 04:26:17.987 30181     0 E Go      : github.com/status-im/status-go/rpc.(*Client).CallContext(0x0, 0xc53766b8, 0x8e67a010, 0xc52b9320, 0x8feb2100, 0x901da000, 0x1b, 0x8e674360, 0x1, 0x4, ...)
07-13 04:26:17.987 30181     0 E Go      : 	/ext-go/1/src/github.com/status-im/status-go/rpc/client.go:93 +0x2c
07-13 04:26:17.987 30181     0 E Go      : github.com/status-im/status-go/rpc.(*Client).callSingleMethod(0x0, 0xc53766b8, 0x8e67a010, 0x8f1c03c0, 0x91, 0xa0, 0x0, 0x0)
07-13 04:26:17.987 30181     0 E Go      : 	/ext-go/1/src/github.com/status-im/status-go/rpc/call_raw.go:120 +0xe8
07-13 04:26:17.988 30181     0 E Go      : github.com/status-im/status-go/rpc.(*Client).callBatchMethods(0x0, 0xc53766b8, 0x8e67a010, 0x8f1c00a0, 0x93, 0xa0, 0xa0, 0x8f1c00a0)
07-13 04:26:17.988 30181     0 E Go      : 	/ext-go/1/src/github.com/status-im/status-go/rpc/call_raw.go:97 +0x128
07-13 04:26:17.988 30181     0 E Go      : github.com/status-im/status-go/rpc.(*Client).callRawContext(0x0, 0xc53766b8, 0x8e67a010, 0x8f1c00a0, 0x93, 0xa0, 0x8ebb54c0, 0xc536de00)
07-13 04:26:17.988 30181     0 E Go      : 	/ext-go/1/src/github.com/status-im/status-go/rpc/call_raw.go:71 +0x6c
07-13 04:26:17.988 30181     0 E Go      : github.com/status-im/status-go/rpc.(*Client).CallRaw(0x0, 0x8f1c0000, 0x93, 0x93, 0x93)
07-13 04:26:17.988 30181     0 E Go      : 	/ext-go/1/src/github.com/status-im/status-go/rpc/call_raw.go:27 +0x5c
07-13 04:26:17.988 30181     0 E Go      : github.com/status-im/status-go/api.(*StatusBackend).CallRPC(0x8ebb5500, 0x8f1c0000, 0x93, 0x8f1c0000, 0x93)
07-13 04:26:17.988 30181     0 E Go      : 	/ext-go/1/src/github.com/status-im/status-go/api/backend.go:225 +0x3c
07-13 04:26:17.988 30181     0 E Go      : github.com/status-im/status-go/api.(*StatusAPI).CallRPC(0x8e5f6900, 0x8f1c0000, 0x93, 0x8e825f58, 0xc4226b68)
07-13 04:26:17.988 30181     0 E Go      : 	/ext-go/1/src/github.com/status-im/status-go/api/api.go:108 +0x30
07-13 04:26:17.988 30181     0 E Go      : main.CallRPC(0x63805a80, 0xc536d8b8)
07-13 04:26:17.988 30181     0 E Go      : 	/ext-go/1/src/github.com/status-im/status-go/lib/library.go:114 +0x30
07-13 04:26:17.989 30181     0 E Go      : main._cgoexpwrap_a7bccece0b5a_CallRPC(0x63805a80, 0x0)
07-13 04:26:17.989 30181     0 E Go      : 	_cgo_gotypes.go:149 +0x4c
07-13 04:26:18.330  3448 30306 F google-breakpad: Microdump skipped (uninteresting)
07-13 04:26:18.374 30181 30306 F libc    : Fatal signal 6 (SIGABRT), code -6 in tid 30306 (pool-8-thread-2)
07-13 04:26:19.215  3450  3450 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
07-13 04:26:19.215  3450  3450 F DEBUG   : Build fingerprint: 'samsung/dreamltexx/dreamlte:7.0/NRD90M/G950FXXU1AQK7:user/release-keys'
07-13 04:26:19.215  3450  3450 F DEBUG   : Revision: '10'
07-13 04:26:19.215  3450  3450 F DEBUG   : ABI: 'arm'
07-13 04:26:19.216  3450  3450 F DEBUG   : pid: 30181, tid: 30306, name: pool-8-thread-2  >>> im.status.ethereum <<<
07-13 04:26:19.216  3450  3450 F DEBUG   : signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
07-13 04:26:19.216  3450  3450 F DEBUG   :     r0 00000000  r1 00000006  r2 c5877c50  r3 00000000
07-13 04:26:19.216  3450  3450 F DEBUG   :     r4 00000001  r5 00000000  r6 00000000  r7 000000ee
07-13 04:26:19.216  3450  3450 F DEBUG   :     r8 00000000  r9 00000000  sl 8eaba460  fp 00000001
07-13 04:26:19.216  3450  3450 F DEBUG   :     ip 00000000  sp bc9292bc  lr c426e704  pc c42872a8  cpsr 20070010
07-13 04:26:19.220  3450  3450 F DEBUG   :
07-13 04:26:19.220  3450  3450 F DEBUG   : backtrace:
07-13 04:26:19.220  3450  3450 F DEBUG   :     #00 pc 001e92a8  /data/app/im.status.ethereum-2/lib/arm/libstatusgoraw.so
07-13 04:26:19.220  3450  3450 F DEBUG   :     #01 pc 001d0700  /data/app/im.status.ethereum-2/lib/arm/libstatusgoraw.so
07-13 04:26:23.204  3752  4459 E Watchdog: !@Sync 22389 [2018-07-13 14:26:23.204]
```
