### ISSUE TITLE
App crash with "Could not invoke Status.callPrivateRPC" error for accounts with 1000+ transactions

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#5884]
***Type***: Bug

***Summary***: Depending on the number of transactions contact has, - navigation between screens becomes too laggy which eventually ends up with the `Could not invoke Status.callPrivateRPC` error followed by app crash. 
Lags (app freezes) especially seen for such accounts after any tranaction has sent (e.g. in Dapp), or when navigating to/back Transaction history screen. 

#### Expected behavior
No app crashes for accounts with address having 1000+ transactions.

#### Actual behavior
App crash with "Could not invoke Status.callPrivateRPC" error for accounts with 1000+ transactions
<img width="369" alt="screen shot 2018-09-18 at 15 40 02" src="https://user-images.githubusercontent.com/8749671/45688094-24e0dd00-bb59-11e8-8f7d-2c445eaf273c.png">

### Reproduction

- Open Status
- Recover an account (you can use this one: `shrug dring breeze marcy install net reopen uniform atom guilt sadness elite` - it has 1200+ txs)
- Change network to `Ropsten RPC`
- Navigate to Wallet and complete Wallet set up
- Navigate to Simple Test Dapp. Request STT.
- Once transaction signed in Dapp successfully, navigate between different screens (Home <-> Wallet <-> Profile). Note how much time it takes for respective screen to appear after tap (in my case Samsung Galaxy J7 (Android 7) it's up to 10 seconds (sometimes more) 
- Join any public chat (e.g. `#status`)
- Navigate between Wallet modal and transaction history screen

### Additional Information
* Status version: Develop (8468); node 0.14.1
* Operating System: Android, iOS
### Additional Information 2
This error did not appear in `Release 0.9.27 (node 0.13)`, however the app crached in this version for me as well (crahses not so often as on current develop and just **without errors** on crash)
. 
#### Logs

Here is three TF session where this issue occurred: 
https://app.testfairy.com/projects/4803622-status/builds/8594431/sessions/4401694838/?accessToken=wcQYg5VqXQlXjwZlZea-I0qZB7c
https://app.testfairy.com/projects/4803622-status/builds/8594431/sessions/4401693728/?accessToken=9Ab4zN95dqtpQH5auyGN5s4Bubo
https://app.testfairy.com/projects/4803622-status/builds/8596291/sessions/4401743483/?accessToken=QGLfkD0obW0EUZoLdfsoA6gllVQ

```java.lang.RuntimeException: Could not invoke Status.callPrivateRPC
	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:383)
	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:160)
	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
	at android.os.Looper.loop(Looper.java:154)
	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192)
	at java.lang.Thread.run(Thread.java:762)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
	... 8 more
Caused by: java.lang.OutOfMemoryError: pthread_create (1040KB stack) failed: Try again
	at java.lang.Thread.nativeCreate(Native Method)
	at java.lang.Thread.start(Thread.java:731)
	at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:941)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1348)
	at im.status.ethereum.module.StatusThreadPoolExecutor.execute(StatusThreadPoolExecutor.java:42)
	at im.status.ethereum.module.StatusModule.callPrivateRPC(StatusModule.java:689)
	... 10 more```

<blockquote><div><strong><a href="https://app.testfairy.com/projects/4803622-status/builds/8594431/sessions/4401694838/?accessToken=wcQYg5VqXQlXjwZlZea-I0qZB7c">TestFairy: Status 0.9.28 (8352) @2018</a></strong></div></blockquote>
<blockquote><div><strong><a href="https://app.testfairy.com/projects/4803622-status/builds/8594431/sessions/4401693728/?accessToken=9Ab4zN95dqtpQH5auyGN5s4Bubo">TestFairy: Status 0.9.28 (8352) @2018</a></strong></div></blockquote>
<blockquote><div><strong><a href="https://app.testfairy.com/projects/4803622-status/builds/8596291/sessions/4401743483/?accessToken=QGLfkD0obW0EUZoLdfsoA6gllVQ">TestFairy: Status 0.9.28 (8468) @2018</a></strong></div></blockquote>

**Comment by Serhy** [comment]
Here is a geth.log (with log level = `trace`) for this TF session: https://app.testfairy.com/projects/4803622-status/builds/8596291/sessions/4401766018/?accessToken=91sqiZW9F6eDzIPA3hizLRlLOCQ when `Could not invoke Status.callPrivateRPC` crashed the app. I didn't have a pop-up with error like in description but app just become completly unresponsive for 1m so I had to stop it. 

[gethlog_when_app_become_completly_unresponsive.log](https://github.com/status-im/status-react/files/2393268/gethlog.log)

Above log is ~8MB. But when I was trying to reproduce the issue, I had the cases when geth log were up to 500MB for 6-7 minute of nevigation between screens, pull-to-refresh on wallet transaction history, etc.


<blockquote><div><strong><a href="https://app.testfairy.com/projects/4803622-status/builds/8596291/sessions/4401766018/?accessToken=91sqiZW9F6eDzIPA3hizLRlLOCQ">TestFairy: Status 0.9.28 (8468) @2018</a></strong></div></blockquote>
