### ISSUE TITLE
Phone crash during sync

### ISSUE THREAD

**Issue by jarradh** [status-im/status-react#642]
@vol_har:

I installed the app this afternoon (12 hours ago) on my Samsung Galaxy s7 (Android 6.0.1), but didn't open/use it. When I restarted my phone for some reason, it kept on rebooting or freezing on the start/lockscreen. Once I did a soft reset (or what it's called: power+volume down) all problems were gone.  

I thought nothing of it and went on with my day. An hour ago I wanted to test the app. When I received my backup word sequence it froze and after a couple of seconds the phone restarted and again couldn't stop restarting. Every once in a while it made it to the startscreen, but if it did it froze and restarted again after a couple of seconds. Sometimes the screen was touchable but turned vague when I did touch it and then went into the restart loop again.  

While this was happening (30 minutes or so, you can't eject the battery on this phone) the phone got extremely hot. It was not until I cooled the phone with some ice packs for 10 minutes that I managed to kill the loop after some attempts.  

I immediately removed the app afterwards and it looks like it didn't do any damage (too soon to tell). Of course I cant tell for sure, but I'm almost certain it's the status app that caused it. My phone is only a couple months old, never shows any problems (freezing, getting hot etc) and I didn't install any other apps recently.  

Is this a familiar problem? Would love to hear from you, cause the app (in the video) looked great.

This may be because there is not enough disk space but geth continues to write files?

![screenshot_20170106-064714_720](https://cloud.githubusercontent.com/assets/2714786/21708916/6f58b8c2-d40f-11e6-9fba-9f16b58352e7.png)

**Comment by jarradh** [comment]
We also need `status-go` to report errors from failing to access internal storage, as it results in this.
An error found by vivek

```
1-06 20:53:13.340  6859     0 E Go      : panic: error starting p2p node: open /storage/emulated/0/ethereum/testnet/StatusIM/LOCK: permission denied
01-06 20:53:13.340  6859     0 E Go      : 
01-06 20:53:13.340  6859     0 E Go      : goroutine 51 [running]:
01-06 20:53:13.340  6859     0 E Go      : panic(0x94a71d70, 0x50b84838)
01-06 20:53:13.340  6859     0 E Go      :     /usr/local/go/src/runtime/panic.go:500 +0x37c
01-06 20:53:13.340  6859     0 E Go      : github.com/status-im/status-go/geth.(*NodeManager).StartNode(0x50c02900)
01-06 20:53:13.340  6859     0 E Go      :     /ext-go/3/src/github.com/status-im/status-go/geth/node_manager.go:152 +0x1a8
01-06 20:53:13.340  6859     0 E Go      : github.com/status-im/status-go/geth.(*NodeManager).RunNode.func1(0x50c02900)
01-06 20:53:13.340  6859     0 E Go      :     /ext-go/3/src/github.com/status-im/status-go/geth/node_manager.go:108 +0x38
01-06 20:53:13.340  6859     0 E Go      : created by github.com/status-im/status-go/geth.(*NodeManager).RunNode
01-06 20:53:13.340  6859     0 E Go      :     /ext-go/3/src/github.com/status-im/status-go/geth/node_manager.go:142 +0x30
01-06 20:53:27.072   621   621 E cnss-daemon: Stale or unreachable neighbors, ndm state: 4
```

![screenshot_1483702630](https://cloud.githubusercontent.com/assets/2714786/21723713/11a209b8-d464-11e6-987e-189d6d75be2f.png)

This is also similar to #652
