### ISSUE TITLE
Unhandled Error with camera leads to broken QR Screen

### ISSUE THREAD

**Issue by jarradh** [status-im/status-react#646]
![548ea6c99109f834c99ebd400d334207_original](https://cloud.githubusercontent.com/assets/2714786/21711395/5b0a43c4-d421-11e6-9608-b7e43ea59bb9.jpg)

https://instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/117

```
--------- beginning of crash
01-06 02:22:35.473 E/AndroidRuntime(10115): FATAL EXCEPTION: mqt_native_modules
01-06 02:22:35.473 E/AndroidRuntime(10115): Process: im.status.ethereum, PID: 10115
01-06 02:22:35.473 E/AndroidRuntime(10115): com.facebook.react.common.JavascriptException: No item 0 in vector of length 0, stack:
01-06 02:22:35.473 E/AndroidRuntime(10115): jt@12:30293
01-06 02:22:35.473 E/AndroidRuntime(10115): St@12:30530
01-06 02:22:35.473 E/AndroidRuntime(10115): M@28:18100
01-06 02:22:35.473 E/AndroidRuntime(10115): hl@12:11516
01-06 02:22:35.473 E/AndroidRuntime(10115): <unknown>@42:29583
01-06 02:22:35.473 E/AndroidRuntime(10115): ga@13:22376
01-06 02:22:35.473 E/AndroidRuntime(10115): ya@13:22445
01-06 02:22:35.473 E/AndroidRuntime(10115): qa@13:24423
01-06 02:22:35.473 E/AndroidRuntime(10115): xa@13:23832
01-06 02:22:35.473 E/AndroidRuntime(10115): <unknown>@13:21831
01-06 02:22:35.473 E/AndroidRuntime(10115): <unknown>@68:549
01-06 02:22:35.473 E/AndroidRuntime(10115): callTimer@63:626
01-06 02:22:35.473 E/AndroidRuntime(10115): callTimers@63:1031
01-06 02:22:35.473 E/AndroidRuntime(10115): value@61:2818
01-06 02:22:35.473 E/AndroidRuntime(10115): <unknown>@61:1053
01-06 02:22:35.473 E/AndroidRuntime(10115): d@61:127
01-06 02:22:35.473 E/AndroidRuntime(10115): value@61:1025
01-06 02:22:35.473 E/AndroidRuntime(10115): 
01-06 02:22:35.473 E/AndroidRuntime(10115): 	at com.facebook.react.modules.core.ExceptionsManagerModule.showOrThrowError(ExceptionsManagerModule.java:97)
01-06 02:22:35.473 E/AndroidRuntime(10115): 	at com.facebook.react.modules.core.ExceptionsManagerModule.reportFatalException(ExceptionsManagerModule.java:81)
01-06 02:22:35.473 E/AndroidRuntime(10115): 	at java.lang.reflect.Method.invoke(Native Method)
01-06 02:22:35.473 E/AndroidRuntime(10115): 	at java.lang.reflect.Method.invoke(Method.java:372)
01-06 02:22:35.473 E/AndroidRuntime(10115): 	at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:318)
01-06 02:22:35.473 E/AndroidRuntime(10115): 	at com.facebook.react.cxxbridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
01-06 02:22:35.473 E/AndroidRuntime(10115): 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
01-06 02:22:35.473 E/AndroidRuntime(10115): 	at android.os.Handler.handleCallback(Handler.java:739)
01-06 02:22:35.473 E/AndroidRuntime(10115): 	at android.os.Handler.dispatchMessage(Handler.java:95)
01-06 02:22:35.473 E/AndroidRuntime(10115): 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
01-06 02:22:35.473 E/AndroidRuntime(10115): 	at android.os.Looper.loop(Looper.java:135)
01-06 02:22:35.473 E/AndroidRuntime(10115): 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
01-06 02:22:35.473 E/AndroidRuntime(10115): 	at java.lang.Thread.run(Thread.java:818)
01-06 14:54:59.614 E/AndroidRuntime(24522): FATAL EXCEPTION: AsyncTask #1
01-06 14:54:59.614 E/AndroidRuntime(24522): Process: im.status.ethereum, PID: 24522
01-06 14:54:59.614 E/AndroidRuntime(24522): java.lang.RuntimeException: An error occured while executing doInBackground()
01-06 14:54:59.614 E/AndroidRuntime(24522): 	at android.os.AsyncTask$3.done(AsyncTask.java:304)
01-06 14:54:59.614 E/AndroidRuntime(24522): 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
01-06 14:54:59.614 E/AndroidRuntime(24522): 	at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
01-06 14:54:59.614 E/AndroidRuntime(24522): 	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
01-06 14:54:59.614 E/AndroidRuntime(24522): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
01-06 14:54:59.614 E/AndroidRuntime(24522): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
01-06 14:54:59.614 E/AndroidRuntime(24522): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
01-06 14:54:59.614 E/AndroidRuntime(24522): 	at java.lang.Thread.run(Thread.java:818)
01-06 14:54:59.614 E/AndroidRuntime(24522): Caused by: java.lang.RuntimeException: getParameters failed (empty parameters)
01-06 14:54:59.614 E/AndroidRuntime(24522): 	at android.hardware.Camera.native_getParameters(Native Method)
01-06 14:54:59.614 E/AndroidRuntime(24522): 	at android.hardware.Camera.getParameters(Camera.java:2027)
01-06 14:54:59.614 E/AndroidRuntime(24522): 	at com.lwansbrough.RCTCamera.RCTCameraViewFinder$ReaderAsyncTask.doInBackground(RCTCameraViewFinder.java:282)
01-06 14:54:59.614 E/AndroidRuntime(24522): 	at com.lwansbrough.RCTCamera.RCTCameraViewFinder$ReaderAsyncTask.doInBackground(RCTCameraViewFinder.java:267)
01-06 14:54:59.614 E/AndroidRuntime(24522): 	at android.os.AsyncTask$2.call(AsyncTask.java:292)
01-06 14:54:59.614 E/AndroidRuntime(24522): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
01-06 14:54:59.614 E/AndroidRuntime(24522): 	... 4 more
--------- beginning of main
```

**Comment by jarradh** [comment]
https://instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/99

**Comment by jarradh** [comment]
possible duplicate of #148

**Comment by goranjovic** [comment]
[camera-error.log](https://github.com/status-im/status-react/files/1406240/camera-error.log)

**Comment by goranjovic** [comment]
^ Reproduced on Sony Ericsson Xperia Z5 - 'E6633 - 5.1.1' 
App tried after a fresh restart. No app used camera before in this boot.
