### ISSUE TITLE
Crash: RuntimeException: Unable to start activity - attempt to invoke virtual method 'int com.instabug.library.settings.a.m()' on a null object reference

### ISSUE THREAD

**Issue by ligi** [status-im/status-react#6524]
### User Story

In the context of preparing for the status hackathon I gave the app another spin. Worked at first - but got a crash later in the process when opening the app.
Unfortunately I could not yet reproduce - but I think the stacktrace (see bottom) could be useful for you.

### Additional Information

* Status version: 0.9.29 (9839) node:0.15.0 ( afaik currently the latest on google play)
* Operating System: Android 8.1.0

#### Logs

```
10-24 20:20:29.151 10426 10426 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{im.status.ethereum/com.instabug.library.invocation.invocationdialog.InstabugDialogActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'int com.instabug.library.settings.a.m()' on a null object reference
10-24 20:20:29.151 10426 10426 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2778)
10-24 20:20:29.151 10426 10426 E AndroidRuntime:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
10-24 20:20:29.151 10426 10426 E AndroidRuntime:        at android.app.ActivityThread.-wrap11(Unknown Source:0)
10-24 20:20:29.151 10426 10426 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
10-24 20:20:29.151 10426 10426 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
10-24 20:20:29.151 10426 10426 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:164)
10-24 20:20:29.151 10426 10426 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6501)
10-24 20:20:29.151 10426 10426 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
10-24 20:20:29.151 10426 10426 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
10-24 20:20:29.151 10426 10426 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
10-24 20:20:29.151 10426 10426 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int com.instabug.library.setti\
ngs.a.m()' on a null object reference
10-24 20:20:29.151 10426 10426 E AndroidRuntime:        at com.instabug.library.settings.SettingsManager.getStatusBarColor(SettingsManager.java:372)
10-24 20:20:29.151 10426 10426 E AndroidRuntime:        at com.instabug.library.util.StatusBarUtils.setStatusBar(StatusBarUtils.java:23)
10-24 20:20:29.151 10426 10426 E AndroidRuntime:        at com.instabug.library.core.ui.BaseFragmentActivity.onCreate(BaseFragmentActivity.java:31)
10-24 20:20:29.151 10426 10426 E AndroidRuntime:        at com.instabug.library.invocation.invocationdialog.InstabugDialogActivity.onCreate(InstabugDialogAc\
tivity.java:53)
10-24 20:20:29.151 10426 10426 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:7009)
10-24 20:20:29.151 10426 10426 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:7000)
10-24 20:20:29.151 10426 10426 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1215)
10-24 20:20:29.151 10426 10426 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
10-24 20:20:29.151 10426 10426 E AndroidRuntime:        ... 9 more
10-24 20:20:29.153 10426 10443 I FA      : Collection disabled with firebase_analytics_collection_deactivated=1
10-24 20:20:29.154 10426 10443 I FA      : App measurement is starting up, version: 13001
10-24 20:20:29.154 10426 10443 I FA      : To enable debug logging run: adb shell setprop log.tag.FA VERBOSE
10-24 20:20:29.154 10426 10443 I FA      : To enable faster debug mode event logging run:
10-24 20:20:29.154 10426 10443 I FA      :   adb shell setprop debug.firebase.analytics.app im.status.ethereum
10-24 20:20:29.160  1402  5993 W ActivityManager:   Force finishing activity im.status.ethereum/com.instabug.library.invocation.invocationdialog.InstabugDia\
logActivity

```

**Comment by asemiankevich** [comment]
@ligi thansk for the report! This should gone in 0.9.30 release that is out now : )

**Comment by ligi** [comment]
Thanks for the fix!

**Comment by ghost** [comment]
This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. Thank you for your contributions.

**Comment by ghost** [comment]
This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. Thank you for your contributions.

**Comment by mandrigin** [comment]
we don't have instabug anymore
