### ISSUE TITLE
QR code not scanning

### ISSUE THREAD

**Issue by Jas0n-F** [status-im/status-react#730]
Android user reporting QR reader not scanning even when in focus.

https://instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/165?status=New

```--------- beginning of crash
01-05 11:13:35.854 E/AndroidRuntime(25398): FATAL EXCEPTION: main
01-05 11:13:35.854 E/AndroidRuntime(25398): Process: im.status.ethereum, PID: 25398
01-05 11:13:35.854 E/AndroidRuntime(25398): Theme: themes:{com.cyanogenmod.trebuchet=overlay:system, default=overlay:system, iconPack:com.numix.icons_fold, fontPkg:system, com.android.systemui=overlay:system, com.android.systemui.navbar=overlay:system}
01-05 11:13:35.854 E/AndroidRuntime(25398): java.lang.RuntimeException: Unable to start activity ComponentInfo{im.status.ethereum/com.instabug.library.InstabugFeedbackActivity}: java.lang.IllegalArgumentException
01-05 11:13:35.854 E/AndroidRuntime(25398): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2450)
01-05 11:13:35.854 E/AndroidRuntime(25398): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2510)
01-05 11:13:35.854 E/AndroidRuntime(25398): 	at android.app.ActivityThread.-wrap11(ActivityThread.java)
01-05 11:13:35.854 E/AndroidRuntime(25398): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1363)
01-05 11:13:35.854 E/AndroidRuntime(25398): 	at android.os.Handler.dispatchMessage(Handler.java:102)
01-05 11:13:35.854 E/AndroidRuntime(25398): 	at android.os.Looper.loop(Looper.java:148)
01-05 11:13:35.854 E/AndroidRuntime(25398): 	at android.app.ActivityThread.main(ActivityThread.java:5461)
01-05 11:13:35.854 E/AndroidRuntime(25398): 	at java.lang.reflect.Method.invoke(Native Method)
01-05 11:13:35.854 E/AndroidRuntime(25398): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
01-05 11:13:35.854 E/AndroidRuntime(25398): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
01-05 11:13:35.854 E/AndroidRuntime(25398): Caused by: java.lang.IllegalArgumentException
01-05 11:13:35.854 E/AndroidRuntime(25398): 	at android.media.MediaMetadataRetriever.setDataSource(MediaMetadataRetriever.java:71)
01-05 11:13:35.854 E/AndroidRuntime(25398): 	at com.instabug.library.util.s.a(VideoManipulationUtils.java:20)
01-05 11:13:35.854 E/AndroidRuntime(25398): 	at com.instabug.library.util.s.a(VideoManipulationUtils.java:32)
01-05 11:13:35.854 E/AndroidRuntime(25398): 	at com.instabug.library.e.b.b(FeedbackFragment.java:692)
01-05 11:13:35.854 E/AndroidRuntime(25398): 	at com.instabug.library.e.b.a(FeedbackFragment.java:505)
01-05 11:13:35.854 E/AndroidRuntime(25398): 	at com.instabug.library.e.c.a(FeedbackPresenter.java:178)
01-05 11:13:35.854 E/AndroidRuntime(25398): 	at com.instabug.library.e.b.onStart(FeedbackFragment.java:269)
01-05 11:13:35.854 E/AndroidRuntime(25398): 	at android.support.v4.app.Fragment.performStart(Fragment.java:2106)
01-05 11:13:35.854 E/AndroidRuntime(25398): 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1146)
01-05 11:13:35.854 E/AndroidRuntime(25398): 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1290)
01-05 11:13:35.854 E/AndroidRuntime(25398): 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1272)
01-05 11:13:35.854 E/AndroidRuntime(25398): 	at android.support.v4.app.FragmentManagerImpl.dispatchStart(FragmentManager.java:2154)
01-05 11:13:35.854 E/AndroidRuntime(25398): 	at android.support.v4.app.FragmentController.dispatchStart(FragmentController.java:212)
01-05 11:13:35.854 E/AndroidRuntime(25398): 	at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:610)
01-05 11:13:35.854 E/AndroidRuntime(25398): 	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1238)
01-05 11:13:35.854 E/AndroidRuntime(25398): 	at android.app.Activity.performStart(Activity.java:6268)
01-05 11:13:35.854 E/AndroidRuntime(25398): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2413)
01-05 11:13:35.854 E/AndroidRuntime(25398): 	... 9 more
01-07 14:40:44.078 E/AndroidRuntime(10498): FATAL EXCEPTION: mqt_native_modules
01-07 14:40:44.078 E/AndroidRuntime(10498): Process: im.status.ethereum, PID: 10498
01-07 14:40:44.078 E/AndroidRuntime(10498): Theme: themes:{com.cyanogenmod.trebuchet=overlay:system, default=overlay:system, iconPack:com.numix.icons_fold, fontPkg:system, com.android.systemui=overlay:system, com.android.systemui.navbar=overlay:system}
01-07 14:40:44.078 E/AndroidRuntime(10498): com.facebook.react.bridge.NativeArgumentsParseException: TypeError: expected dynamic type `string', but had type `int64' (constructing arguments for Status.completeTransaction at argument index 1)
01-07 14:40:44.078 E/AndroidRuntime(10498): 	at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:312)
01-07 14:40:44.078 E/AndroidRuntime(10498): 	at com.facebook.react.cxxbridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
01-07 14:40:44.078 E/AndroidRuntime(10498): 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
01-07 14:40:44.078 E/AndroidRuntime(10498): 	at android.os.Handler.handleCallback(Handler.java:739)
01-07 14:40:44.078 E/AndroidRuntime(10498): 	at android.os.Handler.dispatchMessage(Handler.java:95)
01-07 14:40:44.078 E/AndroidRuntime(10498): 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
01-07 14:40:44.078 E/AndroidRuntime(10498): 	at android.os.Looper.loop(Looper.java:148)
01-07 14:40:44.078 E/AndroidRuntime(10498): 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
01-07 14:40:44.078 E/AndroidRuntime(10498): 	at java.lang.Thread.run(Thread.java:818)
01-07 14:40:44.078 E/AndroidRuntime(10498): Caused by: com.facebook.react.bridge.UnexpectedNativeTypeException: TypeError: expected dynamic type `string', but had type `int64'
01-07 14:40:44.078 E/AndroidRuntime(10498): 	at com.facebook.react.bridge.ReadableNativeArray.getString(Native Method)
01-07 14:40:44.078 E/AndroidRuntime(10498): 	at com.facebook.react.bridge.BaseJavaModule$5.extractArgument(BaseJavaModule.java:106)
01-07 14:40:44.078 E/AndroidRuntime(10498): 	at com.facebook.react.bridge.BaseJavaModule$5.extractArgument(BaseJavaModule.java:102)
01-07 14:40:44.078 E/AndroidRuntime(10498): 	at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:304)
01-07 14:40:44.078 E/AndroidRuntime(10498): 	... 8 more
--------- beginning of main```

**Comment by chadyj** [comment]
This should be fixed now
