### ISSUE TITLE
Android compatibility warnings about unsupported APIs in PlayStore

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#8177]
### Description
[comment]: # (Feature or Bug? i.e Type: Bug)
_Type_: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
_Summary_: PlayStore has 4 warnings in Android compatibility about unsupported APIs. The following APIs are greylisted and Google can’t guarantee that they will work on existing versions of Android. Some may be already be restricted for your target SDK

1. Landroid/app/AppGlobals;->getInitialApplication()Landroid/app/Application;

```
StrictMode policy violation: android.os.strictmode.NonSdkApiUsedViolation: Landroid/app/AppGlobals;->getInitialApplication()Landroid/app/Application;
at android.os.StrictMode.lambda$static$1(StrictMode.java:428)
at android.os.-$$Lambda$StrictMode$lu9ekkHJ2HMz0jd3F8K8MnhenxQ.accept(Unknown Source:2)
at java.lang.Class.getDeclaredMethodInternal(Native Method)
at java.lang.Class.getPublicMethodRecursive(Class.java:2075)
at java.lang.Class.getMethod(Class.java:2063)
at java.lang.Class.getMethod(Class.java:1690)
at go.LoadJNI.<clinit>(LoadJNI.java:28)
at java.lang.Class.classForName(Native Method)
at java.lang.Class.forName(Class.java:453)
at java.lang.Class.forName(Class.java:378)
at go.Seq.<clinit>(Seq.java:38)
at go.Seq.touch(Seq.java:55)
at statusgo.Statusgo.<clinit>(Statusgo.java:11)
at statusgo.Statusgo.setMobileSignalHandler(Native Method)
at im.status.ethereum.module.StatusModule.onHostResume(StatusModule.java:79)
at com.facebook.react.bridge.ReactContext.onHostResume(ReactContext.java:184)
at com.facebook.react.ReactInstanceManager.moveToResumedLifecycleState(ReactInstanceManager.java:649)
at com.facebook.react.ReactInstanceManager.moveReactContextToCurrentLifecycleState(ReactInstanceManager.java:684)
at com.facebook.react.ReactInstanceManager.setupReactContext(ReactInstanceManager.java:969)
at com.facebook.react.ReactInstanceManager.access$1300(ReactInstanceManager.java:116)
at com.facebook.react.ReactInstanceManager$5$2.run(ReactInstanceManager.java:937)
at android.os.Handler.handleCallback(Handler.java:873)
at android.os.Handler.dispatchMessage(Handler.java:99)
at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
at android.os.Looper.loop(Looper.java:193)
at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192)
at java.lang.Thread.run(Thread.java:764)
```

1. Ldalvik/system/CloseGuard;->get()Ldalvik/system/CloseGuard;

```
StrictMode policy violation: android.os.strictmode.NonSdkApiUsedViolation: Ldalvik/system/CloseGuard;->get()Ldalvik/system/CloseGuard;
at android.os.StrictMode.lambda$static$1(StrictMode.java:428)
at android.os.-$$Lambda$StrictMode$lu9ekkHJ2HMz0jd3F8K8MnhenxQ.accept(Unknown Source:2)
at java.lang.Class.getDeclaredMethodInternal(Native Method)
at java.lang.Class.getPublicMethodRecursive(Class.java:2075)
at java.lang.Class.getMethod(Class.java:2063)
at java.lang.Class.getMethod(Class.java:1690)
at okhttp3.internal.platform.AndroidPlatform$CloseGuard.get(AndroidPlatform.java:368)
at okhttp3.internal.platform.AndroidPlatform.<init>(AndroidPlatform.java:56)
at okhttp3.internal.platform.AndroidPlatform.buildIfSupported(AndroidPlatform.java:258)
at okhttp3.internal.platform.Platform.findPlatform(Platform.java:199)
at okhttp3.internal.platform.Platform.<clinit>(Platform.java:78)
at okhttp3.internal.platform.Platform.get(Platform.java:84)
at okhttp3.OkHttpClient.systemDefaultSslSocketFactory(OkHttpClient.java:300)
at okhttp3.OkHttpClient.<init>(OkHttpClient.java:255)
at okhttp3.OkHttpClient$Builder.build(OkHttpClient.java:935)
at com.github.alinz.reactnativewebviewbridge.WebViewBridgeManager.<init>(WebViewBridgeManager.java:88)
at com.github.alinz.reactnativewebviewbridge.WebViewBridgePackage.createViewManagers(WebViewBridgePackage.java:35)
at com.facebook.react.ReactInstanceManager.getOrCreateViewManagers(ReactInstanceManager.java:756)
at com.facebook.react.CoreModulesPackage.createUIManager(CoreModulesPackage.java:173)
at com.facebook.react.CoreModulesPackage.access$200(CoreModulesPackage.java:53)
at com.facebook.react.CoreModulesPackage$7.get(CoreModulesPackage.java:130)
at com.facebook.react.CoreModulesPackage$7.get(CoreModulesPackage.java:127)
at com.facebook.react.LazyReactPackage.createNativeModules(LazyReactPackage.java:79)
at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:109)
at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1175)
at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1145)
at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1086)
at com.facebook.react.ReactInstanceManager.access$900(ReactInstanceManager.java:116)
at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:916)
at java.lang.Thread.run(Thread.java:764)
```

1. Ldalvik/system/CloseGuard;->open(Ljava/lang/String;)V

```
StrictMode policy violation: android.os.strictmode.NonSdkApiUsedViolation: Ldalvik/system/CloseGuard;->open(Ljava/lang/String;)V
at android.os.StrictMode.lambda$static$1(StrictMode.java:428)
at android.os.-$$Lambda$StrictMode$lu9ekkHJ2HMz0jd3F8K8MnhenxQ.accept(Unknown Source:2)
at java.lang.Class.getDeclaredMethodInternal(Native Method)
at java.lang.Class.getPublicMethodRecursive(Class.java:2075)
at java.lang.Class.getMethod(Class.java:2063)
at java.lang.Class.getMethod(Class.java:1690)
at okhttp3.internal.platform.AndroidPlatform$CloseGuard.get(AndroidPlatform.java:369)
at okhttp3.internal.platform.AndroidPlatform.<init>(AndroidPlatform.java:56)
at okhttp3.internal.platform.AndroidPlatform.buildIfSupported(AndroidPlatform.java:258)
at okhttp3.internal.platform.Platform.findPlatform(Platform.java:199)
at okhttp3.internal.platform.Platform.<clinit>(Platform.java:78)
at okhttp3.internal.platform.Platform.get(Platform.java:84)
at okhttp3.OkHttpClient.systemDefaultSslSocketFactory(OkHttpClient.java:300)
at okhttp3.OkHttpClient.<init>(OkHttpClient.java:255)
at okhttp3.OkHttpClient$Builder.build(OkHttpClient.java:935)
at com.github.alinz.reactnativewebviewbridge.WebViewBridgeManager.<init>(WebViewBridgeManager.java:88)
at com.github.alinz.reactnativewebviewbridge.WebViewBridgePackage.createViewManagers(WebViewBridgePackage.java:35)
at com.facebook.react.ReactInstanceManager.getOrCreateViewManagers(ReactInstanceManager.java:756)
at com.facebook.react.CoreModulesPackage.createUIManager(CoreModulesPackage.java:173)
at com.facebook.react.CoreModulesPackage.access$200(CoreModulesPackage.java:53)
at com.facebook.react.CoreModulesPackage$7.get(CoreModulesPackage.java:130)
at com.facebook.react.CoreModulesPackage$7.get(CoreModulesPackage.java:127)
at com.facebook.react.LazyReactPackage.createNativeModules(LazyReactPackage.java:79)
at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:109)
at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1175)
at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1145)
at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1086)
at com.facebook.react.ReactInstanceManager.access$900(ReactInstanceManager.java:116)
at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:916)
at java.lang.Thread.run(Thread.java:764)
```

1. Ldalvik/system/CloseGuard;->warnIfOpen()V

```
StrictMode policy violation: android.os.strictmode.NonSdkApiUsedViolation: Ldalvik/system/CloseGuard;->warnIfOpen()V
at android.os.StrictMode.lambda$static$1(StrictMode.java:428)
at android.os.-$$Lambda$StrictMode$lu9ekkHJ2HMz0jd3F8K8MnhenxQ.accept(Unknown Source:2)
at java.lang.Class.getDeclaredMethodInternal(Native Method)
at java.lang.Class.getPublicMethodRecursive(Class.java:2075)
at java.lang.Class.getMethod(Class.java:2063)
at java.lang.Class.getMethod(Class.java:1690)
at okhttp3.internal.platform.AndroidPlatform$CloseGuard.get(AndroidPlatform.java:370)
at okhttp3.internal.platform.AndroidPlatform.<init>(AndroidPlatform.java:56)
at okhttp3.internal.platform.AndroidPlatform.buildIfSupported(AndroidPlatform.java:258)
at okhttp3.internal.platform.Platform.findPlatform(Platform.java:199)
at okhttp3.internal.platform.Platform.<clinit>(Platform.java:78)
at okhttp3.internal.platform.Platform.get(Platform.java:84)
at okhttp3.OkHttpClient.systemDefaultSslSocketFactory(OkHttpClient.java:300)
at okhttp3.OkHttpClient.<init>(OkHttpClient.java:255)
at okhttp3.OkHttpClient$Builder.build(OkHttpClient.java:935)
at com.github.alinz.reactnativewebviewbridge.WebViewBridgeManager.<init>(WebViewBridgeManager.java:88)
at com.github.alinz.reactnativewebviewbridge.WebViewBridgePackage.createViewManagers(WebViewBridgePackage.java:35)
at com.facebook.react.ReactInstanceManager.getOrCreateViewManagers(ReactInstanceManager.java:756)
at com.facebook.react.CoreModulesPackage.createUIManager(CoreModulesPackage.java:173)
at com.facebook.react.CoreModulesPackage.access$200(CoreModulesPackage.java:53)
at com.facebook.react.CoreModulesPackage$7.get(CoreModulesPackage.java:130)
at com.facebook.react.CoreModulesPackage$7.get(CoreModulesPackage.java:127)
at com.facebook.react.LazyReactPackage.createNativeModules(LazyReactPackage.java:79)
at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:109)
at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1175)
at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1145)
at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1086)
at com.facebook.react.ReactInstanceManager.access$900(ReactInstanceManager.java:116)
at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:916)
at java.lang.Thread.run(Thread.java:764)
```

![](https://user-images.githubusercontent.com/6584810/57513196-f8f3b100-730d-11e9-9798-bacad2fd0e30.png)

### Reproduction

* Open PlayStore
* Check Release management -> Pre-launch report

### Additional Information
[comment]: # (Please do your best to fill this out.)

* Status version: released 0.12.1
* Operating System: Android

**Comment by mandrigin** [comment]
The first one comes from `gomobile`, issue here: https://github.com/golang/go/issues/31364
They are working on the fix: https://github.com/golang/mobile/pull/31 so we need to wait for the next gomobile release.

Issue in `okhttp`: https://github.com/square/okhttp/issues/3980
They are not considering this issue until either this functionality is broken or the API becomes public.
We can't get rid of this lib because React Native. So I guess we have to live with it for now.

So, nothing to do here now, but it would be nice to revisit in a month or something.

**Comment by devhmm** [comment]
<img width="947" alt="Screen Shot 2019-07-01 at 9 51 38 AM" src="https://user-images.githubusercontent.com/38485175/60408665-e26b2700-9be5-11e9-87ea-9f8b15140a1f.png">
I am facing this problem.
How can I solve?

**Comment by churik** [comment]
not relevant anymore
