### ISSUE TITLE
[ViewManager for tag 1987 could not be found] error when installing stickers [android]

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#8197]
# Problem
Error occurred when installing stickers by autotest
https://ethstatus.testrail.net/index.php?/tests/view/642307

Can't reproduce manually

```
java.lang.RuntimeException: com.facebook.react.uimanager.IllegalViewOperationException: ViewManager for tag 1987 could not be found
```

# Logs

```
--------- beginning of crash
05-13 03:49:29.412 4524 4524 E AndroidRuntime: FATAL EXCEPTION: main
05-13 03:49:29.412 4524 4524 E AndroidRuntime: Process: im.status.ethereum.pr, PID: 4524
05-13 03:49:29.412 4524 4524 E AndroidRuntime: java.lang.RuntimeException: com.facebook.react.uimanager.IllegalViewOperationException: ViewManager for tag 1987 could not be found
05-13 03:49:29.412 4524 4524 E AndroidRuntime: at com.facebook.react.bridge.ReactContext.handleException(ReactContext.java:320)
05-13 03:49:29.412 4524 4524 E AndroidRuntime: at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:31)
05-13 03:49:29.412 4524 4524 E AndroidRuntime: at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:166)
05-13 03:49:29.412 4524 4524 E AndroidRuntime: at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:84)
05-13 03:49:29.412 4524 4524 E AndroidRuntime: at android.view.Choreographer$CallbackRecord.run(Choreographer.java:909)
05-13 03:49:29.412 4524 4524 E AndroidRuntime: at android.view.Choreographer.doCallbacks(Choreographer.java:723)
05-13 03:49:29.412 4524 4524 E AndroidRuntime: at android.view.Choreographer.doFrame(Choreographer.java:655)
05-13 03:49:29.412 4524 4524 E AndroidRuntime: at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
05-13 03:49:29.412 4524 4524 E AndroidRuntime: at android.os.Handler.handleCallback(Handler.java:789)
05-13 03:49:29.412 4524 4524 E AndroidRuntime: at android.os.Handler.dispatchMessage(Handler.java:98)
05-13 03:49:29.412 4524 4524 E AndroidRuntime: at android.os.Looper.loop(Looper.java:164)
05-13 03:49:29.412 4524 4524 E AndroidRuntime: at android.app.ActivityThread.main(ActivityThread.java:6541)
05-13 03:49:29.412 4524 4524 E AndroidRuntime: at java.lang.reflect.Method.invoke(Native Method)
05-13 03:49:29.412 4524 4524 E AndroidRuntime: at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
05-13 03:49:29.412 4524 4524 E AndroidRuntime: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
05-13 03:49:29.412 4524 4524 E AndroidRuntime: Caused by: com.facebook.react.uimanager.IllegalViewOperationException: ViewManager for tag 1987 could not be found
05-13 03:49:29.412 4524 4524 E AndroidRuntime: at com.facebook.react.uimanager.NativeViewHierarchyManager.resolveViewManager(NativeViewHierarchyManager.java:105)
05-13 03:49:29.412 4524 4524 E AndroidRuntime: at com.facebook.react.uimanager.NativeViewHierarchyManager.manageChildren(NativeViewHierarchyManager.java:353)
05-13 03:49:29.412 4524 4524 E AndroidRuntime: at com.facebook.react.uimanager.UIViewOperationQueue$ManageChildrenOperation.execute(UIViewOperationQueue.java:227)
05-13 03:49:29.412 4524 4524 E AndroidRuntime: at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:917)
05-13 03:49:29.412 4524 4524 E AndroidRuntime: at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:1025)
05-13 03:49:29.412 4524 4524 E AndroidRuntime: at com.facebook.react.uimanager.UIViewOperationQueue.access$2600(UIViewOperationQueue.java:46)
05-13 03:49:29.412 4524 4524 E AndroidRuntime: at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:1085)
05-13 03:49:29.412 4524 4524 E AndroidRuntime: at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
05-13 03:49:29.412 4524 4524 E AndroidRuntime: ... 13 more
05-13 03:49:29.460 1407 1407 D SurfaceFlinger: duplicate layer name: changing im.status.ethereum.pr/im.status.ethereum.MainActivity to im.status.ethereum.pr/im.status.ethereum.MainActivity#1
05-13 03:49:29.463 1397 1397 D gralloc_ranchu: gralloc_alloc: Creating ashmem region of size 1945600
05-13 03:49:29.465 1397 1397 D gralloc_ranchu: gralloc_alloc: Creating ashmem region of size 1945600
05-13 03:49:29.467 1407 1693 D : HostConnection::get() New Host Connection established 0x702690913ba0, tid 1693
05-13 03:49:29.467 1397 1397 D gralloc_ranchu: gralloc_alloc: Creating ashmem region of size 1945600
05-13 03:49:29.476 4524 4550 D EGL_emulation: eglMakeCurrent: 0xcbad0c00: ver 2 0 (tinfo 0xcbac3d70)
05-13 03:49:29.772 2578 2578 D MediaScannerReceiver: action: android.intent.action.MEDIA_SCANNER_SCAN_FILE path: /data/local/tmp/screen.png
05-13 03:49:30.199 4487 4621 I appium : channel read invoked!
05-13 03:49:30.199 4487 4621 I appium : channel read: POST /wd/hub/session/5b91b476-1c4a-4c93-9aae-f1246e8fe297/element
05-13 03:49:30.200 4487 4621 I appium : Find element command
05-13 03:49:30.200 4487 4621 D appium : payload: {"strategy":"accessibility id","selector":"back-button","context":"","multiple":false}
05-13 03:49:30.200 4487 4621 I appium : find element command using 'accessibility id' with selector 'back-button'.
05-13 03:49:30.206 4487 4621 I appium : AppiumResponse: {"sessionId":"5b91b476-1c4a-4c93-9aae-f1246e8fe297","status":7,"value":"An element could not be located on the page using the given search parameters."}
05-13 03:49:30.718 4487 4514 I appium : channel read invoked!
05-13 03:49:30.718 4487 4514 I appium : channel read: POST /wd/hub/session/5b91b476-1c4a-4c93-9aae-f1246e8fe297/element
05-13 03:49:30.718 4487 4514 I appium : Find element command
05-13 03:49:30.718 4487 4514 D appium : payload: {"strategy":"accessibility id","selector":"back-button","context":"","multiple":false}
05-13 03:49:30.718 4487 4514 I appium : find element command using 'accessibility id' with selector 'back-button'.
05-13 03:49:30.721 4487 4514 I appium : AppiumResponse: {"sessionId":"5b91b476-1c4a-4c93-9aae-f1246e8fe297","status":7,"value":"An element could not be located on the page using the given search parameters."}
05-13 03:49:31.127 1405 1405 I boot-pipe: done populating /dev/random
05-13 03:49:31.234 4487 4516 I appium : channel read invoked!
05-13 03:49:31.234 4487 4516 I appium : channel read: POST /wd/hub/session/5b91b476-1c4a-4c93-9aae-f1246e8fe297/element
05-13 03:49:31.235 4487 4516 I appium : Find element command
05-13 03:49:31.235 4487 4516 D appium : payload: {"strategy":"accessibility id","selector":"back-button","context":"","multiple":false}
05-13 03:49:31.235 4487 4516 I appium : find element command using 'accessibility id' with selector 'back-button'.
05-13 03:49:31.247 4487 4516 I appium : AppiumResponse: {"sessionId":"5b91b476-1c4a-4c93-9aae-f1246e8fe297","status":7,"value":"An element could not be located on the page using the given search parameters."}
05-13 03:49:31.761 4487 4607 I appium : channel read invoked!
05-13 03:49:31.761 4487 4607 I appium : channel read: POST /wd/hub/session/5b91b476-1c4a-4c93-9aae-f1246e8fe297/element
05-13 03:49:31.761 4487 4607 I appium : Find element command
05-13 03:49:31.761 4487 4607 D appium : payload: {"strategy":"accessibility id","selector":"back-button","context":"","multiple":false}
05-13 03:49:31.761 4487 4607 I appium : find element command using 'accessibility id' with selector 'back-button'.
05-13 03:49:31.765 4487 4607 I appium : AppiumResponse: {"sessionId":"5b91b476-1c4a-4c93-9aae-f1246e8fe297","status":7,"value":"An element could not be located on the page using the given search parameters."}
05-13 03:49:31.767 2209 2713 W ctxmgr : [AclManager]No 2 for (accnt=account#-517948760#, com.google.android.gms(10013):IndoorOutdoorProducer, vrsn=13280000, 0, 3pPkg = null , 3pMdlId = null , pid = 2209). Was: 3 for 57, account#-517948760#
05-13 03:49:32.276 4487 4621 I appium : channel read invoked!
05-13 03:49:32.277 4487 4621 I appium : channel read: POST /wd/hub/session/5b91b476-1c4a-4c93-9aae-f1246e8fe297/element
05-13 03:49:32.277 4487 4621 I appium : Find element command
05-13 03:49:32.277 4487 4621 D appium : payload: {"strategy":"accessibility id","selector":"back-button","context":"","multiple":false}
05-13 03:49:32.277 4487 4621 I appium : find element command using 'accessibility id' with selector 'back-button'.
05-13 03:49:32.281 4487 4621 I appium : AppiumResponse: {"sessionId":"5b91b476-1c4a-4c93-9aae-f1246e8fe297","status":7,"value":"An element could not be located on the page using the given search parameters."}
05-13 03:49:32.387 1391 1629 W audio_hw_generic: Not supplying enough data to HAL, expected position 1730314 , only wrote 1408320
05-13 03:49:32.791 4487 4514 I appium : channel read invoked!
05-13 03:49:32.791 4487 4514 I appium : channel read: POST /wd/hub/session/5b91b476-1c4a-4c93-9aae-f1246e8fe297/element
05-13 03:49:32.792 4487 4514 I appium : Find element command
05-13 03:49:32.792 4487 4514 D appium : payload: {"strategy":"accessibility id","selector":"back-button","context":"","multiple":false}
05-13 03:49:32.792 4487 4514 I appium : find element command using 'accessibility id' with selector 'back-button'.
05-13 03:49:32.795 4487 4514 I appium : AppiumResponse: {"sessionId":"5b91b476-1c4a-4c93-9aae-f1246e8fe297","status":7,"value":"An element could not be located on the page using the given search parameters."}
05-13 03:49:33.310 4487 4516 I appium : channel read invoked!
05-13 03:49:33.310 4487 4516 I appium : channel read: POST /wd/hub/session/5b91b476-1c4a-4c93-9aae-f1246e8fe297/element
05-13 03:49:33.310 4487 4516 I appium : Find element command
05-13 03:49:33.311 4487 4516 D appium : payload: {"strategy":"accessibility id","selector":"back-button","context":"","multiple":false}
05-13 03:49:33.311 4487 4516 I appium : find element command using 'accessibility id' with selector 'back-button'.
05-13 03:49:33.315 4487 4516 I appium : AppiumResponse: {"sessionId":"5b91b476-1c4a-4c93-9aae-f1246e8fe297","status":7,"value":"An element could not be located on the page using the given search parameters."}
05-13 03:49:33.717 1598 1692 W ActivityManager: Unable to start service Intent { act=com.google.android.gms.drive.ApiService.RESET_AFTER_BOOT flg=0x4 cmp=com.google.android.gms/.drive.api.ApiService (has extras) } U=0: not found
05-13 03:49:33.720 1598 1640 E memtrack: Couldn't load memtrack module
05-13 03:49:33.720 1598 1640 W android.os.Debug: failed to get memory consumption info: -1
05-13 03:49:33.828 4487 4607 I appium : channel read invoked!
05-13 03:49:33.828 4487 4607 I appium : channel read: POST /wd/hub/session/5b91b476-1c4a-4c93-9aae-f1246e8fe297/element
05-13 03:49:33.829 4487 4607 I appium : Find element command
05-13 03:49:33.829 4487 4607 D appium : payload: {"strategy":"accessibility id","selector":"back-button","context":"","multiple":false}
05-13 03:49:33.829 4487 4607 I appium : find element command using 'accessibility id' with selector 'back-button'.
05-13 03:49:33.832 4487 4607 I appium : AppiumResponse: {"sessionId":"5b91b476-1c4a-4c93-9aae-f1246e8fe297","status":7,"value":"An element could not be located on the page using the given search parameters."}
05-13 03:49:34.345 4487 4621 I appium : channel read invoked!
05-13 03:49:34.345 4487 4621 I appium : channel read: POST /wd/hub/session/5b91b476-1c4a-4c93-9aae-f1246e8fe297/element
05-13 03:49:34.345 4487 4621 I appium : Find element command
05-13 03:49:34.345 4487 4621 D appium : payload: {"strategy":"accessibility id","selector":"back-button","context":"","multiple":false}
05-13 03:49:34.346 4487 4621 I appium : find element command using 'accessibility id' with selector 'back-button'.
05-13 03:49:34.349 4487 4621 I appium : AppiumResponse: {"sessionId":"5b91b476-1c4a-4c93-9aae-f1246e8fe297","status":7,"value":"An element could not be located on the page using the given search parameters."}
05-13 03:49:34.873 4487 4514 I appium : channel read invoked!
05-13 03:49:34.873 4487 4514 I appium : channel read: POST /wd/hub/session/5b91b476-1c4a-4c93-9aae-f1246e8fe297/element
05-13 03:49:34.874 4487 4514 I appium : Find element command
05-13 03:49:34.874 4487 4514 D appium : payload: {"strategy":"accessibility id","selector":"back-button","context":"","multiple":false}
05-13 03:49:34.874 4487 4514 I appium : find element command using 'accessibility id' with selector 'back-button'.
05-13 03:49:34.877 4487 4514 I appium : AppiumResponse: {"sessionId":"5b91b476-1c4a-4c93-9aae-f1246e8fe297","status":7,"value":"An element could not be located on the page using the given search parameters."}
05-13 03:49:35.393 4487 4516 I appium : channel read invoked!
05-13 03:49:35.395 4487 4516 I appium : channel read: POST /wd/hub/session/5b91b476-1c4a-4c93-9aae-f1246e8fe297/element
05-13 03:49:35.395 4487 4516 I appium : Find element command
05-13 03:49:35.395 4487 4516 D appium : payload: {"strategy":"accessibility id","selector":"back-button","context":"","multiple":false}
05-13 03:49:35.396 4487 4516 I appium : find element command using 'accessibility id' with selector 'back-button'.
05-13 03:49:35.400 4487 4516 I appium : AppiumResponse: {"sessionId":"5b91b476-1c4a-4c93-9aae-f1246e8fe297","status":7,"value":"An element could not be located on the page using the given search parameters."}
05-13 03:49:35.849 1598 1645 E BatteryStatsService: modem info is invalid: ModemActivityInfo{ mTimestamp=0 mSleepTimeMs=0 mIdleTimeMs=0 mTxTimeMs[]=[0, 0, 0, 0, 0] mRxTimeMs=0 mEnergyUsed=0}
05-13 03:49:36.168 4524 5334 D StatusModule: Signal event: {"type":"subscriptions.data","event":{"subscription_id":"eth-be480cfa-5fa2-4a1e-a6ee-a5476acb2a3d","data":["0x8952782ef92045eca08b33beb8a80f0d13c5aa0469b215d2575a248390a253ab"]}}
05-13 03:49:36.168 4524 5334 W unknown:ReactNative: Calling JS function after bridge has been destroyed: RCTDeviceEventEmitter.emit(["gethEvent",{"jsonEvent":"{\"type\":\"subscriptions.data\",\"event\":{\"subscription_id\":\"eth-be480cfa-5fa2-4a1e-a6ee-a5476acb2a3d\",\"data\":[\"0x8952782ef92045eca08b33beb8a80f0d13c5aa0469b215d2575a248390a253ab\"]}}"}])
05-13 03:49:36.579 4487 4607 I appium : channel read invoked!
05-13 03:49:36.580 4487 4607 I appium : channel read: POST /wd/hub/session/5b91b476-1c4a-4c93-9aae-f1246e8fe297/element
05-13 03:49:36.580 4487 4607 I appium : Find element command
05-13 03:49:36.580 4487 4607 D appium : payload: {"strategy":"id","selector":"android:id/message","context":"","multiple":false}
05-13 03:49:36.580 4487 4607 I appium : find element command using 'id' with selector 'android:id/message'.
05-13 03:49:36.583 4487 4607 I appium : AppiumResponse: {"sessionId":"5b91b476-1c4a-4c93-9aae-f1246e8fe297","status":0,"value":{"ELEMENT":"7b033aa8-7473-4a1d-881e-3250575727cb"}}
05-13 03:49:36.726 1598 2320 D WificondControl: Scan result ready event
05-13 03:49:36.766 2209 5166 W ctxmgr : [AclManager]No 2 for (accnt=account#-517948760#, com.google.android.gms(10013):IndoorOutdoorProducer, vrsn=13280000, 0, 3pPkg = null , 3pMdlId = null , pid = 2209). Was: 3 for 57, account#-517948760#
05-13 03:49:36.977 4487 4621 I appium : channel read invoked!
05-13 03:49:36.977 4487 4621 I appium : channel read: POST /wd/hub/session/5b91b476-1c4a-4c93-9aae-f1246e8fe297/element
05-13 03:49:36.977 4487 4621 I appium : Find element command
05-13 03:49:36.977 4487 4621 D appium : payload: {"strategy":"id","selector":"android:id/message","context":"","multiple":false}
05-13 03:49:36.978 4487 4621 I appium : find element command using 'id' with selector 'android:id/message'.
05-13 03:49:36.990 4487 4621 I appium : AppiumResponse: {"sessionId":"5b91b476-1c4a-4c93-9aae-f1246e8fe297","status":0,"value":{"ELEMENT":"8c40e941-6bd0-4ad5-84f9-6a749a0b0544"}}
05-13 03:49:37.363 4487 4514 I appium : channel read invoked!
05-13 03:49:37.363 4487 4514 I appium : channel read: GET /wd/hub/session/5b91b476-1c4a-4c93-9aae-f1246e8fe297/element/8c40e941-6bd0-4ad5-84f9-6a749a0b0544/text
05-13 03:49:37.363 4487 4514 I appium : Get Text of element command
05-13 03:49:37.367 4487 4514 I appium : Get Text :java.lang.RuntimeException: com.facebook.react.uimanager.IllegalViewOperationException: ViewManager for tag 1987 could not be found
05-13 03:49:37.367 4487 4514 I appium : AppiumResponse: {"sessionId":"5b91b476-1c4a-4c93-9aae-f1246e8fe297","status":0,"value":"java.lang.RuntimeException: com.facebook.react.uimanager.IllegalViewOperationException: ViewManager for tag 1987 could not be found"}
05-13 03:49:37.818 1407 2207 E SurfaceFlinger: ro.sf.lcd_density must be defined as a build property
05-13 03:49:37.826 1397 1397 D gralloc_ranchu: gralloc_alloc: Creating ashmem region of size 3936256
05-13 03:49:37.831 5780 5780 D : HostConnection::get() New Host Connection established 0x76a2e122f780, tid 5780
05-13 03:49:37.835 1407 1407 E EGL_emulation: tid 1407: eglCreateSyncKHR(2054): error 0x3004 (EGL_BAD_ATTRIBUTE)
05-13 03:49:38.234 2578 2578 D MediaScannerReceiver: action: android.intent.action.MEDIA_SCANNER_SCAN_FILE path: /data/local/tmp/screen.png
```

**Comment by asemiankevich** [comment]
@flexsurfer please take a look

**Comment by xinyujauchou** [comment]
what is your RN version

**Comment by asemiankevich** [comment]
stickers install is removed on test net
