### ISSUE TITLE
Can't attach logs to email draft on android on some devices

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#8276]
# Problem
Error `can't add attachment` shown when trying to send logs on Android (7 and 8 at least) on some devices. User can't send logs.

## Steps

1. install status and create account
1. profile -> dev mode -> send logs -> gmail

![image](https://user-images.githubusercontent.com/28752642/58313098-7858a880-7e15-11e9-822d-856b690401f6.png)

## Build
Reproduced in:

* nightly build https://status-im.ams3.digitaloceanspaces.com/StatusIm-190524-025900-ee1277-nightly.apk
* release 0.13 https://ci.status.im/job/status-react/job/release/job/release%252F0.13.x/

Devices: 

* Android 7 (Xiaomi Redmi Note 4)
* Android 8 (Huawei P10 Lite)

## Note:
**it is working fine on same devices in 0.12.2 release**

## Logs

```
2019-05-24 12:20:04.389 1519-3240/? I/ActivityManager: START u0 {act=android.intent.action.SEND dat=<a href="mailto:" target="_blank" rel="nofollow noreferrer noopener" data-auto-wrap="true">mailto:</a> flg=0xb080003 cmp=com.google.android.gm/.ComposeActivityGmailExternal (has extras) sel=act=android.intent.action.SENDTO dat=<a href="mailto:}}" target="_blank" rel="nofollow noreferrer noopener" data-auto-wrap="true">mailto:}}</a> from uid 10376 on display 0
2019-05-24 12:20:04.738 9330-9330/? W/Gmail: Gmail:No collectionId found for event forward
2019-05-24 12:20:04.738 9330-9330/? W/Gmail: Gmail:No itemId found for event forward
2019-05-24 12:20:04.760 9330-9330/? E/Gmail: Gmail:Error adding attachment
ebj: Security Exception from attachment uri
at ebk.a(SourceFile:75)
at ckl.a(SourceFile:436)
at clh.run(SourceFile:2)
at ckl.a(SourceFile:201)
at ckl.a(SourceFile:691)
at ckl.R(SourceFile:73)
at ckl.onCreate(SourceFile:26)
at com.google.android.gm.ComposeActivityGmail.onCreate(SourceFile:19)
at android.app.Activity.performCreate(Activity.java:6845)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2700)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2808)
at android.app.ActivityThread.-wrap12(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1541)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:165)
at android.app.ActivityThread.main(ActivityThread.java:6375)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:802)
Caused by: java.lang.SecurityException: Permission Denial: opening provider android.support.v4.content.FileProvider from ProcessRecord{824f099 9330:com.google.android.gm/u0a69} (pid=9330, uid=10069) that is not exported from uid 10376
at android.os.Parcel.readException(Parcel.java:1715)
at android.os.Parcel.readException(Parcel.java:1668)
at android.app.ActivityManagerProxy.getContentProvider(ActivityManagerNative.java:4256)
at android.app.ActivityThread.acquireProvider(ActivityThread.java:5620)
at android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider(ContextImpl.java:2281)
at android.content.ContentResolver.acquireUnstableProvider(ContentResolver.java:1531)
at android.content.ContentResolver.query(ContentResolver.java:516)
at android.content.ContentResolver.query(ContentResolver.java:473)
at ebk.a(SourceFile:60)
at ckl.a(SourceFile:436)
at clh.run(SourceFile:2)
at ckl.a(SourceFile:201)
at ckl.a(SourceFile:691)
at ckl.R(SourceFile:73)
at ckl.onCreate(SourceFile:26)
at com.google.android.gm.ComposeActivityGmail.onCreate(SourceFile:19)
at android.app.Activity.performCreate(Activity.java:6845)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2700)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2808)
at android.app.ActivityThread.-wrap12(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1541)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:165)
at android.app.ActivityThread.main(ActivityThread.java:6375)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:802)
2019-05-24 12:20:04.845 9330-10380/? W/Gmail: Gmail:No valid account details in bundle: empty username, email address and/or host
2019-05-24 12:20:04.996 1519-1608/? I/ActivityManager: Displayed com.google.android.gm/.ComposeActivityGmailExternal: +552ms
2019-05-24 12:20:04.997 1519-1608/? I/Timeline: Timeline: Activity_windows_visible id: ActivityRecord{7685a40 u0 com.google.android.gm/.ComposeActivityGmailExternal t116} time:560091276
2019-05-24 12:20:04.997 4067-4235/? D/PowerKeeper.Event: notifyActivityLaunchTime: com.google.android.gm/.ComposeActivityGmailExternal totalTime: 552
```

**Comment by annadanchenko** [comment]
tried with PR build 6 https://github.com/status-im/status-react/pull/8141 on 
1. Pixel XL, Android 9 - can shake device and logs are attached to email
2. Galaxy S6, Android 6.0.1 -  can shake device and logs are attached to email

**Comment by mandrigin** [comment]
@asemiankevich probably a logcat would be useful, maybe gmail shows some real error reason there.

**Comment by asemiankevich** [comment]
> @asemiankevich probably a logcat would be useful, maybe gmail shows some real error reason there.

sorry i had to do it first thing. Added.

**Comment by rasom** [comment]
works fine on:
1. galaxy s9, android 9
2. galaxy a500d, android 6.0.1

**Comment by churik** [comment]
Works fine on Android 8 (LG V20)

**Comment by Serhy** [comment]
Works fine with Android 8.1 (Samsung Galaxy J7) and Android 6.0.1 (Galaxy Note 4)

**Comment by churik** [comment]
Couldn't reproduce (nightly 26/02/2020)
