### ISSUE TITLE
"test" topic crashes applocation

### ISSUE THREAD

**Issue by rasom** [status-im/status-react#849]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: Application crashes after joining of public chat with "test" topic

#### Expected behavior
[comment]: # Application shouldn't crash.

#### Actual behavior
[comment]: # But it crashes.

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Press "join public chat"
- enter "test" topic
- press "create"

#### Logs

[comment]: # (if on Android please replicate bug whilst running adb logcat)
```
03-06 11:01:46.216 12875 12916 E AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
03-06 11:01:46.216 12875 12916 E AndroidRuntime: Process: im.status.ethereum, PID: 12875
03-06 11:01:46.216 12875 12916 E AndroidRuntime: com.facebook.react.common.JavascriptException: EOF while reading, stack:
03-06 11:01:46.216 12875 12916 E AndroidRuntime: $s@16:2946
03-06 11:01:46.216 12875 12916 E AndroidRuntime: cf@16:5259
03-06 11:01:46.216 12875 12916 E AndroidRuntime: lf@16:4085
03-06 11:01:46.216 12875 12916 E AndroidRuntime: of@16:4660
03-06 11:01:46.216 12875 12916 E AndroidRuntime: _f@16:7918
03-06 11:01:46.216 12875 12916 E AndroidRuntime: jf@16:8707
03-06 11:01:46.216 12875 12916 E AndroidRuntime: dy@22:6172
03-06 11:01:46.216 12875 12916 E AndroidRuntime: <unknown>@22:7409
03-06 11:01:46.216 12875 12916 E AndroidRuntime: <unknown>@1152:553
03-06 11:01:46.216 12875 12916 E AndroidRuntime: <unknown>@1152:539
03-06 11:01:46.216 12875 12916 E AndroidRuntime: <unknown>@1152:2189
03-06 11:01:46.216 12875 12916 E AndroidRuntime: <unknown>@1135:1293
03-06 11:01:46.216 12875 12916 E AndroidRuntime: <unknown>@957:610
03-06 11:01:46.216 12875 12916 E AndroidRuntime: onreadystatechange@1170:884
03-06 11:01:46.216 12875 12916 E AndroidRuntime: value@218:1505
03-06 11:01:46.216 12875 12916 E AndroidRuntime: value@217:6714
03-06 11:01:46.216 12875 12916 E AndroidRuntime: value@217:3493
03-06 11:01:46.216 12875 12916 E AndroidRuntime: <unknown>@217:5824
03-06 11:01:46.216 12875 12916 E AndroidRuntime: value@111:1338
03-06 11:01:46.216 12875 12916 E AndroidRuntime: value@63:2818
03-06 11:01:46.216 12875 12916 E AndroidRuntime: <unknown>@63:1053
03-06 11:01:46.216 12875 12916 E AndroidRuntime: d@63:127
03-06 11:01:46.216 12875 12916 E AndroidRuntime: value@63:1025
03-06 11:01:46.216 12875 12916 E AndroidRuntime:
03-06 11:01:46.216 12875 12916 E AndroidRuntime:     at com.facebook.react.modules.core.ExceptionsManagerModule.showOrThrowError(ExceptionsManagerModule.java:97)
03-06 11:01:46.216 12875 12916 E AndroidRuntime:     at com.facebook.react.modules.core.ExceptionsManagerModule.reportFatalException(ExceptionsManagerModule.java:81)
03-06 11:01:46.216 12875 12916 E AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method)
03-06 11:01:46.216 12875 12916 E AndroidRuntime:     at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:318)
03-06 11:01:46.216 12875 12916 E AndroidRuntime:     at com.facebook.react.cxxbridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
03-06 11:01:46.216 12875 12916 E AndroidRuntime:     at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
03-06 11:01:46.216 12875 12916 E AndroidRuntime:     at android.os.Handler.handleCallback(Handler.java:739)
03-06 11:01:46.216 12875 12916 E AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:95)
03-06 11:01:46.216 12875 12916 E AndroidRuntime:     at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
03-06 11:01:46.216 12875 12916 E AndroidRuntime:     at android.os.Looper.loop(Looper.java:148)
03-06 11:01:46.216 12875 12916 E AndroidRuntime:     at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
03-06 11:01:46.216 12875 12916 E AndroidRuntime:     at java.lang.Thread.run(Thread.java:818)
```
after
```
[
:status-im.commands.handlers.loading/add-commands
"test"
"I18n.translations = {\n en: {\n location_title: 'Location',\n location_description: 'Share your location',\n location_address: 'Address',\n\n browse_title: 'Browser',\n browse_description: 'Launch the browser',\n\n send_title: 'Send ETH',\n send_description: 'Send a payment',\n\n request_title: 'Request ETH',\n request_description: 'Request a payment',\n request_requesting: 'Requesting ',\n\n validation_title: 'Amount',\n validation_amount_specified: 'Amount must be specified',\n validation_invalid_number: 'Amount is not valid number',\n validation_insufficient_amount: 'Insufficient funds for gas * price + value (balance '\n },\n ru: {\n location_title: 'Местоположение',\n location_description: 'Поделитесь своим местоположением',\n location_address: 'Адрес',\n\n browse_title: 'Браузер',\n browse_description: 'Запуск браузера',\n\n send_title: 'Отправить ETH',\n send_description: 'Отправить платеж',\n\n request_title: 'Запросить ETH',\n request_description: 'Запросить платеж',\n request_requesting: 'Запрос ',\n\n validation_title: 'Сумма',\n vali....
```

**Comment by rasom** [comment]
This problem was caused by messages that weren't sent from Status and this case wasn't handled properly.
