### ISSUE TITLE
App crashes all the time on login if change network while DataSync enabled 

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#8867]
***Type***: Bug

***Summary***: When user has enabled DataSync and then switching to different network - there is no way to login to account after. Status crashes all the time after entering valid password. 
Can create new account or recover different account, but no way to login to the one who changed network while DataSync enabled

Not reproducible with iOS but only Android. 

#### Expected behavior

Can login to account with DataSync enabled after network changed

#### Actual behavior

Can NOT login to account (app crashes) with DataSync enabled after network changed

Video of behavior: https://drive.google.com/file/d/1qdm5yob-5wxnnLR7qyldAJRVjt1d6gfL/view?usp=sharing

### Reproduction

- Open Status and create new account
- Navigate to `Profile` -> `Advanced` -> enable `Developpment mode`
- Enable `DataSync Enabled` setting
- Re-login to account (as suggested in the pop-up after enabling DataSync)
- Change network to different one (e.g. POA/xDAI/Ropsten)
- Login to account

### Additional Information

- Status version: Develop nighty 0.14.0 (2019082902)
- Operating System: Android only

#### Logs

Logcat logs when tap "Sign In" for above scenario
```
08-29 13:02:19.284  9802  9802 D ViewRootImpl@a55e3f0[MainActivity]: ViewPostIme pointer 0
08-29 13:02:19.335  9802  9802 D ViewRootImpl@a55e3f0[MainActivity]: ViewPostIme pointer 1
08-29 13:02:19.346  9802  9857 D ReactNativeJS: DEBUG [status-im.utils.handlers:32] - Handling re-frame event:  :multiaccounts.login.ui/password-input-submitted
08-29 13:02:19.352  9802  9858 D StatusModule: clearCookies
08-29 13:02:19.353  9802  9858 D StatusModule: clearStorageAPIs
08-29 13:02:19.355  9802  9858 D StatusModule: login
08-29 13:02:19.359  9802  9858 D StatusModule: Login result: {"error":""}
08-29 13:02:19.371  9802  9802 D InputMethodManager: HSIFW - flag : 0 Pid : 9802
08-29 13:02:19.456  9802  9802 D ViewRootImpl@a55e3f0[MainActivity]: MSG_RESIZED: frame=Rect(0, 0 - 1080, 1920) ci=Rect(0, 63 - 0, 0) vi=Rect(0, 63 - 0, 0) or=1
08-29 13:02:19.477  9802  9802 D ViewRootImpl@a55e3f0[MainActivity]: Relayout returned: old=[0,0][1080,1920] new=[0,0][1080,1920] result=0x1 surface={valid=true 3551336448} changed=false
08-29 13:02:19.481  9802  9857 D ReactNativeJS: DEBUG [status-im.utils.handlers:32] - Handling re-frame event:  :show-tab-bar
08-29 13:02:19.486  9802  9857 D ReactNativeJS: DEBUG [status-im.utils.handlers:32] - Handling re-frame event:  :set
08-29 13:02:19.512  9802  9985 E GoLog   : INFO [08-29|10:02:19.512] LES protocol is disabled                 package=status-go/node
08-29 13:02:19.513  9802  9985 E GoLog   : INFO [08-29|10:02:19.512] Incentivisation is disabled              package=status-go/node
08-29 13:02:19.513  9802  9985 E GoLog   : INFO [08-29|10:02:19.513] Status service api is disabled           package=status-go/node
08-29 13:02:19.515  9802  9987 E GoLog   : INFO [08-29|10:02:19.515] Starting peer-to-peer node               instance=StatusIM/android-arm/go1.11.5
08-29 13:02:19.537  9802  9985 E GoLog   : INFO [08-29|10:02:19.537] started whisper v.6.0 
08-29 13:02:19.548  9802  9986 E GoLog   : INFO [08-29|10:02:19.548] New local node record                    seq=1 id=2ca1e4eea2f1798d ip=127.0.0.1 udp=0 tcp=0
08-29 13:02:19.549  9802  9986 E GoLog   : INFO [08-29|10:02:19.548] Started P2P networking                   self=enode://a293e6f15a90c22abaa17bea92bebcf7fa5becb64689dc9ace401e1d4f8dd5d38593aef56772c7e4ee3874c11a2ee18d1bd11ad41a1500e62f264d136fbacaa2@127.0.0.1:0
08-29 13:02:19.552  9802  9894 D StatusModule: Signal event: {"type":"node.started","event":null}
08-29 13:02:19.553  9802  9986 E GoLog   : INFO [08-29|10:02:19.553] Handlers registered                      package=status-go/api.StatusBackend
08-29 13:02:19.553  9802  9986 E GoLog   : INFO [08-29|10:02:19.553] Account reselected                       package=status-go/api.StatusBackend
08-29 13:02:19.553  9802  9894 D StatusModule: Signal event: {"type":"node.ready","event":null}
08-29 13:02:19.558  9802  9857 D ReactNativeJS: DEBUG [status-im.utils.handlers:32] - Handling re-frame event:  :signals/signal-received
08-29 13:02:19.562  9802  9857 D ReactNativeJS: DEBUG [status-im.events:691] - :event-str {"type":"node.started","event":null}
08-29 13:02:19.565  9802  9986 E GoLog   : INFO [08-29|10:02:19.564] UDP listener up                          net=enode://a293e6f15a90c22abaa17bea92bebcf7fa5becb64689dc9ace401e1d4f8dd5d38593aef56772c7e4ee3874c11a2ee18d1bd11ad41a1500e62f264d136fbacaa2@[::]:49709
08-29 13:02:19.567  9802  9857 D ReactNativeJS: DEBUG [status-im.signals.core:51] - Event  node.started  not handled nil
08-29 13:02:19.569  9802  9857 D ReactNativeJS: DEBUG [status-im.utils.handlers:32] - Handling re-frame event:  :signals/signal-received
08-29 13:02:19.571  9802  9857 D ReactNativeJS: DEBUG [status-im.events:691] - :event-str {"type":"node.ready","event":null}
08-29 13:02:19.573  9802  9857 D ReactNativeJS: DEBUG [status-im.signals.core:51] - Event  node.ready  not handled nil
08-29 13:02:19.583  9802  9894 D StatusModule: Signal event: {"type":"discovery.started","event":null}
08-29 13:02:19.588  9802  9857 D ReactNativeJS: DEBUG [status-im.utils.handlers:32] - Handling re-frame event:  :signals/signal-received
08-29 13:02:19.591  9802  9857 D ReactNativeJS: DEBUG [status-im.events:691] - :event-str {"type":"discovery.started","event":null}
08-29 13:02:19.593  9802  9857 D ReactNativeJS: DEBUG [status-im.signals.core:51] - Event  discovery.started  not handled nil
08-29 13:02:19.626  9802  9862 E GoLog   : INFO [08-29|10:02:19.626] Difference with ntp servers              offset=-3.162743222s
08-29 13:02:19.644  9802 10123 D StatusModule: Signal event: {"type":"discovery.summary","event":[{"enode":"enode://4e0a8db9b73403c9339a2077e911851750fc955db1fc1e09f81a4a56725946884dd5e4d11258eac961f9078a393c45bcab78dd0e3bc74e37ce773b3471d2e29c@206.189.243.171:443","id":"829fad8fd411906d3bb0447e4c228b902d824c3c7685d4032aeecfb4e09f835d","name":"Statusd/v0.29.0-beta.2/linux-amd64/go1.12.5","caps":["shh/6"],"network":{"localAddress":"192.168.2.56:36060","remoteAddress":"206.189.243.171:443","inbound":false,"trusted":false,"static":true},"protocols":{"shh":"unknown"}}]}
08-29 13:02:19.647  9802 10123 D StatusModule: Signal event: {"type":"discovery.summary","event":[{"enode":"enode://4e0a8db9b73403c9339a2077e911851750fc955db1fc1e09f81a4a56725946884dd5e4d11258eac961f9078a393c45bcab78dd0e3bc74e37ce773b3471d2e29c@206.189.243.171:443","id":"829fad8fd411906d3bb0447e4c228b902d824c3c7685d4032aeecfb4e09f835d","name":"Statusd/v0.29.0-beta.2/linux-amd64/go1.12.5","caps":["shh/6"],"network":{"localAddress":"192.168.2.56:36060","remoteAddress":"206.189.243.171:443","inbound":false,"trusted":false,"static":true},"protocols":{"shh":"unknown"}},{"enode":"enode://0d9d65fcd5592df33ed4507ce862b9c748b6dbd1ea3a1deb94e3750052760b4850aa527265bbaf357021d64d5cc53c02b410458e732fafc5b53f257944247760@167.99.18.187:443","id":"98ab721a4762645a887ffb29672a18d81aa86206c9d0243d95bb0b20e9be04bd","name":"Statusd/v0.29.0-beta.2/linux-amd64/go1.12.5","caps":["shh/6"],"network":{"localAddress":"192.168.2.56:44667","remoteAddress":"167.99.18.187:443","inbound":false,"trusted":false,"static":true},"protocols":{"shh":"unknown"}}]}
08-29 13:02:19.648  9802  9857 D ReactNativeJS: DEBUG [status-im.utils.handlers:32] - Handling re-frame event:  :signals/signal-received
08-29 13:02:19.649  9802  9857 D ReactNativeJS: DEBUG [status-im.events:691] - :event-str {"type":"discovery.summary","event":[{"enode":"enode://4e0a8db9b73403c9339a2077e911851750fc955db1fc1e09f81a4a56725946884dd5e4d11258eac961f9078a393c45bcab78dd0e3bc74e37ce773b3471d2e29c@206.189.243.171:443","id":"829fad8fd411906d3bb0447e4c228b902d824c3c7685d4032aeecfb4e09f835d","name":"Statusd/v0.29.0-beta.2/linux-amd64/go1.12.5","caps":["shh/6"],"network":{"localAddress":"192.168.2.56:36060","remoteAddress":"206.189.243.171:443","inbound":false,"trusted":false,"static":true},"protocols":{"shh":"unknown"}}]}
08-29 13:02:19.654  9802  9857 D ReactNativeJS: DEBUG [status-im.utils.handlers:32] - Handling re-frame event:  :signals/signal-received
08-29 13:02:19.656  9802  9857 D ReactNativeJS: DEBUG [status-im.events:691] - :event-str {"type":"discovery.summary","event":[{"enode":"enode://4e0a8db9b73403c9339a2077e911851750fc955db1fc1e09f81a4a56725946884dd5e4d11258eac961f9078a393c45bcab78dd0e3bc74e37ce773b3471d2e29c@206.189.243.171:443","id":"829fad8fd411906d3bb0447e4c228b902d824c3c7685d4032aeecfb4e09f835d","name":"Statusd/v0.29.0-beta.2/linux-amd64/go1.12.5","caps":["shh/6"],"network":{"localAddress":"192.168.2.56:36060","remoteAddress":"206.189.243.171:443","inbound":false,"trusted":false,"static":true},"protocols":{"shh":"unknown"}},{"enode":"enode://0d9d65fcd5592df33ed4507ce862b9c748b6dbd1ea3a1deb94e3750052760b4850aa527265bbaf357021d64d5cc53c02b410458e732fafc5b53f257944247760@167.99.18.187:443","id":"98ab721a4762645a887ffb29672a18d81aa86206c9d0243d95bb0b20e9be04bd","name":"Statusd/v0.29.0-beta.2/linux-amd64/go1.12.5","caps":["shh/6"],"network":{"localAddress":"192.168.2.56:44667","remoteAddress":"167.99.18.187:443","inbound":false,"trusted":false,"static":true},"protocols":{"shh":"unknown"}}]}
08-29 13:02:20.483  9802 10123 E GoLog   : INFO [08-29|10:02:20.483] Whisper identity selected                id=c95fcc9cc2dae13730fa7f9e6f5c98d6a4311a8a650bee7dd4d45e2e4101e681 key=0x0478a6f0754526c499952abefb03f02068af69f6e1d0431970bf1943f7cefffc0042f672bee7b3b65297ad6d240d11bb2182e4fdd9ed35a88f0b86ff85032396c1
08-29 13:02:20.490  9802 10123 E GoLog   : INFO [08-29|10:02:20.490] starting publisher                       namespace=Publisher site=Start
08-29 13:02:20.490  9802  9986 I GoLog   : Node: 0478a6f0 Epoch: 0
08-29 13:02:20.496  9802  9987 D StatusModule: Signal event: {"type":"node.login","event":null}
08-29 13:02:20.499  9802  9857 D ReactNativeJS: DEBUG [status-im.utils.handlers:32] - Handling re-frame event:  :signals/signal-received
08-29 13:02:20.500  9802  9857 D ReactNativeJS: DEBUG [status-im.events:691] - :event-str {"type":"node.login","event":null}
08-29 13:02:20.512  9802  9857 D ReactNativeJS: DEBUG [status-im.utils.keychain.core:191] - initializing realm encryption key...
08-29 13:02:20.514  9802  9857 D ReactNativeJS: DEBUG [status-im.utils.keychain.core:173] - PERF initializing realm encryption key... 1567072940513
08-29 13:02:20.516  9802  9857 D ReactNativeJS: DEBUG [status-im.ui.screens.navigation:71] - :navigate-to :home nil
08-29 13:02:20.567  9802  9858 D RNFirebaseMessaging: Firebase token: eq8n7u72GTA:APA91bGftqa4x0IqfGcpj-be8ZwDQIqJFWCKE8uD3bIHggyReq-PTKJfOgVdw354y4N-W5Q22xaPoCwsDkuyLn-QLJZ6kwIZiZjROAcEFi9rJTA_Ey5c7Fql3RTQDpHCmu5pfbi717CZ
08-29 13:02:20.794  9802     0 E Go      : panic: runtime error: invalid memory address or nil pointer dereference
08-29 13:02:20.794  9802     0 E Go      : [signal SIGSEGV: segmentation violation code=0x1 addr=0x4 pc=0xc9c9ad30]
08-29 13:02:20.794  9802     0 E Go      : 
08-29 13:02:20.794  9802  9869 E GoLog   : panic: runtime error: invalid memory address or nil pointer dereference
08-29 13:02:20.794  9802     0 E Go      : goroutine 180935 [running]:
08-29 13:02:20.795  9802     0 E Go      : github.com/status-im/status-go/vendor/github.com/vacp2p/mvds/node.(*Node).Start.func2(0x9b5680a0, 0x11e1a300, 0x0)
08-29 13:02:20.795  9802     0 E Go      : 	/build/go/src/github.com/status-im/status-go/vendor/github.com/vacp2p/mvds/node/node.go:168 +0x198
08-29 13:02:20.796  9802     0 E Go      : created by github.com/status-im/status-go/vendor/github.com/vacp2p/mvds/node.(*Node).Start
08-29 13:02:20.796  9802     0 E Go      : 	/build/go/src/github.com/status-im/status-go/vendor/github.com/vacp2p/mvds/node/node.go:155 +0x60
--------- beginning of crash
08-29 13:02:20.797  9802 10123 F libc    : Fatal signal 6 (SIGABRT), code -6 in tid 10123 (Thread-13), pid 9802 (status.ethereum)
08-29 13:02:20.852  9802  9802 D ScrollView: initGoToTop
08-29 13:02:20.855  9802  9802 D ScrollView: initGoToTop
08-29 13:02:23.747  9802  9802 I Choreographer: Skipped 167 frames!  The application may be doing too much work on its main thread.



```

**Comment by cammellos** [comment]
@Serhy this should be fixed in develop, thanks!

**Comment by Serhy** [comment]
Indeed @cammellos! Can't reproduce anymore with both iOS and Android develop builds (messaging keep working as well disregard the network user is connected to) 
Closing the issue
