### ISSUE TITLE
Crash at signing transaction

### ISSUE THREAD

**Issue by churik** [status-im/status-react#9358]
# Bug Report

## Problem

In some cases Status may crash during signing transaction. 
I can't say in what cases it is possible scenario for real users cc @rachelhamlin 

#### Expected behavior
no crash

#### Actual behavior
Status crashed

#### Notes
First time I see this error is 30/10/2019 on current nightly, couldn't reproduce manually. Caught by e2e in nightly.

### Reproduction

- Open Status
- Restore multiaccount with funds
- Send transaction
Full logcat and video: https://app.saucelabs.com/tests/db30fa3dc5c7479097e5e3dabd27dce0?auth=c16877bbb9f26392e69fd6ab04347912#78

### Additional Information

[comment]: # (Please do your best to fill this out.)
- Status version: nightly 30/10/2019

#### Logs

```
10-30 01:54:12.412  4289  4318 D ReactNativeJS: DEBUG [status-im.utils.handlers:32] - Handling re-frame event:  :signing/transaction-completed
10-30 01:54:12.421  4289  4289 I zygote  : Deoptimizing void androidx.appcompat.widget.AppCompatTextHelper.updateTypefaceAndStyle(android.content.Context, androidx.appcompat.widget.TintTypedArray) due to JIT inline cache
10-30 01:54:12.497  4289  4289 E JavaBinder: !!! FAILED BINDER TRANSACTION !!!  (parcel size = 448)
10-30 01:54:12.498  4289  4289 D AndroidRuntime: Shutting down VM
10-30 01:54:12.498  4289  4289 E AndroidRuntime: FATAL EXCEPTION: main
10-30 01:54:12.498  4289  4289 E AndroidRuntime: Process: im.status.ethereum.pr, PID: 4289
10-30 01:54:12.498  4289  4289 E AndroidRuntime: java.lang.RuntimeException: Adding window failed
10-30 01:54:12.498  4289  4289 E AndroidRuntime: 	at android.view.ViewRootImpl.setView(ViewRootImpl.java:738)
10-30 01:54:12.498  4289  4289 E AndroidRuntime: 	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:356)
10-30 01:54:12.498  4289  4289 E AndroidRuntime: 	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:92)
10-30 01:54:12.498  4289  4289 E AndroidRuntime: 	at android.app.Dialog.show(Dialog.java:330)
10-30 01:54:12.498  4289  4289 E AndroidRuntime: 	at androidx.fragment.app.DialogFragment.onStart(DialogFragment.java:436)
10-30 01:54:12.498  4289  4289 E AndroidRuntime: 	at androidx.fragment.app.Fragment.performStart(Fragment.java:2477)
10-30 01:54:12.498  4289  4289 E AndroidRuntime: 	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1494)
10-30 01:54:12.498  4289  4289 E AndroidRuntime: 	at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
10-30 01:54:12.498  4289  4289 E AndroidRuntime: 	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
10-30 01:54:12.498  4289  4289 E AndroidRuntime: 	at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:802)
10-30 01:54:12.498  4289  4289 E AndroidRuntime: 	at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManager.java:2625)
10-30 01:54:12.498  4289  4289 E AndroidRuntime: 	at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2411)
10-30 01:54:12.498  4289  4289 E AndroidRuntime: 	at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
10-30 01:54:12.498  4289  4289 E AndroidRuntime: 	at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273)
10-30 01:54:12.498  4289  4289 E AndroidRuntime: 	at androidx.fragment.app.FragmentManagerImpl$1.run(FragmentManager.java:733)
10-30 01:54:12.498  4289  4289 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:789)
10-30 01:54:12.498  4289  4289 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:98)
10-30 01:54:12.498  4289  4289 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
10-30 01:54:12.498  4289  4289 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6541)
10-30 01:54:12.498  4289  4289 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
10-30 01:54:12.498  4289  4289 E AndroidRuntime: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
10-30 01:54:12.498  4289  4289 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
10-30 01:54:12.498  4289  4289 E AndroidRuntime: Caused by: android.os.DeadObjectException: Transaction failed on small parcel; remote process probably died
10-30 01:54:12.498  4289  4289 E AndroidRuntime: 	at android.os.BinderProxy.transactNative(Native Method)
10-30 01:54:12.498  4289  4289 E AndroidRuntime: 	at android.os.BinderProxy.transact(Binder.java:748)
10-30 01:54:12.498  4289  4289 E AndroidRuntime: 	at android.view.IWindowSession$Stub$Proxy.addToDisplay(IWindowSession.java:791)
10-30 01:54:12.498  4289  4289 E AndroidRuntime: 	at android.view.ViewRootImpl.setView(ViewRootImpl.java:726)
10-30 01:54:12.498  4289  4289 E AndroidRuntime: 	... 21 more
10-30 01:54:12.499  1637  1703 W InputDispatcher: channel 'd431028 im.status.ethereum.pr/im.status.ethereum.MainActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
10-30 01:54:12.499  1637  1703 E InputDispatcher: channel 'd431028 im.status.ethereum.pr/im.status.ethereum.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
10-30 01:54:12.499  4289  4289 W zygote  : ashmem_create_region failed for 'indirect ref table': Too many open files
10-30 01:54:12.499  4289  4289 W google-breakpad: ExceptionHandler::GenerateDump sys_pipe failed:
10-30 01:54:12.499  4289  4289 W google-breakpad: Too many open files
10-30 01:54:12.499  4289  4289 W google-breakpad: 
10-30 01:54:12.521  7167  4289 W google-breakpad: ExceptionHandler::WaitForContinueSignal sys_read failed:
10-30 01:54:12.521  7167  4289 W google-breakpad: Bad file descriptor
10-30 01:54:12.521  7167  4289 W google-breakpad: 

```

**Comment by churik** [comment]
Couldn't reproduce it (nightly 26/02/2020)
