### ISSUE TITLE
Unable to create account on some devices with Android 6

### ISSUE THREAD

**Issue by churik** [status-im/status-react#9404]
# Bug Report

## Problem
Can't create account on Samsung Galaxy phones (Android 6.0.0 only) - on last step of account creation application is crashed with error:
<img width="147" alt="eeee" src="https://user-images.githubusercontent.com/4557972/68305338-cbfb3d80-00a7-11ea-81d7-edf4007c3b7e.png">

### Additional Information

[comment]: # (Please do your best to fill this out.)
- Status version: nightly 06/12/2019
- Operating System: Android 6.0.0 (Samsung Galaxy)

#### Logs
Full logcat: 
[StatusIm-191104-162132-390c1a-pr-universal.apk_2019_11_6_13_31_32.log](https://github.com/status-im/status-react/files/3814805/StatusIm-191104-162132-390c1a-pr-universal.apk_2019_11_6_13_31_32.log)

[comment]: # (if on Android please replicate bug whilst running adb logcat)

```
11-06 13:31:08.112 E/cr_LibraryLoader( 1967): Unable to load library.
11-06 13:31:08.112 E/cr_LibraryLoader( 1967): java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/com.google.android.webview-1/lib/arm/libwebviewchromium.so" is 32-bit instead of 64-bit
11-06 13:31:08.112 E/cr_LibraryLoader( 1967): 	at java.lang.Runtime.loadLibrary(Runtime.java:372)
11-06 13:31:08.112 E/cr_LibraryLoader( 1967): 	at java.lang.System.loadLibrary(System.java:1076)
11-06 13:31:08.112 E/cr_LibraryLoader( 1967): 	at org.chromium.base.library_loader.LibraryLoader.a(PG:24)
11-06 13:31:08.112 E/cr_LibraryLoader( 1967): 	at org.chromium.base.library_loader.LibraryLoader.a(PG:13)
11-06 13:31:08.112 E/cr_LibraryLoader( 1967): 	at org.chromium.android_webview.AwBrowserProcess.a(PG:16)
11-06 13:31:08.112 E/cr_LibraryLoader( 1967): 	at com.android.webview.chromium.WebViewChromiumFactoryProvider.a(PG:82)
11-06 13:31:08.112 E/cr_LibraryLoader( 1967): 	at com.android.webview.chromium.WebViewChromiumFactoryProvider.<init>(PG:12)
11-06 13:31:08.112 E/cr_LibraryLoader( 1967): 	at java.lang.reflect.Constructor.newInstance(Native Method)
11-06 13:31:08.112 E/cr_LibraryLoader( 1967): 	at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:163)
11-06 13:31:08.112 E/cr_LibraryLoader( 1967): 	at android.webkit.CookieManager.getInstance(CookieManager.java:39)
11-06 13:31:08.112 E/cr_LibraryLoader( 1967): 	at im.status.ethereum.module.StatusModule.clearCookies(StatusModule.java:961)
11-06 13:31:08.112 E/cr_LibraryLoader( 1967): 	at java.lang.reflect.Method.invoke(Native Method)
11-06 13:31:08.112 E/cr_LibraryLoader( 1967): 	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
11-06 13:31:08.112 E/cr_LibraryLoader( 1967): 	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
11-06 13:31:08.112 E/cr_LibraryLoader( 1967): 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
11-06 13:31:08.112 E/cr_LibraryLoader( 1967): 	at android.os.Handler.handleCallback(Handler.java:739)
11-06 13:31:08.112 E/cr_LibraryLoader( 1967): 	at android.os.Handler.dispatchMessage(Handler.java:95)
11-06 13:31:08.112 E/cr_LibraryLoader( 1967): 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
11-06 13:31:08.112 E/cr_LibraryLoader( 1967): 	at android.os.Looper.loop(Looper.java:158)
11-06 13:31:08.112 E/cr_LibraryLoader( 1967): 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:232)
11-06 13:31:08.112 E/cr_LibraryLoader( 1967): 	at java.lang.Thread.run(Thread.java:818)
11-06 13:31:08.112 E/WebViewFactory( 1967): error instantiating provider
11-06 13:31:08.112 E/WebViewFactory( 1967): java.lang.reflect.InvocationTargetException
11-06 13:31:08.112 E/WebViewFactory( 1967): 	at java.lang.reflect.Constructor.newInstance(Native Method)
11-06 13:31:08.112 E/WebViewFactory( 1967): 	at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:163)
11-06 13:31:08.112 E/WebViewFactory( 1967): 	at android.webkit.CookieManager.getInstance(CookieManager.java:39)
11-06 13:31:08.112 E/WebViewFactory( 1967): 	at im.status.ethereum.module.StatusModule.clearCookies(StatusModule.java:961)
11-06 13:31:08.112 E/WebViewFactory( 1967): 	at java.lang.reflect.Method.invoke(Native Method)
11-06 13:31:08.112 E/WebViewFactory( 1967): 	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
11-06 13:31:08.112 E/WebViewFactory( 1967): 	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
11-06 13:31:08.112 E/WebViewFactory( 1967): 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
11-06 13:31:08.112 E/WebViewFactory( 1967): 	at android.os.Handler.handleCallback(Handler.java:739)
11-06 13:31:08.112 E/WebViewFactory( 1967): 	at android.os.Handler.dispatchMessage(Handler.java:95)
11-06 13:31:08.112 E/WebViewFactory( 1967): 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
11-06 13:31:08.112 E/WebViewFactory( 1967): 	at android.os.Looper.loop(Looper.java:158)
11-06 13:31:08.112 E/WebViewFactory( 1967): 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:232)
11-06 13:31:08.112 E/WebViewFactory( 1967): 	at java.lang.Thread.run(Thread.java:818)
11-06 13:31:08.112 E/WebViewFactory( 1967): Caused by: java.lang.RuntimeException: Cannot load WebView
11-06 13:31:08.112 E/WebViewFactory( 1967): 	at org.chromium.android_webview.AwBrowserProcess.a(PG:20)
11-06 13:31:08.112 E/WebViewFactory( 1967): 	at com.android.webview.chromium.WebViewChromiumFactoryProvider.a(PG:82)
11-06 13:31:08.112 E/WebViewFactory( 1967): 	at com.android.webview.chromium.WebViewChromiumFactoryProvider.<init>(PG:12)
```

**Comment by churik** [comment]
@rachelhamlin didn't include it in V1, because don't have info about how many users use Android 6.0.0 on Samsung Galaxy devices.

**Comment by rachelhamlin** [comment]
Only ~3% of our current beta installs, so we can leave this unprioritized.

**Comment by churik** [comment]
App doesn't start on LG G5 Android 6.
Logcat: [StatusIm-200116-025900-5ab476-nightly-universal.apk_2020_1_16_11_11_0.log](https://github.com/status-im/status-react/files/4070858/StatusIm-200116-025900-5ab476-nightly-universal.apk_2020_1_16_11_11_0.log)
