### ISSUE TITLE
App crashes on Android 8.1 once launched

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#9879]
# Bug Report

## Problem

Install Status develop nightly (or RC) from January 22nd on Android 8.1 (Samsung Galaxy J7) and Android 6.0.1 (Samsung Galaxy Note 4)

But OK on Android 9 (Samsung Galaxy S8)

#### Expected behavior

Can launch Status

#### Actual behavior

Status crashes on Android 8.1 when launch

<img width="346" alt="Screenshot 2020-01-21 at 17 40 25" src="https://user-images.githubusercontent.com/8749671/72884062-25215780-3d0e-11ea-9fb3-0ed26770c3c4.png">

### Reproduction

- Install Status
- Launch Status

### Additional Information
- Status version: 
- Operating System: Android 6.0.1 and Android 8 (not sure about Android 7 yet), but OK on Android 9

#### Logs

```

--------- beginning of crash
01-22 11:57:51.631 13280 13323 E AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
01-22 11:57:51.631 13280 13323 E AndroidRuntime: Process: im.status.ethereum, PID: 13280
01-22 11:57:51.631 13280 13323 E AndroidRuntime: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/im.status.ethereum--U90qo-PohLu8ifKFF2eFA==/base.apk"],nativeLibraryDirectories=[/data/app/im.status.ethereum--U90qo-PohLu8ifKFF2eFA==/lib/arm, /data/app/im.status.ethereum--U90qo-PohLu8ifKFF2eFA==/base.apk!/lib/armeabi-v7a, /system/lib, /system/vendor/lib]]] couldn't find "libgojni.so"
01-22 11:57:51.631 13280 13323 E AndroidRuntime: 	at java.lang.Runtime.loadLibrary0(Runtime.java:1011)
01-22 11:57:51.631 13280 13323 E AndroidRuntime: 	at java.lang.System.loadLibrary(System.java:1657)
01-22 11:57:51.631 13280 13323 E AndroidRuntime: 	at go.Seq.<clinit>(Seq.java:37)
01-22 11:57:51.631 13280 13323 E AndroidRuntime: 	at go.Seq.touch(Unknown Source:0)
01-22 11:57:51.631 13280 13323 E AndroidRuntime: 	at statusgo.Statusgo.<clinit>(Statusgo.java:11)
01-22 11:57:51.631 13280 13323 E AndroidRuntime: 	at statusgo.Statusgo.setMobileSignalHandler(Native Method)
01-22 11:57:51.631 13280 13323 E AndroidRuntime: 	at im.status.ethereum.module.StatusModule.onHostResume(StatusModule.java:88)
01-22 11:57:51.631 13280 13323 E AndroidRuntime: 	at com.facebook.react.bridge.ReactContext.onHostResume(ReactContext.java:214)
01-22 11:57:51.631 13280 13323 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager.moveToResumedLifecycleState(ReactInstanceManager.java:660)
01-22 11:57:51.631 13280 13323 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager.moveReactContextToCurrentLifecycleState(ReactInstanceManager.java:695)
01-22 11:57:51.631 13280 13323 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager.setupReactContext(ReactInstanceManager.java:1008)
01-22 11:57:51.631 13280 13323 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager.access$1400(ReactInstanceManager.java:125)
01-22 11:57:51.631 13280 13323 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager$5$2.run(ReactInstanceManager.java:972)
01-22 11:57:51.631 13280 13323 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:790)
01-22 11:57:51.631 13280 13323 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
01-22 11:57:51.631 13280 13323 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:26)
01-22 11:57:51.631 13280 13323 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
01-22 11:57:51.631 13280 13323 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:225)
01-22 11:57:51.631 13280 13323 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:764)
01-22 11:57:51.654 13280 13326 D ScrollView: initGoToTop
01-22 11:57:51.667 13280 13326 D ScrollView: initGoToTop
01-22 11:57:51.688 13280 13326 D InputTransport: Input channel constructed: fd=81
01-22 11:57:51.688 13280 13326 D ViewRootImpl@c27d5cc[MainActivity]: setView = DecorView@7e26015[MainActivity] TM=true MM=false
01-22 11:57:51.692 13280 13326 D ViewRootImpl@c27d5cc[MainActivity]: dispatchAttachedToWindow
01-22 11:57:51.707 13280 13322 W ResourceType: No package identifier when getting value for resource number 0x00000000
01-22 11:57:51.717 13280 13280 D ViewRootImpl@5dd8ac2[MainActivity]: MSG_RESIZED: frame=Rect(0, 0 - 1080, 1920) ci=Rect(0, 0 - 0, 0) vi=Rect(0, 0 - 0, 0) or=1
01-22 11:57:51.750 13280 13326 V Surface : sf_framedrop debug : 0x4f4c, game : false, logging : 0
01-22 11:57:51.750 13280 13326 D ViewRootImpl@c27d5cc[MainActivity]: Relayout returned: old=[0,0][0,0] new=[28,501][1052,1419] result=0x27 surface={valid=true 3670366208} changed=true
01-22 11:57:51.758 13280 13299 D mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, egl_color_buffer_format *, EGLBoolean) returns 0x3000,  [1192x1086]-format:1


```

**Comment by churik** [comment]
Can't reproduce the same behaviour on Samsung Galaxy Note 9, Android 8.1
But app is crashed after creating account on tapping `Let's go` button
[StatusIm-200122-085814-aaa51a-nightly-universal.apk_2020_1_22_10_14_5.log](https://github.com/status-im/status-react/files/4096501/StatusIm-200122-085814-aaa51a-nightly-universal.apk_2020_1_22_10_14_5.log)

**Comment by pedropombeiro** [comment]
I tried on Genymotion with Nexus 6P Android 7.1.0 and couldn't reproduce. Does this only happen on real devices?

**Comment by Serhy** [comment]
Yea, I could not reproduce latest nightly x86.apk (https://status-im.ams3.digitaloceanspaces.com/StatusIm-200123-025959-c9e7d8-nightly-x86.apk) on Genymotion emulators with Android 8 and Android 7.1
But universal.apk (https://status-im.ams3.digitaloceanspaces.com/StatusIm-200123-025959-c9e7d8-nightly-universal.apk) gives crash on real devices.

**Comment by Serhy** [comment]
I can check from which nightly it started appear.

**Comment by pedropombeiro** [comment]
Indeed, the armeabi-v7a platform is missing the status-go `libgojni.so` file. I'll look into it.

![image](https://user-images.githubusercontent.com/138074/72983796-7a2e9d80-3de2-11ea-9abe-dbce825a0463.png)

**Comment by pedropombeiro** [comment]
@Serhy can you please test https://ci.status.im/job/status-react/job/prs/job/android/job/PR-9891/1/artifact/result/StatusIm-200123-122305-47e95e-universal.apk ?

**Comment by pedropombeiro** [comment]
The `libgojni.so` file is present now, so it should be working now.

**Comment by Serhy** [comment]
Yes, can confirm it's working now on devices where it was crashing before
Thanks a lot @pombeiro!!
